DROP VIEW IF EXISTS user_aggregates;

DROP TABLE IF EXISTS relationships CASCADE;

DROP TABLE IF EXISTS message_reactions CASCADE;

DROP TABLE IF EXISTS message_attachments CASCADE;

DROP TABLE IF EXISTS channel_invites CASCADE;

DROP TABLE IF EXISTS channel_members CASCADE;

DROP TABLE IF EXISTS messages CASCADE;

DROP TABLE IF EXISTS channels CASCADE;

DROP TABLE IF EXISTS sessions CASCADE;

DROP TABLE IF EXISTS user_mfa_backup_codes CASCADE;

DROP TABLE IF EXISTS user_mfa CASCADE;

DROP TABLE IF EXISTS user_profiles CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS outbox_events CASCADE;

DROP EXTENSION IF EXISTS citext;

