services:
  postgres:
    image: postgres:18-alpine
    container_name: bonfire_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bonfire_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: bonfire_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    # Optional: command to enable persistence (AOF)
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata:
  redis_data:
