// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID             pgtype.UUID        `json:"id"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LockedBy       pgtype.UUID        `json:"locked_by"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	LastError      pgtype.Text        `json:"last_error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ClientIP         netip.Addr         `json:"client_ip"`
	UserAgent        string             `json:"user_agent"`
	OS               string             `json:"os"`
	Browser          string             `json:"browser"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserProfile struct {
	UserID      pgtype.UUID        `json:"user_id"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
