// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OutboxEvent struct {
	ID            pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
	EventType     string
	Payload       []byte
	LastError     pgtype.Text
	Attempts      int32
	MaxAttempts   int32
	NextAttemptAt pgtype.Timestamptz
}

type Session struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
}

type User struct {
	ID                     pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	LastVerificationSentAt pgtype.Timestamptz
	VerifiedAt             pgtype.Timestamptz
	Email                  string
	Username               string
	PasswordHash           string
	TotpSecret             pgtype.Text
	IsTotpEnabled          bool
	Flags                  int64
}

type UserProfile struct {
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DisplayName pgtype.Text
}
