package repository

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"bonfire-api/internal/domain"
)

// Ensure PostgresRepository strictly implements domain.DBRepository at compile time
var _ domain.DBRepository = (*PostgresRepository)(nil)

type PostgresRepository struct {
	pool *pgxpool.Pool
}

func NewPostgresRepository(pool *pgxpool.Pool) *PostgresRepository {
	return &PostgresRepository{
		pool: pool,
	}
}

// WithTx handles opening, wrapping, committing, and rolling back the pgx transaction
func (r *PostgresRepository) WithTx(ctx context.Context, fn func(tx domain.TxUnit) error) error {
	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("beginning transaction: %w", err)
	}

	// Defer a rollback to safely protect against panics or uncommitted errors
	defer tx.Rollback(context.WithoutCancel(ctx))

	// Bind SQLC's generated queries directly to this live transaction object
	txQueries := New(tx)
	adapter := &txUnitAdapter{q: txQueries}

	// Pass the adapter directly into the application service closure
	if err := fn(adapter); err != nil {
		return err // Implicit rollback occurs here
	}

	// Commit using a detached context so it survives client hangups
	if err := tx.Commit(context.WithoutCancel(ctx)); err != nil {
		return fmt.Errorf("committing transaction: %w", err)
	}

	return nil
}

// txUnitAdapter bridges SQLC's generated concrete types with your pristine domain.TxUnit interface
type txUnitAdapter struct {
	q *Queries // Struct generated by SQLC
}

func (a *txUnitAdapter) CreateUser(ctx context.Context, email, username, passwordHash string) (pgtype.UUID, error) {
	userRow, err := a.q.CreateUser(ctx, CreateUserParams{
		Email:        email,
		Username:     username,
		PasswordHash: passwordHash,
	})
	if err != nil {
		return pgtype.UUID{}, err
	}
	return userRow.ID, nil
}

func (a *txUnitAdapter) CreateUserProfile(ctx context.Context, userID pgtype.UUID, displayName *string) (pgtype.UUID, error) {
	var dispText pgtype.Text
	if displayName != nil {
		dispText = pgtype.Text{String: *displayName, Valid: true}
	}

	profileRow, err := a.q.CreateUserProfile(ctx, CreateUserProfileParams{
		UserID:      userID,
		DisplayName: dispText,
	})
	if err != nil {
		return pgtype.UUID{}, err
	}
	return profileRow.UserID, nil
}
