// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one

INSERT INTO outbox_events (event_type, payload)
VALUES ($1, $2)
RETURNING id, event_type, payload, created_at, processed_at, last_error, attempts, max_attempts, next_attempt_at
`

type CreateOutboxEventParams struct {
	EventType string
	Payload   []byte
}

type CreateOutboxEventRow struct {
	ID            pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	ProcessedAt   pgtype.Timestamptz
	LastError     pgtype.Text
	Attempts      int32
	MaxAttempts   int32
	NextAttemptAt pgtype.Timestamptz
}

// outbox_events
func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (CreateOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.EventType, arg.Payload)
	var i CreateOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.LastError,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (
    user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateSessionParams struct {
	UserID       pgtype.UUID
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

// sessions
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (email, username, password_hash, flags)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, email, username, flags
`

type CreateUserParams struct {
	Email        string
	Username     string
	PasswordHash string
	Flags        int64
}

type CreateUserRow struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Email     string
	Username  string
	Flags     int64
}

// users
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Flags,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Username,
		&i.Flags,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one

INSERT INTO user_profiles (user_id, display_name)
VALUES ($1, $2)
RETURNING user_id, created_at, display_name
`

type CreateUserProfileParams struct {
	UserID      pgtype.UUID
	DisplayName pgtype.Text
}

type CreateUserProfileRow struct {
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	DisplayName pgtype.Text
}

// user_profiles
func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (CreateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, createUserProfile, arg.UserID, arg.DisplayName)
	var i CreateUserProfileRow
	err := row.Scan(&i.UserID, &i.CreatedAt, &i.DisplayName)
	return i, err
}

const deleteAllSessionsExcept = `-- name: DeleteAllSessionsExcept :exec
DELETE FROM sessions 
WHERE user_id = $1 
  AND id != $2
`

type DeleteAllSessionsExceptParams struct {
	UserID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) DeleteAllSessionsExcept(ctx context.Context, arg DeleteAllSessionsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsExcept, arg.UserID, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteSessionParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE users
SET totp_secret = NULL, is_totp_enabled = FALSE
WHERE id = $1
`

func (q *Queries) DisableUserTOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableUserTOTP, id)
	return err
}

const enableUserTOTP = `-- name: EnableUserTOTP :exec
UPDATE users
SET totp_secret = $1, is_totp_enabled = TRUE
WHERE id = $2
`

type EnableUserTOTPParams struct {
	TotpSecret pgtype.Text
	ID         pgtype.UUID
}

func (q *Queries) EnableUserTOTP(ctx context.Context, arg EnableUserTOTPParams) error {
	_, err := q.db.Exec(ctx, enableUserTOTP, arg.TotpSecret, arg.ID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
FROM sessions
WHERE refresh_token = $1 LIMIT 1
`

type GetSessionRow struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	RefreshToken string
	UserAgent    string
	ClientIp     string
	IsBlocked    bool
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetSession(ctx context.Context, refreshToken string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, refreshToken)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUnprocessedOutboxEvents = `-- name: GetUnprocessedOutboxEvents :many
SELECT id, event_type, payload, attempts
FROM outbox_events
WHERE processed_at IS NULL
  AND attempts < max_attempts
  AND next_attempt_at <= CURRENT_TIMESTAMP
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetUnprocessedOutboxEventsRow struct {
	ID        pgtype.UUID
	EventType string
	Payload   []byte
	Attempts  int32
}

func (q *Queries) GetUnprocessedOutboxEvents(ctx context.Context, limit int32) ([]GetUnprocessedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getUnprocessedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnprocessedOutboxEventsRow
	for rows.Next() {
		var i GetUnprocessedOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAuthCredentials = `-- name: GetUserAuthCredentials :one
SELECT id, password_hash, is_totp_enabled
FROM users 
WHERE email = $1 LIMIT 1
`

type GetUserAuthCredentialsRow struct {
	ID            pgtype.UUID
	PasswordHash  string
	IsTotpEnabled bool
}

func (q *Queries) GetUserAuthCredentials(ctx context.Context, email string) (GetUserAuthCredentialsRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthCredentials, email)
	var i GetUserAuthCredentialsRow
	err := row.Scan(&i.ID, &i.PasswordHash, &i.IsTotpEnabled)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, deleted_at, verified_at, last_verification_sent_at, email, username
FROM users 
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID                     pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	VerifiedAt             pgtype.Timestamptz
	LastVerificationSentAt pgtype.Timestamptz
	Email                  string
	Username               string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VerifiedAt,
		&i.LastVerificationSentAt,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, deleted_at, verified_at, email, username
FROM users 
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	VerifiedAt pgtype.Timestamptz
	Email      string
	Username   string
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VerifiedAt,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, deleted_at, verified_at, email, username
FROM users
WHERE username = $1 LIMIT 1
`

type GetUserByUsernameRow struct {
	ID         pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	VerifiedAt pgtype.Timestamptz
	Email      string
	Username   string
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.VerifiedAt,
		&i.Email,
		&i.Username,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, created_at, updated_at, display_name
FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many
SELECT id, user_agent, client_ip, created_at, last_seen_at, refresh_token 
FROM sessions 
WHERE user_id = $1 AND is_blocked = false
`

type GetUserSessionsRow struct {
	ID           pgtype.UUID
	UserAgent    string
	ClientIp     string
	CreatedAt    pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	RefreshToken string
}

func (q *Queries) GetUserSessions(ctx context.Context, userID pgtype.UUID) ([]GetUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSessionsRow
	for rows.Next() {
		var i GetUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserAgent,
			&i.ClientIp,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RefreshToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTOTPSecret = `-- name: GetUserTOTPSecret :one
SELECT totp_secret
FROM users 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserTOTPSecret(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserTOTPSecret, id)
	var totp_secret pgtype.Text
	err := row.Scan(&totp_secret)
	return totp_secret, err
}

const markOutboxEventProcessed = `-- name: MarkOutboxEventProcessed :exec
UPDATE outbox_events
SET processed_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) MarkOutboxEventProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventProcessed, id)
	return err
}

const recordOutboxEventFailure = `-- name: RecordOutboxEventFailure :exec
UPDATE outbox_events
SET 
    attempts = attempts + 1,
    last_error = $2,
    next_attempt_at = $3
WHERE id = $1
`

type RecordOutboxEventFailureParams struct {
	ID            pgtype.UUID
	LastError     pgtype.Text
	NextAttemptAt pgtype.Timestamptz
}

func (q *Queries) RecordOutboxEventFailure(ctx context.Context, arg RecordOutboxEventFailureParams) error {
	_, err := q.db.Exec(ctx, recordOutboxEventFailure, arg.ID, arg.LastError, arg.NextAttemptAt)
	return err
}

const updateSessionRefreshToken = `-- name: UpdateSessionRefreshToken :exec
UPDATE sessions
SET refresh_token = $2,
    expires_at = $3
WHERE id = $1
`

type UpdateSessionRefreshTokenParams struct {
	ID           pgtype.UUID
	RefreshToken string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) UpdateSessionRefreshToken(ctx context.Context, arg UpdateSessionRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionRefreshToken, arg.ID, arg.RefreshToken, arg.ExpiresAt)
	return err
}

const updateUserLastVerificationSent = `-- name: UpdateUserLastVerificationSent :exec
UPDATE users
SET last_verification_sent_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateUserLastVerificationSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastVerificationSent, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const validateUserCredentialsAvailability = `-- name: ValidateUserCredentialsAvailability :one
SELECT
    NOT EXISTS (
        SELECT 1
        FROM users u
        WHERE u.email = $1
          AND u.deleted_at IS NULL
    ) AS email_available,
    NOT EXISTS (
        SELECT 1
        FROM users u
        WHERE u.username = $2
          AND u.deleted_at IS NULL
    ) AS username_available
`

type ValidateUserCredentialsAvailabilityParams struct {
	Email    string
	Username string
}

type ValidateUserCredentialsAvailabilityRow struct {
	EmailAvailable    bool
	UsernameAvailable bool
}

func (q *Queries) ValidateUserCredentialsAvailability(ctx context.Context, arg ValidateUserCredentialsAvailabilityParams) (ValidateUserCredentialsAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, validateUserCredentialsAvailability, arg.Email, arg.Username)
	var i ValidateUserCredentialsAvailabilityRow
	err := row.Scan(&i.EmailAvailable, &i.UsernameAvailable)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET verified_at = CURRENT_TIMESTAMP,
    flags = flags | $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND verified_at IS NULL
`

type VerifyUserEmailParams struct {
	ID    pgtype.UUID
	Flags int64
}

func (q *Queries) VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, arg.ID, arg.Flags)
	return err
}
