// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_channels.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelMember = `-- name: AddChannelMember :exec
INSERT INTO channel_members(channel_id, user_id)
    VALUES ($1, $2)
`

type AddChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

// Binds a distinct user identity to a targeted channel access group
func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error {
	_, err := q.db.Exec(ctx, addChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels(type, name, guild_id)
    VALUES ($1, $2, $3)
RETURNING
    id, type, guild_id, name, created_at, updated_at
`

type CreateChannelParams struct {
	Type    int16       `json:"type"`
	Name    pgtype.Text `json:"name"`
	GuildID pgtype.UUID `json:"guild_id"`
}

// Spins up the foundation shell container for a message feed
func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.Type, arg.Name, arg.GuildID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.GuildID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSharedDMChannel = `-- name: FindSharedDMChannel :one
SELECT
    c.id
FROM
    channels c
    JOIN channel_members cm1 ON c.id = cm1.channel_id
    JOIN channel_members cm2 ON c.id = cm2.channel_id
WHERE
    c.type = 1
    AND cm1.user_id = $1
    AND cm2.user_id = $2
LIMIT 1
`

type FindSharedDMChannelParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

// Checks to see if an active type 1 (DM) channel exists between two specified users
func (q *Queries) FindSharedDMChannel(ctx context.Context, arg FindSharedDMChannelParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findSharedDMChannel, arg.UserID, arg.UserID_2)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
