// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_user_profiles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userProfileCheckDisplayNameAvailability = `-- name: UserProfileCheckDisplayNameAvailability :one
SELECT
    NOT EXISTS (
        SELECT
            1
        FROM
            user_profiles
        WHERE
            lower(display_name) = lower($1)) AS available
`

func (q *Queries) UserProfileCheckDisplayNameAvailability(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, userProfileCheckDisplayNameAvailability, lower)
	var available bool
	err := row.Scan(&available)
	return available, err
}

const userProfileCreate = `-- name: UserProfileCreate :one
INSERT INTO user_profiles(user_id, display_name)
    VALUES ($1, $2)
RETURNING
    user_id, created_at, updated_at, display_name
`

type UserProfileCreateParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) UserProfileCreate(ctx context.Context, arg UserProfileCreateParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileCreate, arg.UserID, arg.DisplayName)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const userProfileDelete = `-- name: UserProfileDelete :exec
DELETE FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) UserProfileDelete(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userProfileDelete, userID)
	return err
}

const userProfileGet = `-- name: UserProfileGet :one
SELECT
    user_id, created_at, updated_at, display_name
FROM
    user_profiles
WHERE
    user_id = $1
LIMIT 1
`

func (q *Queries) UserProfileGet(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileGet, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const userProfileGetByDisplayName = `-- name: UserProfileGetByDisplayName :one
SELECT
    user_id, created_at, updated_at, display_name
FROM
    user_profiles
WHERE
    lower(display_name) = lower($1)
LIMIT 1
`

func (q *Queries) UserProfileGetByDisplayName(ctx context.Context, lower string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileGetByDisplayName, lower)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const userProfileUpdateDisplayName = `-- name: UserProfileUpdateDisplayName :exec
UPDATE
    user_profiles
SET
    display_name = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE
    user_id = $1
`

type UserProfileUpdateDisplayNameParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) UserProfileUpdateDisplayName(ctx context.Context, arg UserProfileUpdateDisplayNameParams) error {
	_, err := q.db.Exec(ctx, userProfileUpdateDisplayName, arg.UserID, arg.DisplayName)
	return err
}
