// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_user_sessions.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const userSessionCreate = `-- name: UserSessionCreate :one
INSERT INTO user_sessions(user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at)
    VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
`

type UserSessionCreateParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     netip.Addr         `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UserSessionCreate(ctx context.Context, arg UserSessionCreateParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, userSessionCreate,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ClientIp,
		&i.UserAgent,
	)
	return i, err
}

const userSessionDelete = `-- name: UserSessionDelete :exec
DELETE FROM user_sessions
WHERE id = $1
    AND user_id = $2
`

type UserSessionDeleteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UserSessionDelete(ctx context.Context, arg UserSessionDeleteParams) error {
	_, err := q.db.Exec(ctx, userSessionDelete, arg.ID, arg.UserID)
	return err
}

const userSessionDeleteAllExcept = `-- name: UserSessionDeleteAllExcept :exec
DELETE FROM user_sessions
WHERE user_id = $1
    AND id != $2
`

type UserSessionDeleteAllExceptParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UserSessionDeleteAllExcept(ctx context.Context, arg UserSessionDeleteAllExceptParams) error {
	_, err := q.db.Exec(ctx, userSessionDeleteAllExcept, arg.UserID, arg.ID)
	return err
}

const userSessionGet = `-- name: UserSessionGet :one
SELECT
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
FROM
    user_sessions
WHERE
    refresh_token = $1
LIMIT 1
`

func (q *Queries) UserSessionGet(ctx context.Context, refreshToken string) (UserSession, error) {
	row := q.db.QueryRow(ctx, userSessionGet, refreshToken)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ClientIp,
		&i.UserAgent,
	)
	return i, err
}

const userSessionListByUser = `-- name: UserSessionListByUser :many
SELECT
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
FROM
    user_sessions
WHERE
    user_id = $1
    AND is_blocked = FALSE
ORDER BY
    last_seen_at DESC
`

func (q *Queries) UserSessionListByUser(ctx context.Context, userID pgtype.UUID) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, userSessionListByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RefreshToken,
			&i.IsBlocked,
			&i.ClientIp,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userSessionMarkBlocked = `-- name: UserSessionMarkBlocked :exec
UPDATE
    user_sessions
SET
    is_blocked = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) UserSessionMarkBlocked(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userSessionMarkBlocked, id)
	return err
}

const userSessionUpdateLastSeen = `-- name: UserSessionUpdateLastSeen :exec
UPDATE
    user_sessions
SET
    last_seen_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) UserSessionUpdateLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userSessionUpdateLastSeen, id)
	return err
}

const userSessionUpdateRefreshToken = `-- name: UserSessionUpdateRefreshToken :exec
UPDATE
    user_sessions
SET
    refresh_token = $2,
    expires_at = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

type UserSessionUpdateRefreshTokenParams struct {
	ID           pgtype.UUID        `json:"id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UserSessionUpdateRefreshToken(ctx context.Context, arg UserSessionUpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, userSessionUpdateRefreshToken, arg.ID, arg.RefreshToken, arg.ExpiresAt)
	return err
}
