// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_user_profiles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userProfileCount = `-- name: UserProfileCount :one
SELECT
    COUNT(*)
FROM
    user_profiles
`

// ==========================================
// META
// ==========================================
func (q *Queries) UserProfileCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, userProfileCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userProfileCreate = `-- name: UserProfileCreate :one
INSERT INTO user_profiles(user_id, display_name)
    VALUES ($1, $2)
RETURNING
    user_id, created_at, updated_at, display_name
`

type UserProfileCreateParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) UserProfileCreate(ctx context.Context, arg UserProfileCreateParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileCreate, arg.UserID, arg.DisplayName)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const userProfileDeleteByUserID = `-- name: UserProfileDeleteByUserID :exec
DELETE FROM user_profiles
WHERE user_id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) UserProfileDeleteByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userProfileDeleteByUserID, userID)
	return err
}

const userProfileGetByDisplayName = `-- name: UserProfileGetByDisplayName :one
SELECT
    user_id, created_at, updated_at, display_name
FROM
    user_profiles
WHERE
    lower(display_name) = lower($1)
LIMIT 1
`

func (q *Queries) UserProfileGetByDisplayName(ctx context.Context, lower string) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileGetByDisplayName, lower)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const userProfileGetByUserID = `-- name: UserProfileGetByUserID :one
SELECT
    user_id, created_at, updated_at, display_name
FROM
    user_profiles
WHERE
    user_id = $1
LIMIT 1
`

// ==========================================
// GET
// ==========================================
func (q *Queries) UserProfileGetByUserID(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileGetByUserID, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}

const userProfileUpdateDisplayName = `-- name: UserProfileUpdateDisplayName :one
UPDATE
    user_profiles
SET
    display_name = $2
WHERE
    user_id = $1
RETURNING
    user_id, created_at, updated_at, display_name
`

type UserProfileUpdateDisplayNameParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	DisplayName string      `json:"display_name"`
}

// ==========================================
// UPDATE
// ==========================================
func (q *Queries) UserProfileUpdateDisplayName(ctx context.Context, arg UserProfileUpdateDisplayNameParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileUpdateDisplayName, arg.UserID, arg.DisplayName)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
	)
	return i, err
}
