// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_sessions.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCount = `-- name: SessionCount :one
SELECT
    COUNT(*)
FROM
    sessions
`

// ==========================================
// META
// ==========================================
func (q *Queries) SessionCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sessionCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions(id, user_id, refresh_token, user_agent, client_ip, is_blocked, expires_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
`

type SessionCreateParams struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIP     netip.Addr         `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIP,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ClientIP,
		&i.UserAgent,
	)
	return i, err
}

const sessionDelete = `-- name: SessionDelete :exec
DELETE FROM sessions
WHERE id = $1
    AND user_id = $2
`

type SessionDeleteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

// ==========================================
// DELETE
// ==========================================
func (q *Queries) SessionDelete(ctx context.Context, arg SessionDeleteParams) error {
	_, err := q.db.Exec(ctx, sessionDelete, arg.ID, arg.UserID)
	return err
}

const sessionDeleteAllExcept = `-- name: SessionDeleteAllExcept :exec
DELETE FROM sessions
WHERE user_id = $1
    AND id != $2
`

type SessionDeleteAllExceptParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SessionDeleteAllExcept(ctx context.Context, arg SessionDeleteAllExceptParams) error {
	_, err := q.db.Exec(ctx, sessionDeleteAllExcept, arg.UserID, arg.ID)
	return err
}

const sessionGetByID = `-- name: SessionGetByID :one
SELECT
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
FROM
    sessions
WHERE
    id = $1
LIMIT 1
`

// ==========================================
// GET
// ==========================================
func (q *Queries) SessionGetByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGetByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ClientIP,
		&i.UserAgent,
	)
	return i, err
}

const sessionGetByRefreshToken = `-- name: SessionGetByRefreshToken :one
SELECT
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
FROM
    sessions
WHERE
    refresh_token = $1
    AND is_blocked = FALSE
    AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

func (q *Queries) SessionGetByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGetByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ClientIP,
		&i.UserAgent,
	)
	return i, err
}

const sessionListActiveByUserID = `-- name: SessionListActiveByUserID :many
SELECT
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
FROM
    sessions
WHERE
    user_id = $1
    AND is_blocked = FALSE
    AND expires_at > CURRENT_TIMESTAMP
ORDER BY
    last_seen_at DESC
`

func (q *Queries) SessionListActiveByUserID(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionListActiveByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RefreshToken,
			&i.IsBlocked,
			&i.ClientIP,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionListBlockedByUserID = `-- name: SessionListBlockedByUserID :many
SELECT
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
FROM
    sessions
WHERE
    user_id = $1
    AND is_blocked = TRUE
ORDER BY
    last_seen_at DESC
`

func (q *Queries) SessionListBlockedByUserID(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionListBlockedByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RefreshToken,
			&i.IsBlocked,
			&i.ClientIP,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionListByUserID = `-- name: SessionListByUserID :many
SELECT
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
FROM
    sessions
WHERE
    user_id = $1
ORDER BY
    last_seen_at DESC
`

// ==========================================
// LIST
// ==========================================
func (q *Queries) SessionListByUserID(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionListByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RefreshToken,
			&i.IsBlocked,
			&i.ClientIP,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionListExpiredByUserID = `-- name: SessionListExpiredByUserID :many
SELECT
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
FROM
    sessions
WHERE
    user_id = $1
    AND expires_at <= CURRENT_TIMESTAMP
ORDER BY
    last_seen_at DESC
`

func (q *Queries) SessionListExpiredByUserID(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionListExpiredByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.LastSeenAt,
			&i.RefreshToken,
			&i.IsBlocked,
			&i.ClientIP,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionMarkBlocked = `-- name: SessionMarkBlocked :one
UPDATE
    sessions
SET
    is_blocked = TRUE
WHERE
    id = $1
RETURNING
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
`

func (q *Queries) SessionMarkBlocked(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionMarkBlocked, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ClientIP,
		&i.UserAgent,
	)
	return i, err
}

const sessionPurgeExpired = `-- name: SessionPurgeExpired :exec
DELETE FROM sessions
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) SessionPurgeExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sessionPurgeExpired)
	return err
}

const sessionUpdateLastSeen = `-- name: SessionUpdateLastSeen :one
UPDATE
    sessions
SET
    last_seen_at = CURRENT_TIMESTAMP
WHERE
    id = $1
RETURNING
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
`

func (q *Queries) SessionUpdateLastSeen(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionUpdateLastSeen, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ClientIP,
		&i.UserAgent,
	)
	return i, err
}

const sessionUpdateRefreshToken = `-- name: SessionUpdateRefreshToken :one
UPDATE
    sessions
SET
    refresh_token = $2,
    expires_at = $3
WHERE
    id = $1
RETURNING
    id, user_id, created_at, updated_at, expires_at, last_seen_at, refresh_token, is_blocked, client_ip, user_agent
`

type SessionUpdateRefreshTokenParams struct {
	ID           pgtype.UUID        `json:"id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// ==========================================
// UPDATE
// ==========================================
func (q *Queries) SessionUpdateRefreshToken(ctx context.Context, arg SessionUpdateRefreshTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionUpdateRefreshToken, arg.ID, arg.RefreshToken, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RefreshToken,
		&i.IsBlocked,
		&i.ClientIP,
		&i.UserAgent,
	)
	return i, err
}
