// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_delete_requests.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRequestCount = `-- name: DeleteRequestCount :one
SELECT
    COUNT(*)
FROM
    delete_requests
`

// ==========================================
// META
// ==========================================
func (q *Queries) DeleteRequestCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, deleteRequestCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRequestCreate = `-- name: DeleteRequestCreate :one
INSERT INTO delete_requests(user_id, scheduled_at)
    VALUES ($1, $2)
RETURNING
    user_id, created_at, scheduled_at
`

type DeleteRequestCreateParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) DeleteRequestCreate(ctx context.Context, arg DeleteRequestCreateParams) (DeleteRequest, error) {
	row := q.db.QueryRow(ctx, deleteRequestCreate, arg.UserID, arg.ScheduledAt)
	var i DeleteRequest
	err := row.Scan(&i.UserID, &i.CreatedAt, &i.ScheduledAt)
	return i, err
}

const deleteRequestDeleteByUserID = `-- name: DeleteRequestDeleteByUserID :exec
DELETE FROM delete_requests
WHERE user_id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) DeleteRequestDeleteByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequestDeleteByUserID, userID)
	return err
}

const deleteRequestGetByUserID = `-- name: DeleteRequestGetByUserID :one
SELECT
    user_id, created_at, scheduled_at
FROM
    delete_requests
WHERE
    user_id = $1
LIMIT 1
`

// ==========================================
// GET
// ==========================================
func (q *Queries) DeleteRequestGetByUserID(ctx context.Context, userID pgtype.UUID) (DeleteRequest, error) {
	row := q.db.QueryRow(ctx, deleteRequestGetByUserID, userID)
	var i DeleteRequest
	err := row.Scan(&i.UserID, &i.CreatedAt, &i.ScheduledAt)
	return i, err
}

const deleteRequestListDue = `-- name: DeleteRequestListDue :many
SELECT
    user_id, created_at, scheduled_at
FROM
    delete_requests
WHERE
    scheduled_at <= CURRENT_TIMESTAMP
ORDER BY
    scheduled_at ASC
`

// ==========================================
// LIST
// ==========================================
func (q *Queries) DeleteRequestListDue(ctx context.Context) ([]DeleteRequest, error) {
	rows, err := q.db.Query(ctx, deleteRequestListDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteRequest
	for rows.Next() {
		var i DeleteRequest
		if err := rows.Scan(&i.UserID, &i.CreatedAt, &i.ScheduledAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
