// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_messages.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages(channel_id, user_id, content)
    VALUES ($1, $2, $3)
RETURNING
    id, channel_id, user_id, content, created_at
`

type InsertMessageParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Content   string      `json:"content"`
}

// ==========================================
// CREATE
// ==========================================
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage, arg.ChannelID, arg.UserID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const messageDelete = `-- name: MessageDelete :exec
DELETE FROM messages
WHERE id = $1
`

// ==========================================
// DELETE
// ==========================================
func (q *Queries) MessageDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, messageDelete, id)
	return err
}

const messageGetByID = `-- name: MessageGetByID :one
SELECT
    id, channel_id, user_id, content, created_at
FROM
    messages
WHERE
    id = $1
LIMIT 1
`

// ==========================================
// GET
// ==========================================
func (q *Queries) MessageGetByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, messageGetByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const messageListByChannel = `-- name: MessageListByChannel :many
SELECT
    id, channel_id, user_id, content, created_at
FROM
    messages
WHERE
    channel_id = $1
ORDER BY
    created_at DESC
LIMIT $2 OFFSET $3
`

type MessageListByChannelParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

// ==========================================
// LIST
// ==========================================
func (q *Queries) MessageListByChannel(ctx context.Context, arg MessageListByChannelParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, messageListByChannel, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
