// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_chats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isUserInConversation = `-- name: IsUserInConversation :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            chat_members
        WHERE
            conversation_id = $1
            AND user_id = $2)
`

type IsUserInConversationParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// ==========================================
// CHAT MEMBERS
// ==========================================
func (q *Queries) IsUserInConversation(ctx context.Context, arg IsUserInConversationParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInConversation, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const messageCreate = `-- name: MessageCreate :one
INSERT INTO messages(conversation_id, author_id, content)
    VALUES ($1, $2, $3)
RETURNING
    id, conversation_id, author_id, content, created_at
`

type MessageCreateParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	AuthorID       pgtype.UUID `json:"author_id"`
	Content        string      `json:"content"`
}

// ==========================================
// MESSAGES
// ==========================================
func (q *Queries) MessageCreate(ctx context.Context, arg MessageCreateParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageCreate, arg.ConversationID, arg.AuthorID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const messageListByConversation = `-- name: MessageListByConversation :many
SELECT
    id, conversation_id, author_id, content, created_at
FROM
    messages
WHERE
    conversation_id = $1
ORDER BY
    created_at ASC
`

func (q *Queries) MessageListByConversation(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, messageListByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
