// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_relationships.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const relationshipDelete = `-- name: RelationshipDelete :exec
DELETE FROM relationships
WHERE user1_id = $1
    AND user2_id = $2
`

type RelationshipDeleteParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

// ==========================================
// DELETE
// ==========================================
func (q *Queries) RelationshipDelete(ctx context.Context, arg RelationshipDeleteParams) error {
	_, err := q.db.Exec(ctx, relationshipDelete, arg.User1ID, arg.User2ID)
	return err
}

const relationshipDeleteVerified = `-- name: RelationshipDeleteVerified :one
DELETE FROM relationships
WHERE user1_id = $1
    AND user2_id = $2
    AND (type != 2
        OR actor_id = $3)
RETURNING
    type
`

type RelationshipDeleteVerifiedParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
	ActorID pgtype.UUID `json:"actor_id"`
}

func (q *Queries) RelationshipDeleteVerified(ctx context.Context, arg RelationshipDeleteVerifiedParams) (int16, error) {
	row := q.db.QueryRow(ctx, relationshipDeleteVerified, arg.User1ID, arg.User2ID, arg.ActorID)
	var type_ int16
	err := row.Scan(&type_)
	return type_, err
}

const relationshipGet = `-- name: RelationshipGet :one
SELECT
    user1_id,
    user2_id,
    actor_id,
    type,
    created_at,
    updated_at
FROM
    relationships
WHERE
    user1_id = $1
    AND user2_id = $2
`

type RelationshipGetParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

// ==========================================
// GET
// ==========================================
func (q *Queries) RelationshipGet(ctx context.Context, arg RelationshipGetParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipGet, arg.User1ID, arg.User2ID)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const relationshipGetForUpdate = `-- name: RelationshipGetForUpdate :one
SELECT
    user1_id,
    user2_id,
    actor_id,
    type,
    created_at,
    updated_at
FROM
    relationships
WHERE
    user1_id = $1
    AND user2_id = $2
FOR UPDATE
`

type RelationshipGetForUpdateParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

func (q *Queries) RelationshipGetForUpdate(ctx context.Context, arg RelationshipGetForUpdateParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipGetForUpdate, arg.User1ID, arg.User2ID)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const relationshipUpsert = `-- name: RelationshipUpsert :one
INSERT INTO relationships(user1_id, user2_id, type, actor_id)
    VALUES ($1, $2, $3, $4)
ON CONFLICT (user1_id, user2_id)
    DO UPDATE SET type = EXCLUDED.type, actor_id = EXCLUDED.actor_id, updated_at = CURRENT_TIMESTAMP
RETURNING
    user1_id, user2_id, actor_id, type, created_at, updated_at
`

type RelationshipUpsertParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
	Type    int16       `json:"type"`
	ActorID pgtype.UUID `json:"actor_id"`
}

// ==========================================
// UPDATE
// ==========================================
func (q *Queries) RelationshipUpsert(ctx context.Context, arg RelationshipUpsertParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipUpsert,
		arg.User1ID,
		arg.User2ID,
		arg.Type,
		arg.ActorID,
	)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const relationshipsCount = `-- name: RelationshipsCount :one
SELECT
    COUNT(*)
FROM
    relationships
`

// ==========================================
// META
// ==========================================
func (q *Queries) RelationshipsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, relationshipsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const relationshipsListBlockedByUserID = `-- name: RelationshipsListBlockedByUserID :many
SELECT
    user_id, peer_id, type, actor_id, created_at, updated_at, username, display_name, avatar_url, user_status, channel_id
FROM
    relationship_perspectives
WHERE
    user_id = $1
    AND type = 2
    AND actor_id = $1
`

func (q *Queries) RelationshipsListBlockedByUserID(ctx context.Context, userID pgtype.UUID) ([]RelationshipPerspective, error) {
	rows, err := q.db.Query(ctx, relationshipsListBlockedByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelationshipPerspective
	for rows.Next() {
		var i RelationshipPerspective
		if err := rows.Scan(
			&i.UserID,
			&i.PeerID,
			&i.Type,
			&i.ActorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.UserStatus,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relationshipsListByUserID = `-- name: RelationshipsListByUserID :many
SELECT
    user_id, peer_id, type, actor_id, created_at, updated_at, username, display_name, avatar_url, user_status, channel_id
FROM
    relationship_perspectives
WHERE
    user_id = $1
    AND (type != 2
        OR actor_id = $1)
`

// ==========================================
// LIST
// ==========================================
func (q *Queries) RelationshipsListByUserID(ctx context.Context, userID pgtype.UUID) ([]RelationshipPerspective, error) {
	rows, err := q.db.Query(ctx, relationshipsListByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelationshipPerspective
	for rows.Next() {
		var i RelationshipPerspective
		if err := rows.Scan(
			&i.UserID,
			&i.PeerID,
			&i.Type,
			&i.ActorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.UserStatus,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relationshipsListFriendsByUserID = `-- name: RelationshipsListFriendsByUserID :many
SELECT
    user_id, peer_id, type, actor_id, created_at, updated_at, username, display_name, avatar_url, user_status, channel_id
FROM
    relationship_perspectives
WHERE
    user_id = $1
    AND type = 1
`

func (q *Queries) RelationshipsListFriendsByUserID(ctx context.Context, userID pgtype.UUID) ([]RelationshipPerspective, error) {
	rows, err := q.db.Query(ctx, relationshipsListFriendsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelationshipPerspective
	for rows.Next() {
		var i RelationshipPerspective
		if err := rows.Scan(
			&i.UserID,
			&i.PeerID,
			&i.Type,
			&i.ActorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.UserStatus,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relationshipsListPendingByUserID = `-- name: RelationshipsListPendingByUserID :many
SELECT
    user_id, peer_id, type, actor_id, created_at, updated_at, username, display_name, avatar_url, user_status, channel_id
FROM
    relationship_perspectives
WHERE
    user_id = $1
    AND type = 0
`

func (q *Queries) RelationshipsListPendingByUserID(ctx context.Context, userID pgtype.UUID) ([]RelationshipPerspective, error) {
	rows, err := q.db.Query(ctx, relationshipsListPendingByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelationshipPerspective
	for rows.Next() {
		var i RelationshipPerspective
		if err := rows.Scan(
			&i.UserID,
			&i.PeerID,
			&i.Type,
			&i.ActorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.UserStatus,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
