// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	OutboxEventAcquireBatch(ctx context.Context, arg OutboxEventAcquireBatchParams) ([]OutboxEvent, error)
	OutboxEventCreate(ctx context.Context, arg OutboxEventCreateParams) (OutboxEvent, error)
	OutboxEventDeleteByID(ctx context.Context, id pgtype.UUID) error
	OutboxEventGetByID(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	OutboxEventList(ctx context.Context, arg OutboxEventListParams) ([]OutboxEvent, error)
	OutboxEventMarkDeadLetter(ctx context.Context, arg OutboxEventMarkDeadLetterParams) (OutboxEvent, error)
	OutboxEventMarkProcessed(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	OutboxEventPurgeProcessed(ctx context.Context) error
	OutboxEventRecordFailure(ctx context.Context, arg OutboxEventRecordFailureParams) (OutboxEvent, error)
	OutboxEventResetAttempts(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	RelationshipDelete(ctx context.Context, arg RelationshipDeleteParams) error
	RelationshipDeleteVerified(ctx context.Context, arg RelationshipDeleteVerifiedParams) error
	// 3 = Blocked
	RelationshipGet(ctx context.Context, arg RelationshipGetParams) (Relationship, error)
	RelationshipGetForUpdate(ctx context.Context, arg RelationshipGetForUpdateParams) (Relationship, error)
	RelationshipUpsert(ctx context.Context, arg RelationshipUpsertParams) (Relationship, error)
	// 2 = Friends
	RelationshipsListBlockedByUserID(ctx context.Context, userID pgtype.UUID) ([]Relationship, error)
	RelationshipsListByUserID(ctx context.Context, userID pgtype.UUID) ([]Relationship, error)
	// 1 = Pending
	RelationshipsListFriendsByUserID(ctx context.Context, userID pgtype.UUID) ([]Relationship, error)
	RelationshipsListPendingByUserID(ctx context.Context, userID pgtype.UUID) ([]Relationship, error)
	SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error)
	SessionDelete(ctx context.Context, id pgtype.UUID) error
	SessionDeleteAllExcept(ctx context.Context, arg SessionDeleteAllExceptParams) error
	SessionDeleteAllExpired(ctx context.Context) error
	SessionDeleteByUserID(ctx context.Context, userID pgtype.UUID) error
	SessionGetByID(ctx context.Context, id pgtype.UUID) (Session, error)
	SessionUpdateLastSeen(ctx context.Context, id pgtype.UUID) (Session, error)
	SessionUpdateRefreshToken(ctx context.Context, arg SessionUpdateRefreshTokenParams) (Session, error)
	SessionUpdateRevoked(ctx context.Context, id pgtype.UUID) (Session, error)
	UserCheckAvailability(ctx context.Context, arg UserCheckAvailabilityParams) (UserCheckAvailabilityRow, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (User, error)
	UserGetByEmail(ctx context.Context, email string) (User, error)
	UserGetByID(ctx context.Context, id pgtype.UUID) (User, error)
	UserGetByUsername(ctx context.Context, username string) (User, error)
	UserMarkVerified(ctx context.Context, id pgtype.UUID) (User, error)
	UserProfileCreate(ctx context.Context, arg UserProfileCreateParams) (UserProfile, error)
	UserProfileGetByUserID(ctx context.Context, userID pgtype.UUID) (UserProfile, error)
	UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
