// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userCheckAvailability = `-- name: UserCheckAvailability :one
SELECT
    NOT EXISTS (
        SELECT
            1
        FROM
            users u
        WHERE
            u.email = $1) AS email_available,
    NOT EXISTS (
        SELECT
            1
        FROM
            users u
        WHERE
            u.username = $2) AS username_available
`

type UserCheckAvailabilityParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type UserCheckAvailabilityRow struct {
	EmailAvailable    bool `json:"email_available"`
	UsernameAvailable bool `json:"username_available"`
}

func (q *Queries) UserCheckAvailability(ctx context.Context, arg UserCheckAvailabilityParams) (UserCheckAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, userCheckAvailability, arg.Email, arg.Username)
	var i UserCheckAvailabilityRow
	err := row.Scan(&i.EmailAvailable, &i.UsernameAvailable)
	return i, err
}

const userCreate = `-- name: UserCreate :one
INSERT INTO users(email, username, password_hash)
    VALUES ($1, $2, $3)
RETURNING
    id, created_at, updated_at, email, username, password_hash, is_totp_enabled, totp_secret, verified_at, last_verification_sent_at, role
`

type UserCreateParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.Email, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.VerifiedAt,
		&i.LastVerificationSentAt,
		&i.Role,
	)
	return i, err
}

const userDelete = `-- name: UserDelete :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) UserDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userDelete, id)
	return err
}

const userDeleteByEmail = `-- name: UserDeleteByEmail :one
DELETE FROM users
WHERE email = $1
RETURNING
    id, created_at, updated_at, email, username, password_hash, is_totp_enabled, totp_secret, verified_at, last_verification_sent_at, role
`

func (q *Queries) UserDeleteByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userDeleteByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.VerifiedAt,
		&i.LastVerificationSentAt,
		&i.Role,
	)
	return i, err
}

const userDisableTOTP = `-- name: UserDisableTOTP :exec
UPDATE
    users
SET
    totp_secret = NULL,
    is_totp_enabled = FALSE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) UserDisableTOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userDisableTOTP, id)
	return err
}

const userEnableTOTP = `-- name: UserEnableTOTP :exec
UPDATE
    users
SET
    totp_secret = $1,
    is_totp_enabled = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $2
`

type UserEnableTOTPParams struct {
	TotpSecret pgtype.Text `json:"totp_secret"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UserEnableTOTP(ctx context.Context, arg UserEnableTOTPParams) error {
	_, err := q.db.Exec(ctx, userEnableTOTP, arg.TotpSecret, arg.ID)
	return err
}

const userGetAuthCredentials = `-- name: UserGetAuthCredentials :one
SELECT
    id,
    password_hash,
    is_totp_enabled,
    verified_at,
    role

FROM
    users
WHERE
    email = $1
LIMIT 1
`

type UserGetAuthCredentialsRow struct {
	ID            pgtype.UUID        `json:"id"`
	PasswordHash  string             `json:"password_hash"`
	IsTotpEnabled bool               `json:"is_totp_enabled"`
	VerifiedAt    pgtype.Timestamptz `json:"verified_at"`
	Role          UserRole           `json:"role"`
}

func (q *Queries) UserGetAuthCredentials(ctx context.Context, email string) (UserGetAuthCredentialsRow, error) {
	row := q.db.QueryRow(ctx, userGetAuthCredentials, email)
	var i UserGetAuthCredentialsRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.IsTotpEnabled,
		&i.VerifiedAt,
		&i.Role,
	)
	return i, err
}

const userGetByEmail = `-- name: UserGetByEmail :one
SELECT
    id, created_at, updated_at, email, username, password_hash, is_totp_enabled, totp_secret, verified_at, last_verification_sent_at, role
FROM
    users
WHERE
    email = $1
LIMIT 1
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.VerifiedAt,
		&i.LastVerificationSentAt,
		&i.Role,
	)
	return i, err
}

const userGetByID = `-- name: UserGetByID :one
SELECT
    id, created_at, updated_at, email, username, password_hash, is_totp_enabled, totp_secret, verified_at, last_verification_sent_at, role
FROM
    users
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) UserGetByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userGetByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.VerifiedAt,
		&i.LastVerificationSentAt,
		&i.Role,
	)
	return i, err
}

const userGetByUsername = `-- name: UserGetByUsername :one
SELECT
    id, created_at, updated_at, email, username, password_hash, is_totp_enabled, totp_secret, verified_at, last_verification_sent_at, role
FROM
    users
WHERE
    username = $1
LIMIT 1
`

func (q *Queries) UserGetByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.IsTotpEnabled,
		&i.TotpSecret,
		&i.VerifiedAt,
		&i.LastVerificationSentAt,
		&i.Role,
	)
	return i, err
}

const userGetTOTPSecret = `-- name: UserGetTOTPSecret :one
SELECT
    totp_secret
FROM
    users
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) UserGetTOTPSecret(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, userGetTOTPSecret, id)
	var totp_secret pgtype.Text
	err := row.Scan(&totp_secret)
	return totp_secret, err
}

const userListUnverified = `-- name: UserListUnverified :many
SELECT
    id,
    email,
    username,
    created_at
FROM
    users
WHERE
    verified_at IS NULL
ORDER BY
    created_at ASC
`

type UserListUnverifiedRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UserListUnverified(ctx context.Context) ([]UserListUnverifiedRow, error) {
	rows, err := q.db.Query(ctx, userListUnverified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserListUnverifiedRow
	for rows.Next() {
		var i UserListUnverifiedRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userMarkVerified = `-- name: UserMarkVerified :exec
UPDATE
    users
SET
    verified_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
    AND verified_at IS NULL
`

func (q *Queries) UserMarkVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userMarkVerified, id)
	return err
}

const userUpdateLastVerificationSent = `-- name: UserUpdateLastVerificationSent :exec
UPDATE
    users
SET
    last_verification_sent_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

func (q *Queries) UserUpdateLastVerificationSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userUpdateLastVerificationSent, id)
	return err
}

const userUpdatePassword = `-- name: UserUpdatePassword :exec
UPDATE
    users
SET
    password_hash = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1
`

type UserUpdatePasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, userUpdatePassword, arg.ID, arg.PasswordHash)
	return err
}
