// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Uses a CTE to lock rows and immediately push next_attempt_at into the future.
	// This creates a "visibility timeout" so if the worker crashes, the events will naturally retry.
	OutboxEventAcquireBatch(ctx context.Context, limit int32) ([]OutboxEvent, error)
	// ==========================================
	// META
	// ==========================================
	OutboxEventCount(ctx context.Context) (int64, error)
	// ==========================================
	// CREATE
	// ==========================================
	OutboxEventCreate(ctx context.Context, arg OutboxEventCreateParams) (OutboxEvent, error)
	// ==========================================
	// DELETE
	// ==========================================
	OutboxEventDeleteByID(ctx context.Context, id pgtype.UUID) error
	// ==========================================
	// GET
	// ==========================================
	OutboxEventGetByID(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	// ==========================================
	// LIST
	// ==========================================
	OutboxEventList(ctx context.Context, arg OutboxEventListParams) ([]OutboxEvent, error)
	// Permanently ignores an event that cannot be processed.
	OutboxEventMarkDeadLetter(ctx context.Context, arg OutboxEventMarkDeadLetterParams) (OutboxEvent, error)
	// ==========================================
	// UPDATE
	// ==========================================
	OutboxEventMarkProcessed(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	OutboxEventPurgeProcessed(ctx context.Context) error
	OutboxEventRecordFailure(ctx context.Context, arg OutboxEventRecordFailureParams) (OutboxEvent, error)
	OutboxEventResetAttempts(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	UserCheckAvailability(ctx context.Context, arg UserCheckAvailabilityParams) (UserCheckAvailabilityRow, error)
	// ==========================================
	// META
	// ==========================================
	UserCount(ctx context.Context) (int64, error)
	// ==========================================
	// CREATE
	// ==========================================
	UserCreate(ctx context.Context, arg UserCreateParams) (User, error)
	UserDeleteByEmail(ctx context.Context, email string) error
	// ==========================================
	// DELETE
	// ==========================================
	UserDeleteByID(ctx context.Context, id pgtype.UUID) error
	UserDeleteRequestCreate(ctx context.Context, arg UserDeleteRequestCreateParams) (UserDeleteRequest, error)
	UserDeleteRequestDelete(ctx context.Context, userID pgtype.UUID) error
	UserDeleteRequestGet(ctx context.Context, userID pgtype.UUID) (UserDeleteRequest, error)
	UserDeleteRequestListDue(ctx context.Context) ([]pgtype.UUID, error)
	UserDisableTOTP(ctx context.Context, id pgtype.UUID) (User, error)
	UserEnableTOTP(ctx context.Context, arg UserEnableTOTPParams) (User, error)
	UserGetByEmail(ctx context.Context, email string) (User, error)
	// ==========================================
	// GET
	// ==========================================
	UserGetByID(ctx context.Context, id pgtype.UUID) (User, error)
	UserGetByUsername(ctx context.Context, username string) (User, error)
	// ==========================================
	// LIST
	// ==========================================
	UserList(ctx context.Context, arg UserListParams) ([]User, error)
	UserListUnverified(ctx context.Context, limit int32) ([]User, error)
	// ==========================================
	// UPDATE
	// ==========================================
	UserMarkVerified(ctx context.Context, id pgtype.UUID) (User, error)
	UserProfileCheckDisplayNameAvailability(ctx context.Context, lower string) (bool, error)
	UserProfileCreate(ctx context.Context, arg UserProfileCreateParams) (UserProfile, error)
	UserProfileDelete(ctx context.Context, userID pgtype.UUID) error
	UserProfileGet(ctx context.Context, userID pgtype.UUID) (UserProfile, error)
	UserProfileGetByDisplayName(ctx context.Context, lower string) (UserProfile, error)
	UserProfileUpdateDisplayName(ctx context.Context, arg UserProfileUpdateDisplayNameParams) error
	UserSessionCreate(ctx context.Context, arg UserSessionCreateParams) (UserSession, error)
	UserSessionDelete(ctx context.Context, arg UserSessionDeleteParams) error
	UserSessionDeleteAllExcept(ctx context.Context, arg UserSessionDeleteAllExceptParams) error
	UserSessionGet(ctx context.Context, refreshToken string) (UserSession, error)
	UserSessionGetByID(ctx context.Context, id pgtype.UUID) (UserSession, error)
	UserSessionListByUser(ctx context.Context, userID pgtype.UUID) ([]UserSession, error)
	UserSessionMarkBlocked(ctx context.Context, id pgtype.UUID) error
	UserSessionUpdateLastSeen(ctx context.Context, id pgtype.UUID) error
	UserSessionUpdateRefreshToken(ctx context.Context, arg UserSessionUpdateRefreshTokenParams) error
	UserUpdateLastVerificationSent(ctx context.Context, id pgtype.UUID) (User, error)
	UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
