// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_user_delete_requests.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userDeleteRequestCreate = `-- name: UserDeleteRequestCreate :one
INSERT INTO user_delete_requests(user_id, scheduled_at)
    VALUES ($1, $2)
RETURNING
    user_id, created_at, scheduled_at
`

type UserDeleteRequestCreateParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) UserDeleteRequestCreate(ctx context.Context, arg UserDeleteRequestCreateParams) (UserDeleteRequest, error) {
	row := q.db.QueryRow(ctx, userDeleteRequestCreate, arg.UserID, arg.ScheduledAt)
	var i UserDeleteRequest
	err := row.Scan(&i.UserID, &i.CreatedAt, &i.ScheduledAt)
	return i, err
}

const userDeleteRequestDelete = `-- name: UserDeleteRequestDelete :exec
DELETE FROM user_delete_requests
WHERE user_id = $1
`

func (q *Queries) UserDeleteRequestDelete(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, userDeleteRequestDelete, userID)
	return err
}

const userDeleteRequestGet = `-- name: UserDeleteRequestGet :one
SELECT
    user_id, created_at, scheduled_at
FROM
    user_delete_requests
WHERE
    user_id = $1
LIMIT 1
`

func (q *Queries) UserDeleteRequestGet(ctx context.Context, userID pgtype.UUID) (UserDeleteRequest, error) {
	row := q.db.QueryRow(ctx, userDeleteRequestGet, userID)
	var i UserDeleteRequest
	err := row.Scan(&i.UserID, &i.CreatedAt, &i.ScheduledAt)
	return i, err
}

const userDeleteRequestListDue = `-- name: UserDeleteRequestListDue :many
SELECT
    user_id
FROM
    user_delete_requests
WHERE
    scheduled_at <= CURRENT_TIMESTAMP
ORDER BY
    scheduled_at ASC
`

func (q *Queries) UserDeleteRequestListDue(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, userDeleteRequestListDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
