// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachmentCreateBatch = `-- name: AttachmentCreateBatch :many
INSERT INTO message_attachments(id, message_id, created_at, file_size, width, height, file_name, content_type, url)
SELECT
    id,
    message_id,
    created_at,
    file_size,
    width,
    height,
    file_name,
    content_type,
    url
FROM
    jsonb_to_recordset($1::jsonb) AS x(id uuid,
        message_id uuid,
        created_at timestamptz,
        file_size bigint,
        width integer,
        height integer,
        file_name text,
        content_type text,
        url text)
RETURNING
    id, message_id, file_name, content_type, url, file_size, width, height, created_at
`

func (q *Queries) AttachmentCreateBatch(ctx context.Context, payload []byte) ([]MessageAttachment, error) {
	rows, err := q.db.Query(ctx, attachmentCreateBatch, payload)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAttachment
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.ContentType,
			&i.URL,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attachmentDelete = `-- name: AttachmentDelete :exec
DELETE FROM message_attachments
WHERE id = $1::uuid
`

func (q *Queries) AttachmentDelete(ctx context.Context, attachmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, attachmentDelete, attachmentID)
	return err
}

const attachmentGetBatchByMessageIDs = `-- name: AttachmentGetBatchByMessageIDs :many
SELECT
    id, message_id, file_name, content_type, url, file_size, width, height, created_at
FROM
    message_attachments
WHERE
    message_id = ANY ($1::uuid[])
ORDER BY
    message_id,
    id ASC
`

func (q *Queries) AttachmentGetBatchByMessageIDs(ctx context.Context, messageIds []pgtype.UUID) ([]MessageAttachment, error) {
	rows, err := q.db.Query(ctx, attachmentGetBatchByMessageIDs, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAttachment
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.ContentType,
			&i.URL,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
