// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachmentCreateBatch = `-- name: AttachmentCreateBatch :exec
WITH input_data AS (
    SELECT
        jsonb_populate_recordset
    FROM
        jsonb_populate_recordset(NULL::message_attachments, $2::jsonb))
INSERT INTO message_attachments(id, message_id, file_name, file_size, content_type, url, width, height, created_at)
SELECT
    id,
    COALESCE(message_id, $1::uuid),
    file_name,
    file_size,
    content_type,
    url,
    width,
    height,
    created_at
FROM
    input_data
`

type AttachmentCreateBatchParams struct {
	MessageID       pgtype.UUID `json:"message_id"`
	AttachmentsJson []byte      `json:"attachments_json"`
}

func (q *Queries) AttachmentCreateBatch(ctx context.Context, arg AttachmentCreateBatchParams) error {
	_, err := q.db.Exec(ctx, attachmentCreateBatch, arg.MessageID, arg.AttachmentsJson)
	return err
}

const attachmentDelete = `-- name: AttachmentDelete :exec
DELETE FROM message_attachments
WHERE id = $1::uuid
`

func (q *Queries) AttachmentDelete(ctx context.Context, attachmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, attachmentDelete, attachmentID)
	return err
}
