// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelCreate = `-- name: ChannelCreate :one
INSERT INTO channels(id, created_at, updated_at, type, name, icon_url)
    VALUES ($1::uuid, $2::timestamptz, $3::timestamptz, $4::smallint, $5::text, $6::text)
RETURNING
    channels.id, channels.last_message_id, channels.created_at, channels.updated_at, channels.last_message_at, channels.type, channels.name, channels.icon_url
`

type ChannelCreateParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Type      int16              `json:"type"`
	Name      pgtype.Text        `json:"name"`
	IconURL   pgtype.Text        `json:"icon_url"`
}

func (q *Queries) ChannelCreate(ctx context.Context, arg ChannelCreateParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelCreate,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Type,
		arg.Name,
		arg.IconURL,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
		&i.Type,
		&i.Name,
		&i.IconURL,
	)
	return i, err
}

const channelDelete = `-- name: ChannelDelete :exec
DELETE FROM channels
WHERE id = $1::uuid
`

func (q *Queries) ChannelDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, channelDelete, id)
	return err
}

const channelGet = `-- name: ChannelGet :one
SELECT
    channels.id, channels.last_message_id, channels.created_at, channels.updated_at, channels.last_message_at, channels.type, channels.name, channels.icon_url
FROM
    channels
WHERE
    id = $1::uuid
`

func (q *Queries) ChannelGet(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, channelGet, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
		&i.Type,
		&i.Name,
		&i.IconURL,
	)
	return i, err
}

const channelGetBatch = `-- name: ChannelGetBatch :many
SELECT
    channels.id, channels.last_message_id, channels.created_at, channels.updated_at, channels.last_message_at, channels.type, channels.name, channels.icon_url
FROM
    channels
WHERE
    id = ANY ($1::uuid[])
ORDER BY
    id ASC
`

func (q *Queries) ChannelGetBatch(ctx context.Context, ids []pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, channelGetBatch, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.LastMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessageAt,
			&i.Type,
			&i.Name,
			&i.IconURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelGetForUpdate = `-- name: ChannelGetForUpdate :one
SELECT
    channels.id, channels.last_message_id, channels.created_at, channels.updated_at, channels.last_message_at, channels.type, channels.name, channels.icon_url
FROM
    channels
WHERE
    id = $1::uuid
FOR UPDATE
`

func (q *Queries) ChannelGetForUpdate(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, channelGetForUpdate, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
		&i.Type,
		&i.Name,
		&i.IconURL,
	)
	return i, err
}

const channelUpdateGroup = `-- name: ChannelUpdateGroup :one
UPDATE
    channels
SET
    name = $1::text,
    icon_url = $2::text,
    updated_at = $3::timestamptz
WHERE
    id = $4::uuid
    AND type = 2
RETURNING
    channels.id, channels.last_message_id, channels.created_at, channels.updated_at, channels.last_message_at, channels.type, channels.name, channels.icon_url
`

type ChannelUpdateGroupParams struct {
	Name      pgtype.Text        `json:"name"`
	IconURL   pgtype.Text        `json:"icon_url"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) ChannelUpdateGroup(ctx context.Context, arg ChannelUpdateGroupParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelUpdateGroup,
		arg.Name,
		arg.IconURL,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
		&i.Type,
		&i.Name,
		&i.IconURL,
	)
	return i, err
}

const channelUpdateLastMessage = `-- name: ChannelUpdateLastMessage :one
UPDATE
    channels
SET
    last_message_id = $1::uuid,
    last_message_at = $2::timestamptz,
    updated_at = $3::timestamptz
WHERE
    id = $4::uuid
RETURNING
    channels.id, channels.last_message_id, channels.created_at, channels.updated_at, channels.last_message_at, channels.type, channels.name, channels.icon_url
`

type ChannelUpdateLastMessageParams struct {
	LastMessageID pgtype.UUID        `json:"last_message_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) ChannelUpdateLastMessage(ctx context.Context, arg ChannelUpdateLastMessageParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelUpdateLastMessage,
		arg.LastMessageID,
		arg.LastMessageAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
		&i.Type,
		&i.Name,
		&i.IconURL,
	)
	return i, err
}
