// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelMemberAddBatch = `-- name: ChannelMemberAddBatch :exec
WITH input_data AS (
    SELECT
        jsonb_populate_recordset
    FROM
        jsonb_populate_recordset(NULL::channel_members, $1::jsonb))
INSERT INTO channel_members(channel_id, user_id, created_at, updated_at, last_read_at, mention_count, last_read_message_id, is_visible, pinned_at)
SELECT
    channel_id,
    user_id,
    created_at,
    updated_at,
    last_read_at,
    mention_count,
    last_read_message_id,
    is_visible,
    pinned_at
FROM
    input_data
ON CONFLICT (channel_id,
    user_id)
    DO UPDATE SET
        updated_at = EXCLUDED.updated_at,
        last_read_at = EXCLUDED.last_read_at,
        mention_count = EXCLUDED.mention_count,
        last_read_message_id = EXCLUDED.last_read_message_id,
        is_visible = EXCLUDED.is_visible,
        pinned_at = EXCLUDED.pinned_at
`

func (q *Queries) ChannelMemberAddBatch(ctx context.Context, membersJson []byte) error {
	_, err := q.db.Exec(ctx, channelMemberAddBatch, membersJson)
	return err
}

const channelMemberCloseDM = `-- name: ChannelMemberCloseDM :exec
UPDATE
    channel_members
SET
    is_visible = FALSE,
    updated_at = $1::timestamptz
WHERE
    channel_id = $2::uuid
    AND user_id = $3::uuid
`

type ChannelMemberCloseDMParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ChannelMemberCloseDM(ctx context.Context, arg ChannelMemberCloseDMParams) error {
	_, err := q.db.Exec(ctx, channelMemberCloseDM, arg.UpdatedAt, arg.ChannelID, arg.UserID)
	return err
}

const channelMemberOpenDM = `-- name: ChannelMemberOpenDM :exec
UPDATE
    channel_members
SET
    is_visible = TRUE,
    updated_at = $1::timestamptz
WHERE
    channel_id = $2::uuid
    AND user_id = $3::uuid
`

type ChannelMemberOpenDMParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ChannelMemberOpenDM(ctx context.Context, arg ChannelMemberOpenDMParams) error {
	_, err := q.db.Exec(ctx, channelMemberOpenDM, arg.UpdatedAt, arg.ChannelID, arg.UserID)
	return err
}

const channelMemberTogglePinned = `-- name: ChannelMemberTogglePinned :exec
UPDATE
    channel_members
SET
    pinned_at = CASE WHEN pinned_at IS NULL THEN
        $1::timestamptz
    ELSE
        NULL
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE
    channel_id = $2::uuid
    AND user_id = $3::uuid
`

type ChannelMemberTogglePinnedParams struct {
	PinnedAt  pgtype.Timestamptz `json:"pinned_at"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ChannelMemberTogglePinned(ctx context.Context, arg ChannelMemberTogglePinnedParams) error {
	_, err := q.db.Exec(ctx, channelMemberTogglePinned, arg.PinnedAt, arg.ChannelID, arg.UserID)
	return err
}

const channelMemberUpdateLastRead = `-- name: ChannelMemberUpdateLastRead :exec
UPDATE
    channel_members
SET
    last_read_message_id = CASE WHEN $1::timestamptz > last_read_at THEN
        COALESCE($2::uuid, last_read_message_id)
    ELSE
        last_read_message_id
    END,
    last_read_at = GREATEST(last_read_at, $1::timestamptz),
    updated_at = CURRENT_TIMESTAMP
WHERE
    channel_id = $3::uuid
    AND user_id = $4::uuid
`

type ChannelMemberUpdateLastReadParams struct {
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
	LastReadMessageID pgtype.UUID        `json:"last_read_message_id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	UserID            pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ChannelMemberUpdateLastRead(ctx context.Context, arg ChannelMemberUpdateLastReadParams) error {
	_, err := q.db.Exec(ctx, channelMemberUpdateLastRead,
		arg.LastReadAt,
		arg.LastReadMessageID,
		arg.ChannelID,
		arg.UserID,
	)
	return err
}
