// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const messageCreate = `-- name: MessageCreate :one
INSERT INTO messages(id, channel_id, author_id, reply_to_message_id, forwarded_message_id, forwarded_channel_id, created_at, updated_at, edited_at, pinned_at, type, content, system_metadata)
    VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5::uuid, $6::uuid, $7::timestamptz, $8::timestamptz, $9::timestamptz, $10::timestamptz, $11::smallint, $12::text, $13::jsonb)
RETURNING
    id, channel_id, author_id, reply_to_message_id, forwarded_message_id, forwarded_channel_id, created_at, updated_at, edited_at, pinned_at, type, content, system_metadata
`

type MessageCreateParams struct {
	ID                 pgtype.UUID        `json:"id"`
	ChannelID          pgtype.UUID        `json:"channel_id"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	ReplyToMessageID   pgtype.UUID        `json:"reply_to_message_id"`
	ForwardedMessageID pgtype.UUID        `json:"forwarded_message_id"`
	ForwardedChannelID pgtype.UUID        `json:"forwarded_channel_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	EditedAt           pgtype.Timestamptz `json:"edited_at"`
	PinnedAt           pgtype.Timestamptz `json:"pinned_at"`
	Type               int16              `json:"type"`
	Content            pgtype.Text        `json:"content"`
	SystemMetadata     []byte             `json:"system_metadata"`
}

func (q *Queries) MessageCreate(ctx context.Context, arg MessageCreateParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageCreate,
		arg.ID,
		arg.ChannelID,
		arg.AuthorID,
		arg.ReplyToMessageID,
		arg.ForwardedMessageID,
		arg.ForwardedChannelID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EditedAt,
		arg.PinnedAt,
		arg.Type,
		arg.Content,
		arg.SystemMetadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ReplyToMessageID,
		&i.ForwardedMessageID,
		&i.ForwardedChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.PinnedAt,
		&i.Type,
		&i.Content,
		&i.SystemMetadata,
	)
	return i, err
}

const messageDelete = `-- name: MessageDelete :exec
DELETE FROM messages
WHERE id = $1::uuid
`

func (q *Queries) MessageDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, messageDelete, id)
	return err
}

const messageGet = `-- name: MessageGet :one
SELECT
    id,
    channel_id,
    author_id,
    reply_to_message_id,
    forwarded_message_id,
    forwarded_channel_id,
    created_at,
    updated_at,
    edited_at,
    pinned_at,
    type,
    content,
    system_metadata
FROM
    messages
WHERE
    id = $1::uuid
`

func (q *Queries) MessageGet(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, messageGet, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ReplyToMessageID,
		&i.ForwardedMessageID,
		&i.ForwardedChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.PinnedAt,
		&i.Type,
		&i.Content,
		&i.SystemMetadata,
	)
	return i, err
}

const messageListByChannel = `-- name: MessageListByChannel :many
SELECT
    id,
    channel_id,
    author_id,
    reply_to_message_id,
    forwarded_message_id,
    forwarded_channel_id,
    created_at,
    updated_at,
    edited_at,
    pinned_at,
    type,
    content,
    system_metadata
FROM
    messages
WHERE
    channel_id = $1::uuid
    AND (created_at,
        id) <($2::timestamptz,
        $3::uuid)
ORDER BY
    created_at DESC,
    id DESC
LIMIT $4::int
`

type MessageListByChannelParams struct {
	ChannelID       pgtype.UUID        `json:"channel_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
	BatchLimit      int32              `json:"batch_limit"`
}

func (q *Queries) MessageListByChannel(ctx context.Context, arg MessageListByChannelParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, messageListByChannel,
		arg.ChannelID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.BatchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.ReplyToMessageID,
			&i.ForwardedMessageID,
			&i.ForwardedChannelID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.PinnedAt,
			&i.Type,
			&i.Content,
			&i.SystemMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageListPinned = `-- name: MessageListPinned :many
SELECT
    id,
    channel_id,
    author_id,
    reply_to_message_id,
    forwarded_message_id,
    forwarded_channel_id,
    created_at,
    updated_at,
    edited_at,
    pinned_at,
    type,
    content,
    system_metadata
FROM
    messages
WHERE
    channel_id = $1::uuid
    AND pinned_at IS NOT NULL
ORDER BY
    pinned_at DESC
`

func (q *Queries) MessageListPinned(ctx context.Context, channelID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, messageListPinned, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.ReplyToMessageID,
			&i.ForwardedMessageID,
			&i.ForwardedChannelID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.PinnedAt,
			&i.Type,
			&i.Content,
			&i.SystemMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageTogglePin = `-- name: MessageTogglePin :one
UPDATE
    messages
SET
    pinned_at = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
    AND channel_id = $4::uuid
RETURNING
    id,
    channel_id,
    pinned_at,
    updated_at
`

type MessageTogglePinParams struct {
	PinnedAt  pgtype.Timestamptz `json:"pinned_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
}

type MessageTogglePinRow struct {
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	PinnedAt  pgtype.Timestamptz `json:"pinned_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MessageTogglePin(ctx context.Context, arg MessageTogglePinParams) (MessageTogglePinRow, error) {
	row := q.db.QueryRow(ctx, messageTogglePin,
		arg.PinnedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.ChannelID,
	)
	var i MessageTogglePinRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.PinnedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const messageUpdateContent = `-- name: MessageUpdateContent :one
UPDATE
    messages
SET
    content = COALESCE($1::text, content),
    updated_at = $2::timestamptz,
    edited_at = $3::timestamptz
WHERE
    id = $4::uuid
    AND author_id = $5::uuid
RETURNING
    id,
    channel_id,
    author_id,
    reply_to_message_id,
    forwarded_message_id,
    forwarded_channel_id,
    created_at,
    updated_at,
    edited_at,
    pinned_at,
    type,
    content,
    system_metadata
`

type MessageUpdateContentParams struct {
	Content   pgtype.Text        `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	ID        pgtype.UUID        `json:"id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
}

func (q *Queries) MessageUpdateContent(ctx context.Context, arg MessageUpdateContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageUpdateContent,
		arg.Content,
		arg.UpdatedAt,
		arg.EditedAt,
		arg.ID,
		arg.AuthorID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ReplyToMessageID,
		&i.ForwardedMessageID,
		&i.ForwardedChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.PinnedAt,
		&i.Type,
		&i.Content,
		&i.SystemMetadata,
	)
	return i, err
}
