// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const outboxEventClaimPending = `-- name: OutboxEventClaimPending :many
WITH target_events AS (
    SELECT
        id
    FROM
        outbox_events
    WHERE
        processed_at IS NULL
        AND attempts < max_attempts
        AND next_attempt_at <= $3::timestamptz
        AND (lease_expires_at IS NULL
            OR lease_expires_at < $3::timestamptz)
    ORDER BY
        next_attempt_at ASC,
        id ASC
    LIMIT $4::int
    FOR UPDATE
        SKIP LOCKED)
UPDATE
    outbox_events o
SET
    locked_by = $1::uuid,
    lease_expires_at = $2::timestamptz,
    updated_at = $3::timestamptz
FROM
    target_events t
WHERE
    o.id = t.id
RETURNING
    o.id, o.aggregate_id, o.locked_by, o.created_at, o.updated_at, o.next_attempt_at, o.lease_expires_at, o.processed_at, o.attempts, o.max_attempts, o.event_type, o.aggregate_type, o.trace_id, o.payload, o.last_error
`

type OutboxEventClaimPendingParams struct {
	WorkerID       pgtype.UUID        `json:"worker_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	Now            pgtype.Timestamptz `json:"now"`
	LimitVal       int32              `json:"limit_val"`
}

func (q *Queries) OutboxEventClaimPending(ctx context.Context, arg OutboxEventClaimPendingParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, outboxEventClaimPending,
		arg.WorkerID,
		arg.LeaseExpiresAt,
		arg.Now,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.LockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
			&i.LeaseExpiresAt,
			&i.ProcessedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.EventType,
			&i.AggregateType,
			&i.TraceID,
			&i.Payload,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxEventCreate = `-- name: OutboxEventCreate :exec
INSERT INTO outbox_events(id, aggregate_id, aggregate_type, event_type, payload, trace_id, created_at, updated_at, next_attempt_at, attempts, max_attempts)
    VALUES ($1::uuid, $2::uuid, $3::text, $4::text, $5::jsonb, $6::text, $7::timestamptz, $8::timestamptz, $9::timestamptz, $10::int, $11::int)
`

type OutboxEventCreateParams struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType pgtype.Text        `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	TraceID       pgtype.Text        `json:"trace_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
}

func (q *Queries) OutboxEventCreate(ctx context.Context, arg OutboxEventCreateParams) error {
	_, err := q.db.Exec(ctx, outboxEventCreate,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.TraceID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.NextAttemptAt,
		arg.Attempts,
		arg.MaxAttempts,
	)
	return err
}

type OutboxEventCreateBatchParams struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType pgtype.Text        `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	TraceID       pgtype.Text        `json:"trace_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
}

const outboxEventDeleteProcessedBatch = `-- name: OutboxEventDeleteProcessedBatch :execrows
WITH targets AS (
    SELECT
        id
    FROM
        outbox_events
    WHERE
        processed_at IS NOT NULL
        AND processed_at < $1::timestamptz
    ORDER BY
        processed_at ASC,
        id ASC
    LIMIT $2::int
    FOR UPDATE
        SKIP LOCKED)
DELETE FROM outbox_events o USING targets t
WHERE o.id = t.id
`

type OutboxEventDeleteProcessedBatchParams struct {
	Before   pgtype.Timestamptz `json:"before"`
	LimitVal int32              `json:"limit_val"`
}

func (q *Queries) OutboxEventDeleteProcessedBatch(ctx context.Context, arg OutboxEventDeleteProcessedBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, outboxEventDeleteProcessedBatch, arg.Before, arg.LimitVal)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const outboxEventMarkDeadLetter = `-- name: OutboxEventMarkDeadLetter :exec
UPDATE
    outbox_events
SET
    attempts = max_attempts,
    last_error = $1::text,
    locked_by = NULL,
    lease_expires_at = NULL,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
    AND locked_by = $4::uuid
    AND processed_at IS NULL
`

type OutboxEventMarkDeadLetterParams struct {
	LastError pgtype.Text        `json:"last_error"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
	WorkerID  pgtype.UUID        `json:"worker_id"`
}

func (q *Queries) OutboxEventMarkDeadLetter(ctx context.Context, arg OutboxEventMarkDeadLetterParams) error {
	_, err := q.db.Exec(ctx, outboxEventMarkDeadLetter,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkerID,
	)
	return err
}

const outboxEventMarkFailure = `-- name: OutboxEventMarkFailure :exec
UPDATE
    outbox_events
SET
    attempts = attempts + 1,
    next_attempt_at = $1::timestamptz,
    last_error = $2::text,
    locked_by = NULL,
    lease_expires_at = NULL,
    updated_at = $3::timestamptz
WHERE
    id = $4::uuid
    AND locked_by = $5::uuid
    AND processed_at IS NULL
`

type OutboxEventMarkFailureParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ID            pgtype.UUID        `json:"id"`
	WorkerID      pgtype.UUID        `json:"worker_id"`
}

func (q *Queries) OutboxEventMarkFailure(ctx context.Context, arg OutboxEventMarkFailureParams) error {
	_, err := q.db.Exec(ctx, outboxEventMarkFailure,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkerID,
	)
	return err
}

const outboxEventMarkProcessed = `-- name: OutboxEventMarkProcessed :exec
UPDATE
    outbox_events
SET
    processed_at = $1::timestamptz,
    locked_by = NULL,
    lease_expires_at = NULL,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
    AND locked_by = $4::uuid
    AND processed_at IS NULL
`

type OutboxEventMarkProcessedParams struct {
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          pgtype.UUID        `json:"id"`
	WorkerID    pgtype.UUID        `json:"worker_id"`
}

func (q *Queries) OutboxEventMarkProcessed(ctx context.Context, arg OutboxEventMarkProcessedParams) error {
	_, err := q.db.Exec(ctx, outboxEventMarkProcessed,
		arg.ProcessedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkerID,
	)
	return err
}

const outboxEventReleaseLease = `-- name: OutboxEventReleaseLease :exec
UPDATE
    outbox_events
SET
    locked_by = NULL,
    lease_expires_at = NULL,
    updated_at = $1::timestamptz
WHERE
    id = $2::uuid
    AND locked_by = $3::uuid
    AND processed_at IS NULL
`

type OutboxEventReleaseLeaseParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
	WorkerID  pgtype.UUID        `json:"worker_id"`
}

func (q *Queries) OutboxEventReleaseLease(ctx context.Context, arg OutboxEventReleaseLeaseParams) error {
	_, err := q.db.Exec(ctx, outboxEventReleaseLease, arg.UpdatedAt, arg.ID, arg.WorkerID)
	return err
}

const outboxEventRenewLease = `-- name: OutboxEventRenewLease :exec
UPDATE
    outbox_events
SET
    lease_expires_at = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
    AND locked_by = $4::uuid
    AND processed_at IS NULL
`

type OutboxEventRenewLeaseParams struct {
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             pgtype.UUID        `json:"id"`
	WorkerID       pgtype.UUID        `json:"worker_id"`
}

func (q *Queries) OutboxEventRenewLease(ctx context.Context, arg OutboxEventRenewLeaseParams) error {
	_, err := q.db.Exec(ctx, outboxEventRenewLease,
		arg.LeaseExpiresAt,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkerID,
	)
	return err
}
