// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const outboxEventAcquireBatch = `-- name: OutboxEventAcquireBatch :many
UPDATE
    outbox_events
SET
    locked_by = $1::uuid,
    lease_expires_at = CURRENT_TIMESTAMP + make_interval(secs => $2::int),
    updated_at = CURRENT_TIMESTAMP
WHERE (id, created_at) IN (
    SELECT
        id,
        created_at
    FROM
        outbox_events
    WHERE
        processed_at IS NULL
        AND attempts < max_attempts
        AND next_attempt_at <= CURRENT_TIMESTAMP
        AND (lease_expires_at IS NULL
            OR lease_expires_at < CURRENT_TIMESTAMP)
    ORDER BY
        next_attempt_at ASC,
        id ASC
    LIMIT $3::int
    FOR UPDATE
        SKIP LOCKED)
RETURNING
    id,
    aggregate_id,
    aggregate_type,
    event_type,
    payload,
    trace_id,
    created_at,
    updated_at,
    next_attempt_at,
    lease_expires_at,
    processed_at,
    locked_by,
    attempts,
    max_attempts,
    last_error
`

type OutboxEventAcquireBatchParams struct {
	WorkerID             pgtype.UUID `json:"worker_id"`
	LeaseDurationSeconds int32       `json:"lease_duration_seconds"`
	BatchSize            int32       `json:"batch_size"`
}

type OutboxEventAcquireBatchRow struct {
	ID             pgtype.UUID        `json:"id"`
	AggregateID    pgtype.UUID        `json:"aggregate_id"`
	AggregateType  pgtype.Text        `json:"aggregate_type"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	TraceID        pgtype.Text        `json:"trace_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	LockedBy       pgtype.UUID        `json:"locked_by"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	LastError      pgtype.Text        `json:"last_error"`
}

func (q *Queries) OutboxEventAcquireBatch(ctx context.Context, arg OutboxEventAcquireBatchParams) ([]OutboxEventAcquireBatchRow, error) {
	rows, err := q.db.Query(ctx, outboxEventAcquireBatch, arg.WorkerID, arg.LeaseDurationSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEventAcquireBatchRow
	for rows.Next() {
		var i OutboxEventAcquireBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
			&i.LeaseExpiresAt,
			&i.ProcessedAt,
			&i.LockedBy,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxEventCreate = `-- name: OutboxEventCreate :one
INSERT INTO outbox_events(id, aggregate_id, aggregate_type, event_type, payload, trace_id, created_at, updated_at, next_attempt_at, attempts, max_attempts)
    VALUES ($1::uuid, $2::uuid, $3::text, $4::text, $5::jsonb, $6::text, $7::timestamptz, $8::timestamptz, $9::timestamptz, $10::int, $11::int)
RETURNING
    id, aggregate_id, aggregate_type, event_type, payload, trace_id, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, locked_by, attempts, max_attempts, last_error
`

type OutboxEventCreateParams struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType pgtype.Text        `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	TraceID       pgtype.Text        `json:"trace_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
}

type OutboxEventCreateRow struct {
	ID             pgtype.UUID        `json:"id"`
	AggregateID    pgtype.UUID        `json:"aggregate_id"`
	AggregateType  pgtype.Text        `json:"aggregate_type"`
	EventType      string             `json:"event_type"`
	Payload        []byte             `json:"payload"`
	TraceID        pgtype.Text        `json:"trace_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	LockedBy       pgtype.UUID        `json:"locked_by"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	LastError      pgtype.Text        `json:"last_error"`
}

func (q *Queries) OutboxEventCreate(ctx context.Context, arg OutboxEventCreateParams) (OutboxEventCreateRow, error) {
	row := q.db.QueryRow(ctx, outboxEventCreate,
		arg.ID,
		arg.AggregateID,
		arg.AggregateType,
		arg.EventType,
		arg.Payload,
		arg.TraceID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.NextAttemptAt,
		arg.Attempts,
		arg.MaxAttempts,
	)
	var i OutboxEventCreateRow
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.AggregateType,
		&i.EventType,
		&i.Payload,
		&i.TraceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
		&i.LeaseExpiresAt,
		&i.ProcessedAt,
		&i.LockedBy,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastError,
	)
	return i, err
}

type OutboxEventCreateBatchParams struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType pgtype.Text        `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	TraceID       pgtype.Text        `json:"trace_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
}

const outboxEventListDeadLetter = `-- name: OutboxEventListDeadLetter :many
SELECT
    id,
    aggregate_id,
    aggregate_type,
    event_type,
    payload,
    trace_id,
    created_at,
    updated_at,
    next_attempt_at,
    attempts,
    max_attempts,
    last_error
FROM
    outbox_events
WHERE
    processed_at IS NULL
    AND attempts >= max_attempts
    AND ($1::uuid IS NULL
        OR id < $1::uuid)
ORDER BY
    id DESC
LIMIT $2::int
`

type OutboxEventListDeadLetterParams struct {
	CursorID pgtype.UUID `json:"cursor_id"`
	LimitVal int32       `json:"limit_val"`
}

type OutboxEventListDeadLetterRow struct {
	ID            pgtype.UUID        `json:"id"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType pgtype.Text        `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	TraceID       pgtype.Text        `json:"trace_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	Attempts      int32              `json:"attempts"`
	MaxAttempts   int32              `json:"max_attempts"`
	LastError     pgtype.Text        `json:"last_error"`
}

func (q *Queries) OutboxEventListDeadLetter(ctx context.Context, arg OutboxEventListDeadLetterParams) ([]OutboxEventListDeadLetterRow, error) {
	rows, err := q.db.Query(ctx, outboxEventListDeadLetter, arg.CursorID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEventListDeadLetterRow
	for rows.Next() {
		var i OutboxEventListDeadLetterRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.AggregateType,
			&i.EventType,
			&i.Payload,
			&i.TraceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxEventMarkFailed = `-- name: OutboxEventMarkFailed :one
UPDATE
    outbox_events
SET
    attempts = attempts + 1,
    next_attempt_at = $1::timestamptz,
    last_error = $2::text,
    locked_by = NULL,
    lease_expires_at = NULL,
    updated_at = $3::timestamptz
WHERE
    id = $4::uuid
    AND created_at = $5::timestamptz
    AND locked_by = $6::uuid
    AND processed_at IS NULL
RETURNING
    id,
    created_at,
    attempts,
    next_attempt_at,
    last_error,
    updated_at
`

type OutboxEventMarkFailedParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     string             `json:"last_error"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ID            pgtype.UUID        `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WorkerID      pgtype.UUID        `json:"worker_id"`
}

type OutboxEventMarkFailedRow struct {
	ID            pgtype.UUID        `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastError     pgtype.Text        `json:"last_error"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) OutboxEventMarkFailed(ctx context.Context, arg OutboxEventMarkFailedParams) (OutboxEventMarkFailedRow, error) {
	row := q.db.QueryRow(ctx, outboxEventMarkFailed,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.CreatedAt,
		arg.WorkerID,
	)
	var i OutboxEventMarkFailedRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const outboxEventMarkProcessed = `-- name: OutboxEventMarkProcessed :one
UPDATE
    outbox_events
SET
    processed_at = $1::timestamptz,
    locked_by = NULL,
    lease_expires_at = NULL,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
    AND created_at = $4::timestamptz
    AND locked_by = $5::uuid
    AND processed_at IS NULL
RETURNING
    id,
    created_at,
    processed_at,
    updated_at
`

type OutboxEventMarkProcessedParams struct {
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	WorkerID    pgtype.UUID        `json:"worker_id"`
}

type OutboxEventMarkProcessedRow struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) OutboxEventMarkProcessed(ctx context.Context, arg OutboxEventMarkProcessedParams) (OutboxEventMarkProcessedRow, error) {
	row := q.db.QueryRow(ctx, outboxEventMarkProcessed,
		arg.ProcessedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.CreatedAt,
		arg.WorkerID,
	)
	var i OutboxEventMarkProcessedRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ProcessedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const outboxEventReleaseLease = `-- name: OutboxEventReleaseLease :exec
UPDATE
    outbox_events
SET
    locked_by = NULL,
    lease_expires_at = NULL,
    updated_at = $1::timestamptz
WHERE
    id = $2::uuid
    AND created_at = $3::timestamptz
    AND locked_by = $4::uuid
    AND processed_at IS NULL
`

type OutboxEventReleaseLeaseParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	WorkerID  pgtype.UUID        `json:"worker_id"`
}

func (q *Queries) OutboxEventReleaseLease(ctx context.Context, arg OutboxEventReleaseLeaseParams) error {
	_, err := q.db.Exec(ctx, outboxEventReleaseLease,
		arg.UpdatedAt,
		arg.ID,
		arg.CreatedAt,
		arg.WorkerID,
	)
	return err
}

const outboxEventRenewLease = `-- name: OutboxEventRenewLease :exec
UPDATE
    outbox_events
SET
    lease_expires_at = CURRENT_TIMESTAMP + make_interval(secs => $1::int),
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $2::uuid
    AND created_at = $3::timestamptz
    AND locked_by = $4::uuid
    AND processed_at IS NULL
`

type OutboxEventRenewLeaseParams struct {
	LeaseDurationSeconds int32              `json:"lease_duration_seconds"`
	ID                   pgtype.UUID        `json:"id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	WorkerID             pgtype.UUID        `json:"worker_id"`
}

func (q *Queries) OutboxEventRenewLease(ctx context.Context, arg OutboxEventRenewLeaseParams) error {
	_, err := q.db.Exec(ctx, outboxEventRenewLease,
		arg.LeaseDurationSeconds,
		arg.ID,
		arg.CreatedAt,
		arg.WorkerID,
	)
	return err
}
