// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================================
	// CHANNELS
	// ============================================================================
	ChannelCreate(ctx context.Context, arg ChannelCreateParams) (Channel, error)
	ChannelDelete(ctx context.Context, id pgtype.UUID) error
	ChannelFindDM(ctx context.Context, arg ChannelFindDMParams) (Channel, error)
	ChannelGet(ctx context.Context, id pgtype.UUID) (Channel, error)
	// Used for populating the user's sidebar with channel info & peer profiles for DMs
	ChannelListByUser(ctx context.Context, userID pgtype.UUID) ([]ChannelListByUserRow, error)
	// ============================================================================
	// CHANNEL MEMBERS
	// ============================================================================
	ChannelMemberAdd(ctx context.Context, arg ChannelMemberAddParams) (ChannelMember, error)
	ChannelMemberAddBatch(ctx context.Context, arg ChannelMemberAddBatchParams) error
	ChannelMemberGet(ctx context.Context, arg ChannelMemberGetParams) (ChannelMember, error)
	ChannelMemberIncrementMentionCount(ctx context.Context, arg ChannelMemberIncrementMentionCountParams) error
	ChannelMemberIncrementMentionCountBatch(ctx context.Context, arg ChannelMemberIncrementMentionCountBatchParams) error
	ChannelMemberListByChannel(ctx context.Context, channelID pgtype.UUID) ([]ChannelMemberListByChannelRow, error)
	ChannelMemberRemove(ctx context.Context, arg ChannelMemberRemoveParams) error
	ChannelMemberUpdateReadState(ctx context.Context, arg ChannelMemberUpdateReadStateParams) error
	ChannelUpdate(ctx context.Context, arg ChannelUpdateParams) (Channel, error)
	ChannelUpdateLastMessage(ctx context.Context, arg ChannelUpdateLastMessageParams) error
	// ============================================================================
	// MESSAGES
	// ============================================================================
	MessageCreate(ctx context.Context, arg MessageCreateParams) (Message, error)
	MessageDelete(ctx context.Context, id pgtype.UUID) error
	MessageGet(ctx context.Context, id pgtype.UUID) (Message, error)
	MessageListByChannelKeyset(ctx context.Context, arg MessageListByChannelKeysetParams) ([]Message, error)
	MessageListPinnedByChannel(ctx context.Context, channelID pgtype.UUID) ([]Message, error)
	// Fetches direct replies to a specific parent message
	MessageListReplies(ctx context.Context, replyToMessageID pgtype.UUID) ([]Message, error)
	MessageSetPinned(ctx context.Context, arg MessageSetPinnedParams) error
	MessageUpdateContent(ctx context.Context, arg MessageUpdateContentParams) (Message, error)
	OutboxEventAcquireBatch(ctx context.Context, arg OutboxEventAcquireBatchParams) ([]OutboxEvent, error)
	OutboxEventCreate(ctx context.Context, arg OutboxEventCreateParams) (OutboxEvent, error)
	OutboxEventDelete(ctx context.Context, id pgtype.UUID) error
	OutboxEventGet(ctx context.Context, id pgtype.UUID) (OutboxEvent, error)
	OutboxEventList(ctx context.Context, arg OutboxEventListParams) ([]OutboxEvent, error)
	OutboxEventPurgeProcessed(ctx context.Context, retentionDays int32) error
	OutboxEventRenewLease(ctx context.Context, arg OutboxEventRenewLeaseParams) error
	OutboxEventUpdate(ctx context.Context, arg OutboxEventUpdateParams) (OutboxEvent, error)
	// ============================================================================
	// MESSAGE REACTIONS
	// ============================================================================
	ReactionAdd(ctx context.Context, arg ReactionAddParams) (MessageReaction, error)
	ReactionListByMessage(ctx context.Context, messageID pgtype.UUID) ([]MessageReaction, error)
	ReactionRemove(ctx context.Context, arg ReactionRemoveParams) error
	ReactionSummarizeByMessage(ctx context.Context, arg ReactionSummarizeByMessageParams) ([]ReactionSummarizeByMessageRow, error)
	RelationshipDelete(ctx context.Context, arg RelationshipDeleteParams) error
	RelationshipDeleteVerified(ctx context.Context, arg RelationshipDeleteVerifiedParams) error
	RelationshipGet(ctx context.Context, arg RelationshipGetParams) (RelationshipGetRow, error)
	RelationshipGetForUpdate(ctx context.Context, arg RelationshipGetForUpdateParams) (RelationshipGetForUpdateRow, error)
	RelationshipPerspectiveGet(ctx context.Context, arg RelationshipPerspectiveGetParams) (RelationshipPerspective, error)
	RelationshipPerspectivesList(ctx context.Context, arg RelationshipPerspectivesListParams) ([]RelationshipPerspective, error)
	RelationshipUpsert(ctx context.Context, arg RelationshipUpsertParams) (RelationshipUpsertRow, error)
	SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error)
	SessionDelete(ctx context.Context, id pgtype.UUID) error
	SessionDeleteAllByUserID(ctx context.Context, userID pgtype.UUID) error
	SessionDeleteAllExcept(ctx context.Context, arg SessionDeleteAllExceptParams) error
	SessionDeleteAllExpired(ctx context.Context) error
	SessionGet(ctx context.Context, id pgtype.UUID) (Session, error)
	SessionSave(ctx context.Context, arg SessionSaveParams) (Session, error)
	UserCheckAvailability(ctx context.Context, arg UserCheckAvailabilityParams) (UserCheckAvailabilityRow, error)
	UserCreateAggregate(ctx context.Context, arg UserCreateAggregateParams) error
	UserGet(ctx context.Context, id pgtype.UUID) (UserAggregate, error)
	UserGetByEmail(ctx context.Context, email string) (UserAggregate, error)
	UserGetByUsername(ctx context.Context, username string) (UserAggregate, error)
	UserProfileUpsert(ctx context.Context, arg UserProfileUpsertParams) (UserProfile, error)
	UserUpdate(ctx context.Context, arg UserUpdateParams) (User, error)
}

var _ Querier = (*Queries)(nil)
