// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelCreate = `-- name: ChannelCreate :one
INSERT INTO channels(id, type, owner_id, name, icon_url, created_at, updated_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, owner_id, last_message_id, created_at, updated_at, type, name, icon_url
`

type ChannelCreateParams struct {
	ID        pgtype.UUID        `json:"id"`
	Type      int16              `json:"type"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Name      pgtype.Text        `json:"name"`
	IconUrl   pgtype.Text        `json:"icon_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// ============================================================================
// CHANNELS
// ============================================================================
func (q *Queries) ChannelCreate(ctx context.Context, arg ChannelCreateParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelCreate,
		arg.ID,
		arg.Type,
		arg.OwnerID,
		arg.Name,
		arg.IconUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelDelete = `-- name: ChannelDelete :exec
DELETE FROM channels
WHERE id = $1
`

func (q *Queries) ChannelDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, channelDelete, id)
	return err
}

const channelFindDirectMessage = `-- name: ChannelFindDirectMessage :one
SELECT
    c.id, c.owner_id, c.last_message_id, c.created_at, c.updated_at, c.type, c.name, c.icon_url
FROM
    channels c
    JOIN channel_members m1 ON c.id = m1.channel_id
    JOIN channel_members m2 ON c.id = m2.channel_id
WHERE
    c.type = 0
    AND m1.user_id = $1::uuid
    AND m2.user_id = $2::uuid
    AND m1.user_id != m2.user_id
    AND (
        SELECT
            COUNT(*)
        FROM
            channel_members cm
        WHERE
            cm.channel_id = c.id) = 2
LIMIT 1
`

type ChannelFindDirectMessageParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

// Finds an existing 1:1 DM strictly between two unique users
func (q *Queries) ChannelFindDirectMessage(ctx context.Context, arg ChannelFindDirectMessageParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelFindDirectMessage, arg.User1ID, arg.User2ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelGet = `-- name: ChannelGet :one
SELECT
    id, owner_id, last_message_id, created_at, updated_at, type, name, icon_url
FROM
    channels
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) ChannelGet(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, channelGet, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelGetForUpdate = `-- name: ChannelGetForUpdate :one
SELECT
    id, owner_id, last_message_id, created_at, updated_at, type, name, icon_url
FROM
    channels
WHERE
    id = $1
FOR UPDATE
`

func (q *Queries) ChannelGetForUpdate(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, channelGetForUpdate, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelMemberAdd = `-- name: ChannelMemberAdd :one
INSERT INTO channel_members(channel_id, user_id, joined_at, last_read_message_id, mention_count)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    channel_id, user_id, last_read_message_id, joined_at, mention_count
`

type ChannelMemberAddParams struct {
	ChannelID         pgtype.UUID        `json:"channel_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
	LastReadMessageID pgtype.UUID        `json:"last_read_message_id"`
	MentionCount      int32              `json:"mention_count"`
}

// ============================================================================
// CHANNEL MEMBERS
// ============================================================================
func (q *Queries) ChannelMemberAdd(ctx context.Context, arg ChannelMemberAddParams) (ChannelMember, error) {
	row := q.db.QueryRow(ctx, channelMemberAdd,
		arg.ChannelID,
		arg.UserID,
		arg.JoinedAt,
		arg.LastReadMessageID,
		arg.MentionCount,
	)
	var i ChannelMember
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.MentionCount,
	)
	return i, err
}

const channelMemberGet = `-- name: ChannelMemberGet :one
SELECT
    channel_id, user_id, last_read_message_id, joined_at, mention_count
FROM
    channel_members
WHERE
    channel_id = $1
    AND user_id = $2
LIMIT 1
`

type ChannelMemberGetParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelMemberGet(ctx context.Context, arg ChannelMemberGetParams) (ChannelMember, error) {
	row := q.db.QueryRow(ctx, channelMemberGet, arg.ChannelID, arg.UserID)
	var i ChannelMember
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.JoinedAt,
		&i.MentionCount,
	)
	return i, err
}

const channelMemberIncrementMentionCount = `-- name: ChannelMemberIncrementMentionCount :exec
UPDATE
    channel_members
SET
    mention_count = mention_count + 1
WHERE
    channel_id = $1
    AND user_id = $2
`

type ChannelMemberIncrementMentionCountParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelMemberIncrementMentionCount(ctx context.Context, arg ChannelMemberIncrementMentionCountParams) error {
	_, err := q.db.Exec(ctx, channelMemberIncrementMentionCount, arg.ChannelID, arg.UserID)
	return err
}

const channelMemberListByChannel = `-- name: ChannelMemberListByChannel :many
SELECT
    channel_id, user_id, last_read_message_id, joined_at, mention_count
FROM
    channel_members
WHERE
    channel_id = $1
ORDER BY
    joined_at ASC
`

func (q *Queries) ChannelMemberListByChannel(ctx context.Context, channelID pgtype.UUID) ([]ChannelMember, error) {
	rows, err := q.db.Query(ctx, channelMemberListByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMember
	for rows.Next() {
		var i ChannelMember
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.LastReadMessageID,
			&i.JoinedAt,
			&i.MentionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelMemberListByUser = `-- name: ChannelMemberListByUser :many
SELECT
    cm.channel_id, cm.user_id, cm.last_read_message_id, cm.joined_at, cm.mention_count,
    c.type AS channel_type,
    c.owner_id AS channel_owner_id,
    c.name AS channel_name,
    c.icon_url AS channel_icon_url,
    c.last_message_id AS channel_last_message_id,
    c.updated_at AS channel_updated_at
FROM
    channel_members cm
    JOIN channels c ON cm.channel_id = c.id
WHERE
    cm.user_id = $1
ORDER BY
    c.updated_at DESC
`

type ChannelMemberListByUserRow struct {
	ChannelID            pgtype.UUID        `json:"channel_id"`
	UserID               pgtype.UUID        `json:"user_id"`
	LastReadMessageID    pgtype.UUID        `json:"last_read_message_id"`
	JoinedAt             pgtype.Timestamptz `json:"joined_at"`
	MentionCount         int32              `json:"mention_count"`
	ChannelType          int16              `json:"channel_type"`
	ChannelOwnerID       pgtype.UUID        `json:"channel_owner_id"`
	ChannelName          pgtype.Text        `json:"channel_name"`
	ChannelIconUrl       pgtype.Text        `json:"channel_icon_url"`
	ChannelLastMessageID pgtype.UUID        `json:"channel_last_message_id"`
	ChannelUpdatedAt     pgtype.Timestamptz `json:"channel_updated_at"`
}

// Used for populating the user's sidebar
func (q *Queries) ChannelMemberListByUser(ctx context.Context, userID pgtype.UUID) ([]ChannelMemberListByUserRow, error) {
	rows, err := q.db.Query(ctx, channelMemberListByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMemberListByUserRow
	for rows.Next() {
		var i ChannelMemberListByUserRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.LastReadMessageID,
			&i.JoinedAt,
			&i.MentionCount,
			&i.ChannelType,
			&i.ChannelOwnerID,
			&i.ChannelName,
			&i.ChannelIconUrl,
			&i.ChannelLastMessageID,
			&i.ChannelUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelMemberRemove = `-- name: ChannelMemberRemove :exec
DELETE FROM channel_members
WHERE channel_id = $1
    AND user_id = $2
`

type ChannelMemberRemoveParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelMemberRemove(ctx context.Context, arg ChannelMemberRemoveParams) error {
	_, err := q.db.Exec(ctx, channelMemberRemove, arg.ChannelID, arg.UserID)
	return err
}

const channelMemberUpdateReadState = `-- name: ChannelMemberUpdateReadState :exec
UPDATE
    channel_members
SET
    last_read_message_id = $1,
    mention_count = 0
WHERE
    channel_id = $2
    AND user_id = $3
`

type ChannelMemberUpdateReadStateParams struct {
	LastReadMessageID pgtype.UUID `json:"last_read_message_id"`
	ChannelID         pgtype.UUID `json:"channel_id"`
	UserID            pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelMemberUpdateReadState(ctx context.Context, arg ChannelMemberUpdateReadStateParams) error {
	_, err := q.db.Exec(ctx, channelMemberUpdateReadState, arg.LastReadMessageID, arg.ChannelID, arg.UserID)
	return err
}

const channelUpdate = `-- name: ChannelUpdate :one
UPDATE
    channels
SET
    name = $1,
    icon_url = $2,
    owner_id = $3,
    last_message_id = $4,
    updated_at = $5
WHERE
    id = $6
RETURNING
    id, owner_id, last_message_id, created_at, updated_at, type, name, icon_url
`

type ChannelUpdateParams struct {
	Name          pgtype.Text        `json:"name"`
	IconUrl       pgtype.Text        `json:"icon_url"`
	OwnerID       pgtype.UUID        `json:"owner_id"`
	LastMessageID pgtype.UUID        `json:"last_message_id"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) ChannelUpdate(ctx context.Context, arg ChannelUpdateParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelUpdate,
		arg.Name,
		arg.IconUrl,
		arg.OwnerID,
		arg.LastMessageID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LastMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelUpdateLastMessage = `-- name: ChannelUpdateLastMessage :exec
UPDATE
    channels
SET
    last_message_id = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $2
`

type ChannelUpdateLastMessageParams struct {
	LastMessageID pgtype.UUID `json:"last_message_id"`
	ChannelID     pgtype.UUID `json:"channel_id"`
}

func (q *Queries) ChannelUpdateLastMessage(ctx context.Context, arg ChannelUpdateLastMessageParams) error {
	_, err := q.db.Exec(ctx, channelUpdateLastMessage, arg.LastMessageID, arg.ChannelID)
	return err
}

const messageCreate = `-- name: MessageCreate :one
INSERT INTO messages(id, channel_id, author_id, reply_to_message_id, content, is_pinned, created_at, edited_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, channel_id, author_id, reply_to_message_id, created_at, edited_at, is_pinned, content
`

type MessageCreateParams struct {
	ID               pgtype.UUID        `json:"id"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	ReplyToMessageID pgtype.UUID        `json:"reply_to_message_id"`
	Content          pgtype.Text        `json:"content"`
	IsPinned         bool               `json:"is_pinned"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	EditedAt         pgtype.Timestamptz `json:"edited_at"`
}

// ============================================================================
// MESSAGES
// ============================================================================
func (q *Queries) MessageCreate(ctx context.Context, arg MessageCreateParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageCreate,
		arg.ID,
		arg.ChannelID,
		arg.AuthorID,
		arg.ReplyToMessageID,
		arg.Content,
		arg.IsPinned,
		arg.CreatedAt,
		arg.EditedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ReplyToMessageID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
	)
	return i, err
}

const messageDelete = `-- name: MessageDelete :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) MessageDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, messageDelete, id)
	return err
}

const messageGet = `-- name: MessageGet :one
SELECT
    id, channel_id, author_id, reply_to_message_id, created_at, edited_at, is_pinned, content
FROM
    messages
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) MessageGet(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, messageGet, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ReplyToMessageID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
	)
	return i, err
}

const messageListByChannelKeyset = `-- name: MessageListByChannelKeyset :many
SELECT
    id, channel_id, author_id, reply_to_message_id, created_at, edited_at, is_pinned, content
FROM
    messages
WHERE
    channel_id = $1
    AND ($2::uuid IS NULL
        OR id < $2)
ORDER BY
    id DESC
LIMIT $3
`

type MessageListByChannelKeysetParams struct {
	ChannelID   pgtype.UUID `json:"channel_id"`
	CursorID    pgtype.UUID `json:"cursor_id"`
	ResultLimit int32       `json:"result_limit"`
}

// Keyset/Cursor pagination for infinite scroll
func (q *Queries) MessageListByChannelKeyset(ctx context.Context, arg MessageListByChannelKeysetParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, messageListByChannelKeyset, arg.ChannelID, arg.CursorID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.ReplyToMessageID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.IsPinned,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageListPinnedByChannel = `-- name: MessageListPinnedByChannel :many
SELECT
    id, channel_id, author_id, reply_to_message_id, created_at, edited_at, is_pinned, content
FROM
    messages
WHERE
    channel_id = $1
    AND is_pinned = TRUE
ORDER BY
    created_at DESC
`

func (q *Queries) MessageListPinnedByChannel(ctx context.Context, channelID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, messageListPinnedByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.ReplyToMessageID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.IsPinned,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageSetPinned = `-- name: MessageSetPinned :exec
UPDATE
    messages
SET
    is_pinned = $1
WHERE
    id = $2
`

type MessageSetPinnedParams struct {
	IsPinned bool        `json:"is_pinned"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) MessageSetPinned(ctx context.Context, arg MessageSetPinnedParams) error {
	_, err := q.db.Exec(ctx, messageSetPinned, arg.IsPinned, arg.ID)
	return err
}

const messageUpdateContent = `-- name: MessageUpdateContent :one
UPDATE
    messages
SET
    content = $1,
    edited_at = $2
WHERE
    id = $3
RETURNING
    id, channel_id, author_id, reply_to_message_id, created_at, edited_at, is_pinned, content
`

type MessageUpdateContentParams struct {
	Content  pgtype.Text        `json:"content"`
	EditedAt pgtype.Timestamptz `json:"edited_at"`
	ID       pgtype.UUID        `json:"id"`
}

func (q *Queries) MessageUpdateContent(ctx context.Context, arg MessageUpdateContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageUpdateContent, arg.Content, arg.EditedAt, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.ReplyToMessageID,
		&i.CreatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
	)
	return i, err
}

const outboxEventAcquireBatch = `-- name: OutboxEventAcquireBatch :many
UPDATE
    outbox_events
SET
    locked_by = $1::uuid,
    lease_expires_at = CURRENT_TIMESTAMP + make_interval(secs => $2::int),
    updated_at = CURRENT_TIMESTAMP
WHERE
    id IN (
        SELECT
            id
        FROM
            outbox_events
        WHERE
            processed_at IS NULL
            AND attempts < max_attempts
            AND next_attempt_at <= CURRENT_TIMESTAMP
            AND (lease_expires_at IS NULL
                OR lease_expires_at < CURRENT_TIMESTAMP)
        ORDER BY
            next_attempt_at ASC,
            id ASC
        LIMIT $3::int
        FOR UPDATE
            SKIP LOCKED)
RETURNING
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
`

type OutboxEventAcquireBatchParams struct {
	WorkerID             pgtype.UUID `json:"worker_id"`
	LeaseDurationSeconds int32       `json:"lease_duration_seconds"`
	BatchSize            int32       `json:"batch_size"`
}

func (q *Queries) OutboxEventAcquireBatch(ctx context.Context, arg OutboxEventAcquireBatchParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, outboxEventAcquireBatch, arg.WorkerID, arg.LeaseDurationSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.LockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
			&i.LeaseExpiresAt,
			&i.ProcessedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.EventType,
			&i.Payload,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxEventCreate = `-- name: OutboxEventCreate :one
INSERT INTO outbox_events(id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, last_error, payload)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
`

type OutboxEventCreateParams struct {
	ID             pgtype.UUID        `json:"id"`
	LockedBy       pgtype.UUID        `json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	EventType      string             `json:"event_type"`
	LastError      pgtype.Text        `json:"last_error"`
	Payload        []byte             `json:"payload"`
}

func (q *Queries) OutboxEventCreate(ctx context.Context, arg OutboxEventCreateParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, outboxEventCreate,
		arg.ID,
		arg.LockedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.NextAttemptAt,
		arg.LeaseExpiresAt,
		arg.ProcessedAt,
		arg.Attempts,
		arg.MaxAttempts,
		arg.EventType,
		arg.LastError,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
		&i.LeaseExpiresAt,
		&i.ProcessedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.EventType,
		&i.Payload,
		&i.LastError,
	)
	return i, err
}

const outboxEventDelete = `-- name: OutboxEventDelete :exec
DELETE FROM outbox_events
WHERE id = $1
`

func (q *Queries) OutboxEventDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, outboxEventDelete, id)
	return err
}

const outboxEventGet = `-- name: OutboxEventGet :one
SELECT
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
FROM
    outbox_events
WHERE
    id = $1
`

func (q *Queries) OutboxEventGet(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, outboxEventGet, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
		&i.LeaseExpiresAt,
		&i.ProcessedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.EventType,
		&i.Payload,
		&i.LastError,
	)
	return i, err
}

const outboxEventList = `-- name: OutboxEventList :many
SELECT
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
FROM
    outbox_events
WHERE ($1::uuid IS NULL
    OR id < $1)
ORDER BY
    id DESC
LIMIT $2
`

type OutboxEventListParams struct {
	CursorID    pgtype.UUID `json:"cursor_id"`
	ResultLimit int32       `json:"result_limit"`
}

func (q *Queries) OutboxEventList(ctx context.Context, arg OutboxEventListParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, outboxEventList, arg.CursorID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.LockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
			&i.LeaseExpiresAt,
			&i.ProcessedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.EventType,
			&i.Payload,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxEventPurgeProcessed = `-- name: OutboxEventPurgeProcessed :exec
DELETE FROM outbox_events
WHERE processed_at <(CURRENT_TIMESTAMP - make_interval(days => $1::int))
`

func (q *Queries) OutboxEventPurgeProcessed(ctx context.Context, retentionDays int32) error {
	_, err := q.db.Exec(ctx, outboxEventPurgeProcessed, retentionDays)
	return err
}

const outboxEventRenewLease = `-- name: OutboxEventRenewLease :exec
UPDATE
    outbox_events
SET
    lease_expires_at = CURRENT_TIMESTAMP + make_interval(secs => $1::int),
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $2::uuid
    AND locked_by = $3::uuid
    AND processed_at IS NULL
`

type OutboxEventRenewLeaseParams struct {
	LeaseDurationSeconds int32       `json:"lease_duration_seconds"`
	ID                   pgtype.UUID `json:"id"`
	WorkerID             pgtype.UUID `json:"worker_id"`
}

func (q *Queries) OutboxEventRenewLease(ctx context.Context, arg OutboxEventRenewLeaseParams) error {
	_, err := q.db.Exec(ctx, outboxEventRenewLease, arg.LeaseDurationSeconds, arg.ID, arg.WorkerID)
	return err
}

const outboxEventUpdate = `-- name: OutboxEventUpdate :one
UPDATE
    outbox_events
SET
    locked_by = $1,
    lease_expires_at = $2,
    processed_at = $3,
    attempts = $4,
    max_attempts = $5,
    next_attempt_at = $6,
    last_error = $7,
    updated_at = $8
WHERE
    id = $9
RETURNING
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
`

type OutboxEventUpdateParams struct {
	LockedBy       pgtype.UUID        `json:"locked_by"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LastError      pgtype.Text        `json:"last_error"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) OutboxEventUpdate(ctx context.Context, arg OutboxEventUpdateParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, outboxEventUpdate,
		arg.LockedBy,
		arg.LeaseExpiresAt,
		arg.ProcessedAt,
		arg.Attempts,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
		&i.LeaseExpiresAt,
		&i.ProcessedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.EventType,
		&i.Payload,
		&i.LastError,
	)
	return i, err
}

const reactionAdd = `-- name: ReactionAdd :one
INSERT INTO message_reactions(message_id, user_id, emoji, created_at)
    VALUES ($1, $2, $3, $4)
ON CONFLICT (message_id, user_id, emoji)
    DO UPDATE SET
        created_at = EXCLUDED.created_at
    RETURNING
        message_id, user_id, created_at, emoji
`

type ReactionAddParams struct {
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// ============================================================================
// MESSAGE REACTIONS
// ============================================================================
func (q *Queries) ReactionAdd(ctx context.Context, arg ReactionAddParams) (MessageReaction, error) {
	row := q.db.QueryRow(ctx, reactionAdd,
		arg.MessageID,
		arg.UserID,
		arg.Emoji,
		arg.CreatedAt,
	)
	var i MessageReaction
	err := row.Scan(
		&i.MessageID,
		&i.UserID,
		&i.CreatedAt,
		&i.Emoji,
	)
	return i, err
}

const reactionListByMessage = `-- name: ReactionListByMessage :many
SELECT
    message_id, user_id, created_at, emoji
FROM
    message_reactions
WHERE
    message_id = $1
ORDER BY
    created_at ASC
`

func (q *Queries) ReactionListByMessage(ctx context.Context, messageID pgtype.UUID) ([]MessageReaction, error) {
	rows, err := q.db.Query(ctx, reactionListByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageReaction
	for rows.Next() {
		var i MessageReaction
		if err := rows.Scan(
			&i.MessageID,
			&i.UserID,
			&i.CreatedAt,
			&i.Emoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactionRemove = `-- name: ReactionRemove :exec
DELETE FROM message_reactions
WHERE message_id = $1
    AND user_id = $2
    AND emoji = $3
`

type ReactionRemoveParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) ReactionRemove(ctx context.Context, arg ReactionRemoveParams) error {
	_, err := q.db.Exec(ctx, reactionRemove, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const reactionSummarizeByMessage = `-- name: ReactionSummarizeByMessage :many
SELECT
    emoji,
    COUNT(*)::int AS count
FROM
    message_reactions
WHERE
    message_id = $1
GROUP BY
    emoji
ORDER BY
    count DESC
`

type ReactionSummarizeByMessageRow struct {
	Emoji string `json:"emoji"`
	Count int32  `json:"count"`
}

func (q *Queries) ReactionSummarizeByMessage(ctx context.Context, messageID pgtype.UUID) ([]ReactionSummarizeByMessageRow, error) {
	rows, err := q.db.Query(ctx, reactionSummarizeByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReactionSummarizeByMessageRow
	for rows.Next() {
		var i ReactionSummarizeByMessageRow
		if err := rows.Scan(&i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relationshipDelete = `-- name: RelationshipDelete :exec
DELETE FROM relationships
WHERE user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
`

type RelationshipDeleteParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

func (q *Queries) RelationshipDelete(ctx context.Context, arg RelationshipDeleteParams) error {
	_, err := q.db.Exec(ctx, relationshipDelete, arg.User1ID, arg.User2ID)
	return err
}

const relationshipDeleteVerified = `-- name: RelationshipDeleteVerified :exec
DELETE FROM relationships
WHERE user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
    AND (variant != 3 -- 3 = Blocked
        OR actor_id = $3::uuid)
`

type RelationshipDeleteVerifiedParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
	ActorID pgtype.UUID `json:"actor_id"`
}

func (q *Queries) RelationshipDeleteVerified(ctx context.Context, arg RelationshipDeleteVerifiedParams) error {
	_, err := q.db.Exec(ctx, relationshipDeleteVerified, arg.User1ID, arg.User2ID, arg.ActorID)
	return err
}

const relationshipGet = `-- name: RelationshipGet :one
SELECT
    user1_id,
    user2_id,
    actor_id,
    variant,
    created_at,
    updated_at
FROM
    relationships
WHERE
    user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
`

type RelationshipGetParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

type RelationshipGetRow struct {
	User1ID   pgtype.UUID        `json:"user1_id"`
	User2ID   pgtype.UUID        `json:"user2_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Variant   int16              `json:"variant"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RelationshipGet(ctx context.Context, arg RelationshipGetParams) (RelationshipGetRow, error) {
	row := q.db.QueryRow(ctx, relationshipGet, arg.User1ID, arg.User2ID)
	var i RelationshipGetRow
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.Variant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const relationshipGetForUpdate = `-- name: RelationshipGetForUpdate :one
SELECT
    user1_id,
    user2_id,
    actor_id,
    variant,
    created_at,
    updated_at
FROM
    relationships
WHERE
    user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
FOR UPDATE
`

type RelationshipGetForUpdateParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

type RelationshipGetForUpdateRow struct {
	User1ID   pgtype.UUID        `json:"user1_id"`
	User2ID   pgtype.UUID        `json:"user2_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Variant   int16              `json:"variant"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RelationshipGetForUpdate(ctx context.Context, arg RelationshipGetForUpdateParams) (RelationshipGetForUpdateRow, error) {
	row := q.db.QueryRow(ctx, relationshipGetForUpdate, arg.User1ID, arg.User2ID)
	var i RelationshipGetForUpdateRow
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.Variant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const relationshipPerspectiveGet = `-- name: RelationshipPerspectiveGet :one
SELECT
    user_id,
    peer_id,
    variant,
    actor_id,
    is_initiator,
    created_at,
    updated_at,
    username,
    display_name,
    avatar_url,
    user_preferred_presence,
    channel_id
FROM
    relationship_perspectives
WHERE
    user_id = $1::uuid
    AND peer_id = $2::uuid
`

type RelationshipPerspectiveGetParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PeerID pgtype.UUID `json:"peer_id"`
}

func (q *Queries) RelationshipPerspectiveGet(ctx context.Context, arg RelationshipPerspectiveGetParams) (RelationshipPerspective, error) {
	row := q.db.QueryRow(ctx, relationshipPerspectiveGet, arg.UserID, arg.PeerID)
	var i RelationshipPerspective
	err := row.Scan(
		&i.UserID,
		&i.PeerID,
		&i.Variant,
		&i.ActorID,
		&i.IsInitiator,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.UserPreferredPresence,
		&i.ChannelID,
	)
	return i, err
}

const relationshipPerspectivesList = `-- name: RelationshipPerspectivesList :many
SELECT
    user_id,
    peer_id,
    variant,
    actor_id,
    is_initiator,
    created_at,
    updated_at,
    username,
    display_name,
    avatar_url,
    user_preferred_presence,
    channel_id
FROM
    relationship_perspectives
WHERE
    user_id = $1::uuid
    AND ($2::smallint IS NULL
        OR variant = $2)
ORDER BY
    updated_at DESC
`

type RelationshipPerspectivesListParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	FilterVariant pgtype.Int2 `json:"filter_variant"`
}

func (q *Queries) RelationshipPerspectivesList(ctx context.Context, arg RelationshipPerspectivesListParams) ([]RelationshipPerspective, error) {
	rows, err := q.db.Query(ctx, relationshipPerspectivesList, arg.UserID, arg.FilterVariant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelationshipPerspective
	for rows.Next() {
		var i RelationshipPerspective
		if err := rows.Scan(
			&i.UserID,
			&i.PeerID,
			&i.Variant,
			&i.ActorID,
			&i.IsInitiator,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.UserPreferredPresence,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relationshipUpsert = `-- name: RelationshipUpsert :one
INSERT INTO relationships(user1_id, user2_id, actor_id, variant, created_at, updated_at)
    VALUES (LEAST($1::uuid, $2::uuid), GREATEST($1::uuid, $2::uuid), $3, $4, $5, $6)
ON CONFLICT (user1_id, user2_id)
    DO UPDATE SET
        variant = EXCLUDED.variant,
        actor_id = EXCLUDED.actor_id,
        updated_at = EXCLUDED.updated_at
    RETURNING
        user1_id,
        user2_id,
        actor_id,
        variant,
        created_at,
        updated_at
`

type RelationshipUpsertParams struct {
	User1ID   pgtype.UUID        `json:"user1_id"`
	User2ID   pgtype.UUID        `json:"user2_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Variant   int16              `json:"variant"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RelationshipUpsertRow struct {
	User1ID   pgtype.UUID        `json:"user1_id"`
	User2ID   pgtype.UUID        `json:"user2_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Variant   int16              `json:"variant"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RelationshipUpsert(ctx context.Context, arg RelationshipUpsertParams) (RelationshipUpsertRow, error) {
	row := q.db.QueryRow(ctx, relationshipUpsert,
		arg.User1ID,
		arg.User2ID,
		arg.ActorID,
		arg.Variant,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i RelationshipUpsertRow
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.Variant,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions(id, user_id, refresh_token_hash, expires_at, revoked_at, client_ip, user_agent, os, browser, last_seen_at, created_at, updated_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
    id, user_id, last_seen_at, expires_at, revoked_at, created_at, updated_at, client_ip, refresh_token_hash, user_agent, os, browser
`

type SessionCreateParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ClientIP         netip.Addr         `json:"client_ip"`
	UserAgent        string             `json:"user_agent"`
	OS               string             `json:"os"`
	Browser          string             `json:"browser"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.ClientIP,
		arg.UserAgent,
		arg.OS,
		arg.Browser,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.OS,
		&i.Browser,
	)
	return i, err
}

const sessionDelete = `-- name: SessionDelete :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) SessionDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, sessionDelete, id)
	return err
}

const sessionDeleteAllByUserID = `-- name: SessionDeleteAllByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) SessionDeleteAllByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, sessionDeleteAllByUserID, userID)
	return err
}

const sessionDeleteAllExcept = `-- name: SessionDeleteAllExcept :exec
DELETE FROM sessions
WHERE user_id = $1
    AND id != $2
`

type SessionDeleteAllExceptParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SessionDeleteAllExcept(ctx context.Context, arg SessionDeleteAllExceptParams) error {
	_, err := q.db.Exec(ctx, sessionDeleteAllExcept, arg.UserID, arg.ID)
	return err
}

const sessionDeleteAllExpired = `-- name: SessionDeleteAllExpired :exec
DELETE FROM sessions
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) SessionDeleteAllExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sessionDeleteAllExpired)
	return err
}

const sessionGet = `-- name: SessionGet :one
SELECT
    id, user_id, last_seen_at, expires_at, revoked_at, created_at, updated_at, client_ip, refresh_token_hash, user_agent, os, browser
FROM
    sessions
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) SessionGet(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGet, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.OS,
		&i.Browser,
	)
	return i, err
}

const sessionSave = `-- name: SessionSave :one
UPDATE
    sessions
SET
    refresh_token_hash = $2,
    expires_at = $3,
    last_seen_at = $4,
    revoked_at = $5,
    updated_at = $6
WHERE
    id = $1
RETURNING
    id, user_id, last_seen_at, expires_at, revoked_at, created_at, updated_at, client_ip, refresh_token_hash, user_agent, os, browser
`

type SessionSaveParams struct {
	ID               pgtype.UUID        `json:"id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionSave(ctx context.Context, arg SessionSaveParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionSave,
		arg.ID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.OS,
		&i.Browser,
	)
	return i, err
}

const userCheckAvailability = `-- name: UserCheckAvailability :one
SELECT
    NOT EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            users.email = $1)::boolean AS email_available,
    NOT EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            users.username = $2)::boolean AS username_available
`

type UserCheckAvailabilityParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type UserCheckAvailabilityRow struct {
	EmailAvailable    pgtype.Bool `json:"email_available"`
	UsernameAvailable pgtype.Bool `json:"username_available"`
}

func (q *Queries) UserCheckAvailability(ctx context.Context, arg UserCheckAvailabilityParams) (UserCheckAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, userCheckAvailability, arg.Email, arg.Username)
	var i UserCheckAvailabilityRow
	err := row.Scan(&i.EmailAvailable, &i.UsernameAvailable)
	return i, err
}

const userCreateAggregate = `-- name: UserCreateAggregate :exec
WITH new_user AS (
INSERT INTO users(id, created_at, updated_at, verified_at, preferred_presence, email, username, password_hash)
        VALUES ($1, $6, $7, $8, $9, $10, $11, $12))
    INSERT INTO user_profiles(user_id, created_at, updated_at, display_name, avatar_url)
        VALUES ($1, $2, $3, $4, $5)
`

type UserCreateAggregateParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	ProfileCreatedAt  pgtype.Timestamptz `json:"profile_created_at"`
	ProfileUpdatedAt  pgtype.Timestamptz `json:"profile_updated_at"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	UserCreatedAt     pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt     pgtype.Timestamptz `json:"user_updated_at"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	PreferredPresence pgtype.Int2        `json:"preferred_presence"`
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	PasswordHash      string             `json:"password_hash"`
}

func (q *Queries) UserCreateAggregate(ctx context.Context, arg UserCreateAggregateParams) error {
	_, err := q.db.Exec(ctx, userCreateAggregate,
		arg.UserID,
		arg.ProfileCreatedAt,
		arg.ProfileUpdatedAt,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.UserCreatedAt,
		arg.UserUpdatedAt,
		arg.VerifiedAt,
		arg.PreferredPresence,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
	)
	return err
}

const userGet = `-- name: UserGet :one
SELECT
    id, email, username, password_hash, preferred_presence, verified_at, display_name, avatar_url, created_at, updated_at, profile_created_at, profile_updated_at
FROM
    user_aggregates
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) UserGet(ctx context.Context, id pgtype.UUID) (UserAggregate, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i UserAggregate
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PreferredPresence,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const userGetByEmail = `-- name: UserGetByEmail :one
SELECT
    id, email, username, password_hash, preferred_presence, verified_at, display_name, avatar_url, created_at, updated_at, profile_created_at, profile_updated_at
FROM
    user_aggregates
WHERE
    email = $1
LIMIT 1
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (UserAggregate, error) {
	row := q.db.QueryRow(ctx, userGetByEmail, email)
	var i UserAggregate
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PreferredPresence,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const userGetByUsername = `-- name: UserGetByUsername :one
SELECT
    id, email, username, password_hash, preferred_presence, verified_at, display_name, avatar_url, created_at, updated_at, profile_created_at, profile_updated_at
FROM
    user_aggregates
WHERE
    username = $1
LIMIT 1
`

func (q *Queries) UserGetByUsername(ctx context.Context, username string) (UserAggregate, error) {
	row := q.db.QueryRow(ctx, userGetByUsername, username)
	var i UserAggregate
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PreferredPresence,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const userProfileUpsert = `-- name: UserProfileUpsert :one
INSERT INTO user_profiles(user_id, created_at, updated_at, display_name, avatar_url)
    VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id)
    DO UPDATE SET
        display_name = EXCLUDED.display_name,
        avatar_url = EXCLUDED.avatar_url,
        updated_at = EXCLUDED.updated_at
    RETURNING
        user_id, created_at, updated_at, display_name, avatar_url
`

type UserProfileUpsertParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) UserProfileUpsert(ctx context.Context, arg UserProfileUpsertParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileUpsert,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const userUpdate = `-- name: UserUpdate :one
UPDATE
    users
SET
    email = $1,
    username = $2,
    password_hash = $3,
    preferred_presence = $4,
    verified_at = $5,
    updated_at = $6
WHERE
    id = $7
RETURNING
    id, created_at, updated_at, verified_at, preferred_presence, email, username, password_hash
`

type UserUpdateParams struct {
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	PasswordHash      string             `json:"password_hash"`
	PreferredPresence pgtype.Int2        `json:"preferred_presence"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID                pgtype.UUID        `json:"id"`
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, userUpdate,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.PreferredPresence,
		arg.VerifiedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.PreferredPresence,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}
