// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachmentCreateBatch = `-- name: AttachmentCreateBatch :exec
INSERT INTO message_attachments(id, message_id, file_name, file_size, content_type, url, width, height, created_at)
SELECT
    unnest($1::uuid[]),
    $2,
    unnest($3::text[]),
    unnest($4::int[]),
    unnest($5::text[]),
    unnest($6::text[]),
    unnest($7::int[]),
    unnest($8::int[]),
    unnest($9::timestamptz[])
WHERE
    $2 IS NOT NULL
`

type AttachmentCreateBatchParams struct {
	Ids          []pgtype.UUID        `json:"ids"`
	MessageID    pgtype.UUID          `json:"message_id"`
	FileNames    []string             `json:"file_names"`
	FileSizes    []int32              `json:"file_sizes"`
	ContentTypes []string             `json:"content_types"`
	Urls         []string             `json:"urls"`
	Widths       []int32              `json:"widths"`
	Heights      []int32              `json:"heights"`
	CreatedAts   []pgtype.Timestamptz `json:"created_ats"`
}

// ============================================================================
// MESSAGE ATTACHMENTS
// ============================================================================
func (q *Queries) AttachmentCreateBatch(ctx context.Context, arg AttachmentCreateBatchParams) error {
	_, err := q.db.Exec(ctx, attachmentCreateBatch,
		arg.Ids,
		arg.MessageID,
		arg.FileNames,
		arg.FileSizes,
		arg.ContentTypes,
		arg.Urls,
		arg.Widths,
		arg.Heights,
		arg.CreatedAts,
	)
	return err
}

const attachmentDeleteByMessage = `-- name: AttachmentDeleteByMessage :exec
DELETE FROM message_attachments
WHERE message_id = $1
`

func (q *Queries) AttachmentDeleteByMessage(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, attachmentDeleteByMessage, messageID)
	return err
}

const channelCreate = `-- name: ChannelCreate :one
INSERT INTO channels(id, created_at, updated_at, type, last_message_id, name, icon_url)
    VALUES ($1::uuid, $2::timestamptz, $3::timestamptz, $4::smallint, $5::uuid, $6::text, $7::text)
RETURNING
    id, created_at, updated_at, type, last_message_id, name, icon_url
`

type ChannelCreateParams struct {
	ID            pgtype.UUID        `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Type          int16              `json:"type"`
	LastMessageID pgtype.UUID        `json:"last_message_id"`
	Name          pgtype.Text        `json:"name"`
	IconUrl       pgtype.Text        `json:"icon_url"`
}

// ============================================================================
// CHANNELS
// ============================================================================
func (q *Queries) ChannelCreate(ctx context.Context, arg ChannelCreateParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelCreate,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Type,
		arg.LastMessageID,
		arg.Name,
		arg.IconUrl,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.LastMessageID,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelDelete = `-- name: ChannelDelete :exec
DELETE FROM channels
WHERE id = $1::uuid
`

func (q *Queries) ChannelDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, channelDelete, id)
	return err
}

const channelGet = `-- name: ChannelGet :one
SELECT
    id, created_at, updated_at, type, last_message_id, name, icon_url
FROM
    channels
WHERE
    id = $1::uuid
`

func (q *Queries) ChannelGet(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, channelGet, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.LastMessageID,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelGetForMember = `-- name: ChannelGetForMember :one
SELECT
    c.id, c.created_at, c.updated_at, c.type, c.last_message_id, c.name, c.icon_url
FROM
    channels c
    INNER JOIN channel_members cm ON cm.channel_id = c.id
WHERE
    c.id = $1::uuid
    AND cm.user_id = $2::uuid
`

type ChannelGetForMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelGetForMember(ctx context.Context, arg ChannelGetForMemberParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelGetForMember, arg.ChannelID, arg.UserID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.LastMessageID,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelGetForMemberUpdate = `-- name: ChannelGetForMemberUpdate :one
SELECT
    c.id, c.created_at, c.updated_at, c.type, c.last_message_id, c.name, c.icon_url
FROM
    channels c
    INNER JOIN channel_members cm ON cm.channel_id = c.id
WHERE
    c.id = $1::uuid
    AND cm.user_id = $2::uuid
FOR UPDATE
    OF c
`

type ChannelGetForMemberUpdateParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelGetForMemberUpdate(ctx context.Context, arg ChannelGetForMemberUpdateParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelGetForMemberUpdate, arg.ChannelID, arg.UserID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.LastMessageID,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelHasMessagesAfter = `-- name: ChannelHasMessagesAfter :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            messages
        WHERE
            channel_id = $1::uuid
            AND (created_at > $2::timestamptz
                OR (created_at = $2::timestamptz
                    AND id > $3::uuid)))
`

type ChannelHasMessagesAfterParams struct {
	ChannelID pgtype.UUID        `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MessageID pgtype.UUID        `json:"message_id"`
}

func (q *Queries) ChannelHasMessagesAfter(ctx context.Context, arg ChannelHasMessagesAfterParams) (bool, error) {
	row := q.db.QueryRow(ctx, channelHasMessagesAfter, arg.ChannelID, arg.CreatedAt, arg.MessageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelHasMessagesBefore = `-- name: ChannelHasMessagesBefore :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            messages
        WHERE
            channel_id = $1::uuid
            AND (created_at < $2::timestamptz
                OR (created_at = $2::timestamptz
                    AND id < $3::uuid)))
`

type ChannelHasMessagesBeforeParams struct {
	ChannelID pgtype.UUID        `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MessageID pgtype.UUID        `json:"message_id"`
}

func (q *Queries) ChannelHasMessagesBefore(ctx context.Context, arg ChannelHasMessagesBeforeParams) (bool, error) {
	row := q.db.QueryRow(ctx, channelHasMessagesBefore, arg.ChannelID, arg.CreatedAt, arg.MessageID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelMemberAddBatch = `-- name: ChannelMemberAddBatch :exec
INSERT INTO channel_members(channel_id, user_id, created_at, updated_at, last_read_at, mention_count, last_read_message_id)
SELECT
    $1::uuid,
    u.user_id,
    u.created_at,
    u.updated_at,
    u.last_read_at,
    u.mention_count,
    u.last_read_message_id
FROM
    ROWS
FROM (unnest($2::uuid[]),
    unnest($3::timestamptz[]),
    unnest($4::timestamptz[]),
    unnest($5::timestamptz[]),
    unnest($6::int[]),
    unnest($7::uuid[])) AS u(user_id,
        created_at,
        updated_at,
        last_read_at,
        mention_count,
        last_read_message_id)
ON CONFLICT (channel_id,
    user_id)
    DO UPDATE SET
        updated_at = EXCLUDED.updated_at,
        last_read_at = EXCLUDED.last_read_at,
        mention_count = EXCLUDED.mention_count,
        last_read_message_id = EXCLUDED.last_read_message_id
`

type ChannelMemberAddBatchParams struct {
	ChannelID          pgtype.UUID          `json:"channel_id"`
	UserIds            []pgtype.UUID        `json:"user_ids"`
	CreatedAts         []pgtype.Timestamptz `json:"created_ats"`
	UpdatedAts         []pgtype.Timestamptz `json:"updated_ats"`
	LastReadAts        []pgtype.Timestamptz `json:"last_read_ats"`
	MentionCounts      []int32              `json:"mention_counts"`
	LastReadMessageIds []pgtype.UUID        `json:"last_read_message_ids"`
}

// ============================================================================
// CHANNEL MEMBERS
// ============================================================================
func (q *Queries) ChannelMemberAddBatch(ctx context.Context, arg ChannelMemberAddBatchParams) error {
	_, err := q.db.Exec(ctx, channelMemberAddBatch,
		arg.ChannelID,
		arg.UserIds,
		arg.CreatedAts,
		arg.UpdatedAts,
		arg.LastReadAts,
		arg.MentionCounts,
		arg.LastReadMessageIds,
	)
	return err
}

const channelMemberCount = `-- name: ChannelMemberCount :one
SELECT
    COUNT(*)::int AS count
FROM
    channel_members
WHERE
    channel_id = $1::uuid
`

func (q *Queries) ChannelMemberCount(ctx context.Context, channelID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, channelMemberCount, channelID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const channelMemberGet = `-- name: ChannelMemberGet :one
SELECT
    channel_id, user_id, created_at, updated_at, last_read_at, mention_count, last_read_message_id
FROM
    channel_members
WHERE
    channel_id = $1::uuid
    AND user_id = $2::uuid
`

type ChannelMemberGetParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelMemberGet(ctx context.Context, arg ChannelMemberGetParams) (ChannelMember, error) {
	row := q.db.QueryRow(ctx, channelMemberGet, arg.ChannelID, arg.UserID)
	var i ChannelMember
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastReadAt,
		&i.MentionCount,
		&i.LastReadMessageID,
	)
	return i, err
}

const channelMemberGetUnreadCount = `-- name: ChannelMemberGetUnreadCount :one
SELECT
    COUNT(*)::int AS unread_count
FROM
    messages m
    JOIN channel_members cm ON cm.channel_id = m.channel_id
        AND cm.user_id = $1::uuid
WHERE
    m.channel_id = $2::uuid
    AND m.created_at > cm.last_read_at
`

type ChannelMemberGetUnreadCountParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

func (q *Queries) ChannelMemberGetUnreadCount(ctx context.Context, arg ChannelMemberGetUnreadCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, channelMemberGetUnreadCount, arg.UserID, arg.ChannelID)
	var unread_count int32
	err := row.Scan(&unread_count)
	return unread_count, err
}

const channelMemberIncrementMentionCountBatch = `-- name: ChannelMemberIncrementMentionCountBatch :exec
UPDATE
    channel_members
SET
    mention_count = mention_count + 1,
    updated_at = CURRENT_TIMESTAMP
WHERE
    channel_id = $1::uuid
    AND user_id = ANY ($2::uuid[])
`

type ChannelMemberIncrementMentionCountBatchParams struct {
	ChannelID pgtype.UUID   `json:"channel_id"`
	UserIds   []pgtype.UUID `json:"user_ids"`
}

func (q *Queries) ChannelMemberIncrementMentionCountBatch(ctx context.Context, arg ChannelMemberIncrementMentionCountBatchParams) error {
	_, err := q.db.Exec(ctx, channelMemberIncrementMentionCountBatch, arg.ChannelID, arg.UserIds)
	return err
}

const channelMemberListByChannel = `-- name: ChannelMemberListByChannel :many
SELECT
    channel_id,
    user_id,
    created_at,
    updated_at,
    last_read_at,
    mention_count,
    last_read_message_id
FROM
    channel_members
WHERE
    channel_id = $1::uuid
ORDER BY
    created_at ASC,
    user_id ASC
`

func (q *Queries) ChannelMemberListByChannel(ctx context.Context, channelID pgtype.UUID) ([]ChannelMember, error) {
	rows, err := q.db.Query(ctx, channelMemberListByChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMember
	for rows.Next() {
		var i ChannelMember
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastReadAt,
			&i.MentionCount,
			&i.LastReadMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelMemberListItemsByChannel = `-- name: ChannelMemberListItemsByChannel :many
SELECT
    cm.channel_id,
    cm.user_id,
    cm.created_at AS member_since,
    cm.last_read_at,
    ua.username,
    ua.display_name,
    ua.avatar_url,
    ua.created_at AS user_created_at
FROM
    channel_members cm
    JOIN user_aggregates ua ON ua.id = cm.user_id
WHERE
    cm.channel_id = $1::uuid
    AND ($2::timestamptz IS NULL
        OR (cm.created_at,
            cm.user_id) >($2::timestamptz,
            $3::uuid))
ORDER BY
    cm.created_at ASC,
    cm.user_id ASC
LIMIT $4::int
`

type ChannelMemberListItemsByChannelParams struct {
	ChannelID       pgtype.UUID        `json:"channel_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorUserID    pgtype.UUID        `json:"cursor_user_id"`
	LimitVal        int32              `json:"limit_val"`
}

type ChannelMemberListItemsByChannelRow struct {
	ChannelID     pgtype.UUID        `json:"channel_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	MemberSince   pgtype.Timestamptz `json:"member_since"`
	LastReadAt    pgtype.Timestamptz `json:"last_read_at"`
	Username      string             `json:"username"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	UserCreatedAt pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) ChannelMemberListItemsByChannel(ctx context.Context, arg ChannelMemberListItemsByChannelParams) ([]ChannelMemberListItemsByChannelRow, error) {
	rows, err := q.db.Query(ctx, channelMemberListItemsByChannel,
		arg.ChannelID,
		arg.CursorCreatedAt,
		arg.CursorUserID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMemberListItemsByChannelRow
	for rows.Next() {
		var i ChannelMemberListItemsByChannelRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.UserID,
			&i.MemberSince,
			&i.LastReadAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.UserCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelMemberRemove = `-- name: ChannelMemberRemove :exec
DELETE FROM channel_members
WHERE channel_id = $1::uuid
    AND user_id = $2::uuid
`

type ChannelMemberRemoveParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelMemberRemove(ctx context.Context, arg ChannelMemberRemoveParams) error {
	_, err := q.db.Exec(ctx, channelMemberRemove, arg.ChannelID, arg.UserID)
	return err
}

const channelMemberResetMentionCount = `-- name: ChannelMemberResetMentionCount :exec
UPDATE
    channel_members
SET
    mention_count = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE
    channel_id = $1::uuid
    AND user_id = $2::uuid
`

type ChannelMemberResetMentionCountParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ChannelMemberResetMentionCount(ctx context.Context, arg ChannelMemberResetMentionCountParams) error {
	_, err := q.db.Exec(ctx, channelMemberResetMentionCount, arg.ChannelID, arg.UserID)
	return err
}

const channelMemberUpdateLastRead = `-- name: ChannelMemberUpdateLastRead :exec
UPDATE
    channel_members
SET
    last_read_message_id = CASE WHEN $1::timestamptz > last_read_at THEN
        COALESCE($2::uuid, last_read_message_id)
    ELSE
        last_read_message_id
    END,
    last_read_at = GREATEST(last_read_at, $1::timestamptz),
    updated_at = CURRENT_TIMESTAMP
WHERE
    channel_id = $3::uuid
    AND user_id = $4::uuid
`

type ChannelMemberUpdateLastReadParams struct {
	LastReadAt        pgtype.Timestamptz `json:"last_read_at"`
	LastReadMessageID pgtype.UUID        `json:"last_read_message_id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	UserID            pgtype.UUID        `json:"user_id"`
}

func (q *Queries) ChannelMemberUpdateLastRead(ctx context.Context, arg ChannelMemberUpdateLastReadParams) error {
	_, err := q.db.Exec(ctx, channelMemberUpdateLastRead,
		arg.LastReadAt,
		arg.LastReadMessageID,
		arg.ChannelID,
		arg.UserID,
	)
	return err
}

const channelUpdate = `-- name: ChannelUpdate :one
UPDATE
    channels
SET
    name = COALESCE($1::text, name),
    icon_url = COALESCE($2::text, icon_url),
    updated_at = $3::timestamptz
WHERE
    id = $4::uuid
RETURNING
    id, created_at, updated_at, type, last_message_id, name, icon_url
`

type ChannelUpdateParams struct {
	Name      pgtype.Text        `json:"name"`
	IconUrl   pgtype.Text        `json:"icon_url"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

// -- name: ChannelListByUser :many
// -- Used for populating the user's sidebar with channel info & peer profiles for DMs
// SELECT
//
//	-- 1. Primary Identifiers & References
//	cm.channel_id,
//	cm.user_id,
//	rp.peer_id AS peer_user_id,
//	c.type AS channel_type,
//	-- 2. Display & Metadata (Resolved for 1:1 DMs or Group DMs)
//	COALESCE(c.name, rp.display_name, rp.username) AS channel_name,
//	COALESCE(c.icon_url, rp.avatar_url) AS channel_icon_url,
//	-- 3. Read State, Activity & Metrics
//	c.last_message_id AS channel_last_message_id,
//	cm.last_read_message_id,
//	cm.mention_count,
//	-- 4. Timestamps
//	cm.created_at,
//	cm.last_read_at,
//	c.updated_at AS channel_updated_at
//
// FROM
//
//	channel_members cm
//	JOIN channels c ON cm.channel_id = c.id
//	-- Join relationship_perspectives ONLY for 1:1 DMs to resolve peer profile
//	LEFT JOIN relationship_perspectives rp ON c.type = 0
//	    AND rp.user_id = cm.user_id
//	    AND rp.channel_id = c.id
//
// WHERE
//
//	cm.user_id = @user_id::uuid
//
// ORDER BY
//
//	c.updated_at DESC,
//	c.id ASC;
func (q *Queries) ChannelUpdate(ctx context.Context, arg ChannelUpdateParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelUpdate,
		arg.Name,
		arg.IconUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.LastMessageID,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const channelUpdateLastMessage = `-- name: ChannelUpdateLastMessage :one
UPDATE
    channels
SET
    last_message_id = $1::uuid,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
    AND updated_at <= $2::timestamptz
RETURNING
    id, created_at, updated_at, type, last_message_id, name, icon_url
`

type ChannelUpdateLastMessageParams struct {
	LastMessageID pgtype.UUID        `json:"last_message_id"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ChannelID     pgtype.UUID        `json:"channel_id"`
}

func (q *Queries) ChannelUpdateLastMessage(ctx context.Context, arg ChannelUpdateLastMessageParams) (Channel, error) {
	row := q.db.QueryRow(ctx, channelUpdateLastMessage, arg.LastMessageID, arg.UpdatedAt, arg.ChannelID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.LastMessageID,
		&i.Name,
		&i.IconUrl,
	)
	return i, err
}

const messageCreate = `-- name: MessageCreate :one
INSERT INTO messages(id, channel_id, reply_to_message_id, author_id, created_at, updated_at, edited_at, is_pinned, content)
    VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5::timestamptz, $6::timestamptz, $7::timestamptz, $8::boolean, $9::text)
RETURNING
    id, channel_id, reply_to_message_id, author_id, created_at, updated_at, edited_at, is_pinned, content
`

type MessageCreateParams struct {
	ID               pgtype.UUID        `json:"id"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	ReplyToMessageID pgtype.UUID        `json:"reply_to_message_id"`
	AuthorID         pgtype.UUID        `json:"author_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EditedAt         pgtype.Timestamptz `json:"edited_at"`
	IsPinned         bool               `json:"is_pinned"`
	Content          pgtype.Text        `json:"content"`
}

// ============================================================================
// MESSAGES
// ============================================================================
func (q *Queries) MessageCreate(ctx context.Context, arg MessageCreateParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageCreate,
		arg.ID,
		arg.ChannelID,
		arg.ReplyToMessageID,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.EditedAt,
		arg.IsPinned,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ReplyToMessageID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
	)
	return i, err
}

const messageDelete = `-- name: MessageDelete :exec
DELETE FROM messages
WHERE id = $1::uuid
`

func (q *Queries) MessageDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, messageDelete, id)
	return err
}

const messageGetAggregate = `-- name: MessageGetAggregate :one
SELECT
    mb.id,
    mb.channel_id,
    mb.reply_to_message_id,
    mb.author_id,
    mb.author_username,
    mb.author_display_name,
    mb.author_avatar_url,
    mb.created_at,
    mb.updated_at,
    mb.edited_at,
    mb.is_pinned,
    mb.content,
    COALESCE(att.attachments, '[]'::json) AS attachments,
    COALESCE(rec.reactions, '[]'::json) AS reactions
FROM
    message_base_aggregates mb
    LEFT JOIN LATERAL (
        SELECT
            json_agg(json_build_object('id', a.id, 'file_name', a.file_name, 'file_size', a.file_size, 'content_type', a.content_type, 'url', a.url, 'width', a.width, 'height', a.height, 'created_at', a.created_at)
            ORDER BY a.created_at ASC) FILTER (WHERE a.id IS NOT NULL) AS attachments
        FROM
            message_attachments a
        WHERE
            a.message_id = mb.id) att ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            json_agg(json_build_object('message_id', r.message_id, 'user_id', r.user_id, 'emoji', r.emoji, 'created_at', r.created_at)
            ORDER BY r.created_at ASC) FILTER (WHERE r.message_id IS NOT NULL) AS reactions
        FROM
            message_reactions r
        WHERE
            r.message_id = mb.id) rec ON TRUE
WHERE
    mb.id = $1::uuid
`

type MessageGetAggregateRow struct {
	ID                pgtype.UUID        `json:"id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	ReplyToMessageID  pgtype.UUID        `json:"reply_to_message_id"`
	AuthorID          pgtype.UUID        `json:"author_id"`
	AuthorUsername    pgtype.Text        `json:"author_username"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `json:"author_avatar_url"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	IsPinned          bool               `json:"is_pinned"`
	Content           pgtype.Text        `json:"content"`
	Attachments       []byte             `json:"attachments"`
	Reactions         []byte             `json:"reactions"`
}

func (q *Queries) MessageGetAggregate(ctx context.Context, id pgtype.UUID) (MessageGetAggregateRow, error) {
	row := q.db.QueryRow(ctx, messageGetAggregate, id)
	var i MessageGetAggregateRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ReplyToMessageID,
		&i.AuthorID,
		&i.AuthorUsername,
		&i.AuthorDisplayName,
		&i.AuthorAvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
		&i.Attachments,
		&i.Reactions,
	)
	return i, err
}

const messageGetFirstUnread = `-- name: MessageGetFirstUnread :one
SELECT
    m.id, m.channel_id, m.reply_to_message_id, m.author_id, m.created_at, m.updated_at, m.edited_at, m.is_pinned, m.content
FROM
    messages m
    JOIN channel_members cm ON cm.channel_id = m.channel_id
        AND cm.user_id = $1::uuid
WHERE
    m.channel_id = $2::uuid
    AND m.created_at > cm.last_read_at
ORDER BY
    m.created_at ASC,
    m.id ASC
LIMIT 1
`

type MessageGetFirstUnreadParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

// Fetches the first message created after the user's last_read_at timestamp
func (q *Queries) MessageGetFirstUnread(ctx context.Context, arg MessageGetFirstUnreadParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageGetFirstUnread, arg.UserID, arg.ChannelID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ReplyToMessageID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
	)
	return i, err
}

const messageGetLatest = `-- name: MessageGetLatest :one
SELECT
    id, channel_id, reply_to_message_id, author_id, created_at, updated_at, edited_at, is_pinned, content
FROM
    messages
WHERE
    channel_id = $1::uuid
ORDER BY
    created_at DESC,
    id DESC
LIMIT 1
`

func (q *Queries) MessageGetLatest(ctx context.Context, channelID pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, messageGetLatest, channelID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ReplyToMessageID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
	)
	return i, err
}

const messageListAggregateByChannel = `-- name: MessageListAggregateByChannel :many
SELECT
    mb.id,
    mb.channel_id,
    mb.reply_to_message_id,
    mb.author_id,
    mb.author_username,
    mb.author_display_name,
    mb.author_avatar_url,
    mb.created_at,
    mb.updated_at,
    mb.edited_at,
    mb.is_pinned,
    mb.content,
    COALESCE(att.attachments, '[]'::json) AS attachments,
    COALESCE(rec.reactions, '[]'::json) AS reactions
FROM
    message_base_aggregates mb
    LEFT JOIN LATERAL (
        SELECT
            json_agg(json_build_object('id', a.id, 'file_name', a.file_name, 'file_size', a.file_size, 'content_type', a.content_type, 'url', a.url, 'width', a.width, 'height', a.height, 'created_at', a.created_at)
            ORDER BY a.created_at ASC) FILTER (WHERE a.id IS NOT NULL) AS attachments
        FROM
            message_attachments a
        WHERE
            a.message_id = mb.id) att ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            json_agg(json_build_object('message_id', r.message_id, 'user_id', r.user_id, 'emoji', r.emoji, 'created_at', r.created_at)
            ORDER BY r.created_at ASC) FILTER (WHERE r.message_id IS NOT NULL) AS reactions
        FROM
            message_reactions r
        WHERE
            r.message_id = mb.id) rec ON TRUE
WHERE
    mb.channel_id = $1::uuid
    AND ($2::timestamptz IS NULL
        OR (mb.created_at,
            mb.id) <($2::timestamptz,
            $3::uuid))
ORDER BY
    mb.created_at DESC,
    mb.id DESC
LIMIT $4::int
`

type MessageListAggregateByChannelParams struct {
	ChannelID       pgtype.UUID        `json:"channel_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	LimitVal        int32              `json:"limit_val"`
}

type MessageListAggregateByChannelRow struct {
	ID                pgtype.UUID        `json:"id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	ReplyToMessageID  pgtype.UUID        `json:"reply_to_message_id"`
	AuthorID          pgtype.UUID        `json:"author_id"`
	AuthorUsername    pgtype.Text        `json:"author_username"`
	AuthorDisplayName pgtype.Text        `json:"author_display_name"`
	AuthorAvatarUrl   pgtype.Text        `json:"author_avatar_url"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	IsPinned          bool               `json:"is_pinned"`
	Content           pgtype.Text        `json:"content"`
	Attachments       []byte             `json:"attachments"`
	Reactions         []byte             `json:"reactions"`
}

func (q *Queries) MessageListAggregateByChannel(ctx context.Context, arg MessageListAggregateByChannelParams) ([]MessageListAggregateByChannelRow, error) {
	rows, err := q.db.Query(ctx, messageListAggregateByChannel,
		arg.ChannelID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageListAggregateByChannelRow
	for rows.Next() {
		var i MessageListAggregateByChannelRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ReplyToMessageID,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.IsPinned,
			&i.Content,
			&i.Attachments,
			&i.Reactions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageSetPinned = `-- name: MessageSetPinned :one
UPDATE
    messages
SET
    is_pinned = $1::boolean,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
RETURNING
    id, channel_id, reply_to_message_id, author_id, created_at, updated_at, edited_at, is_pinned, content
`

type MessageSetPinnedParams struct {
	IsPinned  bool               `json:"is_pinned"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

// -- name: MessageListByChannelAfter :many
// -- Fetches newer messages using keyset pagination.
// SELECT
//
//	*
//
// FROM
//
//	messages
//
// WHERE
//
//	channel_id = @channel_id::uuid
//	AND (sqlc.narg('cursor_created_at')::timestamptz IS NULL
//	    OR (created_at,
//	        id) >(sqlc.narg('cursor_created_at')::timestamptz,
//	        sqlc.narg('cursor_id')::uuid))
//
// ORDER BY
//
//	created_at ASC,
//	id ASC
//
// LIMIT @result_limit::int;
// -- name: MessageListByChannelAround :many
// WITH around_window AS ((
//
//	SELECT
//	    m1.*
//	FROM
//	    messages m1
//	WHERE
//	    m1.channel_id = @channel_id::uuid
//	    AND (m1.created_at,
//	        m1.id) <=(@cursor_created_at::timestamptz,
//	        @cursor_id::uuid)
//	ORDER BY
//	    m1.created_at DESC,
//	    m1.id DESC
//	LIMIT @older_limit::int)
//
// UNION ALL (
//
//	SELECT
//	    m2.*
//	FROM
//	    messages m2
//	WHERE
//	    m2.channel_id = @channel_id::uuid
//	    AND (m2.created_at,
//	        m2.id) >(@cursor_created_at::timestamptz,
//	        @cursor_id::uuid)
//	ORDER BY
//	    m2.created_at ASC,
//	    m2.id ASC
//	LIMIT @newer_limit::int))
//
// SELECT
//
//	m.*
//
// FROM
//
//	around_window aw
//	JOIN messages m ON m.id = aw.id
//
// ORDER BY
//
//	aw.created_at ASC,
//	aw.id ASC;
//
// -- name: MessageListByChannelBefore :many
// -- Fetches older messages using keyset pagination.
// SELECT
//
//	*
//
// FROM
//
//	messages
//
// WHERE
//
//	channel_id = @channel_id::uuid
//	AND (sqlc.narg('cursor_created_at')::timestamptz IS NULL
//	    OR (created_at,
//	        id) <(sqlc.narg('cursor_created_at')::timestamptz,
//	        sqlc.narg('cursor_id')::uuid))
//
// ORDER BY
//
//	created_at DESC,
//	id DESC
//
// LIMIT @result_limit::int;
// TODO: ADD LIMIT
// -- name: MessageListPinnedByChannel :many
// SELECT
//
//	*
//
// FROM
//
//	messages
//
// WHERE
//
//	channel_id = @channel_id::uuid
//	AND is_pinned = TRUE
//
// ORDER BY
//
//	created_at DESC,
//	id DESC;
func (q *Queries) MessageSetPinned(ctx context.Context, arg MessageSetPinnedParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageSetPinned, arg.IsPinned, arg.UpdatedAt, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ReplyToMessageID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
	)
	return i, err
}

const messageUpdateContent = `-- name: MessageUpdateContent :one
UPDATE
    messages
SET
    content = $1::text,
    updated_at = $2::timestamptz,
    edited_at = $3::timestamptz
WHERE
    id = $4::uuid
RETURNING
    id, channel_id, reply_to_message_id, author_id, created_at, updated_at, edited_at, is_pinned, content
`

type MessageUpdateContentParams struct {
	Content   pgtype.Text        `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) MessageUpdateContent(ctx context.Context, arg MessageUpdateContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, messageUpdateContent,
		arg.Content,
		arg.UpdatedAt,
		arg.EditedAt,
		arg.ID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ReplyToMessageID,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.IsPinned,
		&i.Content,
	)
	return i, err
}

const outboxEventAcquireBatch = `-- name: OutboxEventAcquireBatch :many
UPDATE
    outbox_events
SET
    locked_by = $1::uuid,
    lease_expires_at = CURRENT_TIMESTAMP + make_interval(secs => $2::int),
    updated_at = CURRENT_TIMESTAMP
WHERE
    id IN (
        SELECT
            id
        FROM
            outbox_events
        WHERE
            processed_at IS NULL
            AND attempts < max_attempts
            AND next_attempt_at <= CURRENT_TIMESTAMP
            AND (lease_expires_at IS NULL
                OR lease_expires_at < CURRENT_TIMESTAMP)
        ORDER BY
            next_attempt_at ASC,
            id ASC
        LIMIT $3::int
        FOR UPDATE
            SKIP LOCKED)
RETURNING
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
`

type OutboxEventAcquireBatchParams struct {
	WorkerID             pgtype.UUID `json:"worker_id"`
	LeaseDurationSeconds int32       `json:"lease_duration_seconds"`
	BatchSize            int32       `json:"batch_size"`
}

func (q *Queries) OutboxEventAcquireBatch(ctx context.Context, arg OutboxEventAcquireBatchParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, outboxEventAcquireBatch, arg.WorkerID, arg.LeaseDurationSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.LockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
			&i.LeaseExpiresAt,
			&i.ProcessedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.EventType,
			&i.Payload,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxEventCreate = `-- name: OutboxEventCreate :one
INSERT INTO outbox_events(id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, last_error, payload)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
`

type OutboxEventCreateParams struct {
	ID             pgtype.UUID        `json:"id"`
	LockedBy       pgtype.UUID        `json:"locked_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	EventType      string             `json:"event_type"`
	LastError      pgtype.Text        `json:"last_error"`
	Payload        []byte             `json:"payload"`
}

func (q *Queries) OutboxEventCreate(ctx context.Context, arg OutboxEventCreateParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, outboxEventCreate,
		arg.ID,
		arg.LockedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.NextAttemptAt,
		arg.LeaseExpiresAt,
		arg.ProcessedAt,
		arg.Attempts,
		arg.MaxAttempts,
		arg.EventType,
		arg.LastError,
		arg.Payload,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
		&i.LeaseExpiresAt,
		&i.ProcessedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.EventType,
		&i.Payload,
		&i.LastError,
	)
	return i, err
}

const outboxEventDelete = `-- name: OutboxEventDelete :exec
DELETE FROM outbox_events
WHERE id = $1
`

func (q *Queries) OutboxEventDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, outboxEventDelete, id)
	return err
}

const outboxEventGet = `-- name: OutboxEventGet :one
SELECT
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
FROM
    outbox_events
WHERE
    id = $1
`

func (q *Queries) OutboxEventGet(ctx context.Context, id pgtype.UUID) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, outboxEventGet, id)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
		&i.LeaseExpiresAt,
		&i.ProcessedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.EventType,
		&i.Payload,
		&i.LastError,
	)
	return i, err
}

const outboxEventList = `-- name: OutboxEventList :many
SELECT
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
FROM
    outbox_events
WHERE ($1::uuid IS NULL
    OR id < $1)
ORDER BY
    id DESC
LIMIT $2
`

type OutboxEventListParams struct {
	CursorID    pgtype.UUID `json:"cursor_id"`
	ResultLimit int32       `json:"result_limit"`
}

func (q *Queries) OutboxEventList(ctx context.Context, arg OutboxEventListParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, outboxEventList, arg.CursorID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.LockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NextAttemptAt,
			&i.LeaseExpiresAt,
			&i.ProcessedAt,
			&i.Attempts,
			&i.MaxAttempts,
			&i.EventType,
			&i.Payload,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outboxEventPurgeProcessed = `-- name: OutboxEventPurgeProcessed :exec
DELETE FROM outbox_events
WHERE processed_at <(CURRENT_TIMESTAMP - make_interval(days => $1::int))
`

func (q *Queries) OutboxEventPurgeProcessed(ctx context.Context, retentionDays int32) error {
	_, err := q.db.Exec(ctx, outboxEventPurgeProcessed, retentionDays)
	return err
}

const outboxEventRenewLease = `-- name: OutboxEventRenewLease :exec
UPDATE
    outbox_events
SET
    lease_expires_at = CURRENT_TIMESTAMP + make_interval(secs => $1::int),
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $2::uuid
    AND locked_by = $3::uuid
    AND processed_at IS NULL
`

type OutboxEventRenewLeaseParams struct {
	LeaseDurationSeconds int32       `json:"lease_duration_seconds"`
	ID                   pgtype.UUID `json:"id"`
	WorkerID             pgtype.UUID `json:"worker_id"`
}

func (q *Queries) OutboxEventRenewLease(ctx context.Context, arg OutboxEventRenewLeaseParams) error {
	_, err := q.db.Exec(ctx, outboxEventRenewLease, arg.LeaseDurationSeconds, arg.ID, arg.WorkerID)
	return err
}

const outboxEventUpdate = `-- name: OutboxEventUpdate :one
UPDATE
    outbox_events
SET
    locked_by = $1,
    lease_expires_at = $2,
    processed_at = $3,
    attempts = $4,
    max_attempts = $5,
    next_attempt_at = $6,
    last_error = $7,
    updated_at = $8
WHERE
    id = $9
RETURNING
    id, locked_by, created_at, updated_at, next_attempt_at, lease_expires_at, processed_at, attempts, max_attempts, event_type, payload, last_error
`

type OutboxEventUpdateParams struct {
	LockedBy       pgtype.UUID        `json:"locked_by"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	LastError      pgtype.Text        `json:"last_error"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) OutboxEventUpdate(ctx context.Context, arg OutboxEventUpdateParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, outboxEventUpdate,
		arg.LockedBy,
		arg.LeaseExpiresAt,
		arg.ProcessedAt,
		arg.Attempts,
		arg.MaxAttempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextAttemptAt,
		&i.LeaseExpiresAt,
		&i.ProcessedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.EventType,
		&i.Payload,
		&i.LastError,
	)
	return i, err
}

const reactionAdd = `-- name: ReactionAdd :one
INSERT INTO message_reactions(message_id, user_id, emoji)
    VALUES ($1, $2, $3)
ON CONFLICT (message_id, user_id, emoji)
    DO UPDATE SET
        emoji = EXCLUDED.emoji
    RETURNING
        message_id, user_id, created_at, emoji
`

type ReactionAddParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

// ============================================================================
// MESSAGE REACTIONS
// ============================================================================
func (q *Queries) ReactionAdd(ctx context.Context, arg ReactionAddParams) (MessageReaction, error) {
	row := q.db.QueryRow(ctx, reactionAdd, arg.MessageID, arg.UserID, arg.Emoji)
	var i MessageReaction
	err := row.Scan(
		&i.MessageID,
		&i.UserID,
		&i.CreatedAt,
		&i.Emoji,
	)
	return i, err
}

const reactionRemove = `-- name: ReactionRemove :exec
DELETE FROM message_reactions
WHERE message_id = $1
    AND user_id = $2
    AND emoji = $3
`

type ReactionRemoveParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) ReactionRemove(ctx context.Context, arg ReactionRemoveParams) error {
	_, err := q.db.Exec(ctx, reactionRemove, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const relationshipDelete = `-- name: RelationshipDelete :exec
DELETE FROM relationships
WHERE user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
`

type RelationshipDeleteParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

// ============================================================================
// RELATIONSHIPS
// ============================================================================
func (q *Queries) RelationshipDelete(ctx context.Context, arg RelationshipDeleteParams) error {
	_, err := q.db.Exec(ctx, relationshipDelete, arg.User1ID, arg.User2ID)
	return err
}

const relationshipDeleteVerified = `-- name: RelationshipDeleteVerified :exec
DELETE FROM relationships
WHERE user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
    AND (variant != 3 -- 3 = Blocked
        OR actor_id = $3::uuid)
`

type RelationshipDeleteVerifiedParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
	ActorID pgtype.UUID `json:"actor_id"`
}

func (q *Queries) RelationshipDeleteVerified(ctx context.Context, arg RelationshipDeleteVerifiedParams) error {
	_, err := q.db.Exec(ctx, relationshipDeleteVerified, arg.User1ID, arg.User2ID, arg.ActorID)
	return err
}

const relationshipGet = `-- name: RelationshipGet :one
SELECT
    user1_id, user2_id, actor_id, channel_id, created_at, updated_at, variant
FROM
    relationships
WHERE
    user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
`

type RelationshipGetParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

func (q *Queries) RelationshipGet(ctx context.Context, arg RelationshipGetParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipGet, arg.User1ID, arg.User2ID)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variant,
	)
	return i, err
}

const relationshipGetByChannelID = `-- name: RelationshipGetByChannelID :one
SELECT
    user1_id, user2_id, actor_id, channel_id, created_at, updated_at, variant
FROM
    relationships
WHERE
    channel_id = $1::uuid
`

func (q *Queries) RelationshipGetByChannelID(ctx context.Context, channelID pgtype.UUID) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipGetByChannelID, channelID)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variant,
	)
	return i, err
}

const relationshipGetForUpdate = `-- name: RelationshipGetForUpdate :one
SELECT
    user1_id, user2_id, actor_id, channel_id, created_at, updated_at, variant
FROM
    relationships
WHERE
    user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
FOR UPDATE
`

type RelationshipGetForUpdateParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

func (q *Queries) RelationshipGetForUpdate(ctx context.Context, arg RelationshipGetForUpdateParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipGetForUpdate, arg.User1ID, arg.User2ID)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variant,
	)
	return i, err
}

const relationshipHasBlockBetweenUserAndPeers = `-- name: RelationshipHasBlockBetweenUserAndPeers :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            relationships r
        WHERE
            r.variant = 3 -- Blocked
            AND (
                -- Case A: Primary user is user1_id, peer is user2_id
(r.user1_id = $1::uuid
                    AND r.user2_id = ANY ($2::uuid[]))
                OR
                -- Case B: Peer is user1_id, Primary user is user2_id
(r.user2_id = $1::uuid
                    AND r.user1_id = ANY ($2::uuid[]))))
`

type RelationshipHasBlockBetweenUserAndPeersParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	PeerIds []pgtype.UUID `json:"peer_ids"`
}

func (q *Queries) RelationshipHasBlockBetweenUserAndPeers(ctx context.Context, arg RelationshipHasBlockBetweenUserAndPeersParams) (bool, error) {
	row := q.db.QueryRow(ctx, relationshipHasBlockBetweenUserAndPeers, arg.UserID, arg.PeerIds)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const relationshipPerspectiveGet = `-- name: RelationshipPerspectiveGet :one
SELECT
    user_id, peer_id, variant, actor_id, is_initiator, channel_id, created_at, updated_at, username, display_name, avatar_url
FROM
    relationship_perspectives
WHERE
    user_id = $1::uuid
    AND peer_id = $2::uuid
`

type RelationshipPerspectiveGetParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PeerID pgtype.UUID `json:"peer_id"`
}

func (q *Queries) RelationshipPerspectiveGet(ctx context.Context, arg RelationshipPerspectiveGetParams) (RelationshipPerspective, error) {
	row := q.db.QueryRow(ctx, relationshipPerspectiveGet, arg.UserID, arg.PeerID)
	var i RelationshipPerspective
	err := row.Scan(
		&i.UserID,
		&i.PeerID,
		&i.Variant,
		&i.ActorID,
		&i.IsInitiator,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const relationshipPerspectiveGetByChannelID = `-- name: RelationshipPerspectiveGetByChannelID :one
SELECT
    user_id, peer_id, variant, actor_id, is_initiator, channel_id, created_at, updated_at, username, display_name, avatar_url
FROM
    relationship_perspectives
WHERE
    user_id = $1::uuid
    AND channel_id = $2::uuid
`

type RelationshipPerspectiveGetByChannelIDParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

func (q *Queries) RelationshipPerspectiveGetByChannelID(ctx context.Context, arg RelationshipPerspectiveGetByChannelIDParams) (RelationshipPerspective, error) {
	row := q.db.QueryRow(ctx, relationshipPerspectiveGetByChannelID, arg.UserID, arg.ChannelID)
	var i RelationshipPerspective
	err := row.Scan(
		&i.UserID,
		&i.PeerID,
		&i.Variant,
		&i.ActorID,
		&i.IsInitiator,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const relationshipUpsert = `-- name: RelationshipUpsert :one
INSERT INTO relationships(user1_id, user2_id, actor_id, channel_id, created_at, updated_at, variant)
    VALUES (LEAST($1::uuid, $2::uuid), GREATEST($1::uuid, $2::uuid), $3, $4::uuid, $5, $6, $7)
ON CONFLICT (user1_id, user2_id)
    DO UPDATE SET
        actor_id = EXCLUDED.actor_id,
        channel_id = CASE WHEN EXCLUDED.variant = 2 THEN
            COALESCE(EXCLUDED.channel_id, relationships.channel_id)
        ELSE
            NULL
        END,
        updated_at = EXCLUDED.updated_at,
        variant = EXCLUDED.variant
    RETURNING
        user1_id, user2_id, actor_id, channel_id, created_at, updated_at, variant
`

type RelationshipUpsertParams struct {
	User1ID   pgtype.UUID        `json:"user1_id"`
	User2ID   pgtype.UUID        `json:"user2_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Variant   int16              `json:"variant"`
}

// -- name: RelationshipPerspectivesList :many
// SELECT
//
//	*
//
// FROM
//
//	relationship_perspectives
//
// WHERE
//
//	user_id = @user_id::uuid
//	AND (sqlc.narg('filter_variant')::smallint IS NULL
//	    OR variant = sqlc.narg('filter_variant'))
//
// ORDER BY
//
//	updated_at DESC;
func (q *Queries) RelationshipUpsert(ctx context.Context, arg RelationshipUpsertParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipUpsert,
		arg.User1ID,
		arg.User2ID,
		arg.ActorID,
		arg.ChannelID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Variant,
	)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Variant,
	)
	return i, err
}

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions(id, user_id, refresh_token_hash, expires_at, revoked_at, client_ip, user_agent, os, browser, last_seen_at, created_at, updated_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
    id, user_id, last_seen_at, expires_at, revoked_at, created_at, updated_at, client_ip, refresh_token_hash, user_agent, os, browser
`

type SessionCreateParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ClientIP         netip.Addr         `json:"client_ip"`
	UserAgent        string             `json:"user_agent"`
	OS               string             `json:"os"`
	Browser          string             `json:"browser"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.ClientIP,
		arg.UserAgent,
		arg.OS,
		arg.Browser,
		arg.LastSeenAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.OS,
		&i.Browser,
	)
	return i, err
}

const sessionDelete = `-- name: SessionDelete :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) SessionDelete(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, sessionDelete, id)
	return err
}

const sessionDeleteAllByUserID = `-- name: SessionDeleteAllByUserID :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) SessionDeleteAllByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, sessionDeleteAllByUserID, userID)
	return err
}

const sessionDeleteAllExcept = `-- name: SessionDeleteAllExcept :exec
DELETE FROM sessions
WHERE user_id = $1
    AND id != $2
`

type SessionDeleteAllExceptParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SessionDeleteAllExcept(ctx context.Context, arg SessionDeleteAllExceptParams) error {
	_, err := q.db.Exec(ctx, sessionDeleteAllExcept, arg.UserID, arg.ID)
	return err
}

const sessionDeleteAllExpired = `-- name: SessionDeleteAllExpired :exec
DELETE FROM sessions
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) SessionDeleteAllExpired(ctx context.Context) error {
	_, err := q.db.Exec(ctx, sessionDeleteAllExpired)
	return err
}

const sessionGet = `-- name: SessionGet :one
SELECT
    id, user_id, last_seen_at, expires_at, revoked_at, created_at, updated_at, client_ip, refresh_token_hash, user_agent, os, browser
FROM
    sessions
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) SessionGet(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGet, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.OS,
		&i.Browser,
	)
	return i, err
}

const sessionSave = `-- name: SessionSave :one
UPDATE
    sessions
SET
    refresh_token_hash = $2,
    expires_at = $3,
    last_seen_at = $4,
    revoked_at = $5,
    updated_at = $6
WHERE
    id = $1
RETURNING
    id, user_id, last_seen_at, expires_at, revoked_at, created_at, updated_at, client_ip, refresh_token_hash, user_agent, os, browser
`

type SessionSaveParams struct {
	ID               pgtype.UUID        `json:"id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionSave(ctx context.Context, arg SessionSaveParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionSave,
		arg.ID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.OS,
		&i.Browser,
	)
	return i, err
}

const userCheckAvailability = `-- name: UserCheckAvailability :one
SELECT
    NOT EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            users.email = $1)::boolean AS email_available,
    NOT EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            users.username = $2)::boolean AS username_available
`

type UserCheckAvailabilityParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type UserCheckAvailabilityRow struct {
	EmailAvailable    pgtype.Bool `json:"email_available"`
	UsernameAvailable pgtype.Bool `json:"username_available"`
}

func (q *Queries) UserCheckAvailability(ctx context.Context, arg UserCheckAvailabilityParams) (UserCheckAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, userCheckAvailability, arg.Email, arg.Username)
	var i UserCheckAvailabilityRow
	err := row.Scan(&i.EmailAvailable, &i.UsernameAvailable)
	return i, err
}

const userCreateAggregate = `-- name: UserCreateAggregate :exec
WITH new_user AS (
INSERT INTO users(id, created_at, updated_at, verified_at, preferred_presence, email, username, password_hash)
        VALUES ($1, $6, $7, $8, $9, $10, $11, $12))
    INSERT INTO user_profiles(user_id, created_at, updated_at, display_name, avatar_url)
        VALUES ($1, $2, $3, $4, $5)
`

type UserCreateAggregateParams struct {
	UserID            pgtype.UUID        `json:"user_id"`
	ProfileCreatedAt  pgtype.Timestamptz `json:"profile_created_at"`
	ProfileUpdatedAt  pgtype.Timestamptz `json:"profile_updated_at"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	UserCreatedAt     pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt     pgtype.Timestamptz `json:"user_updated_at"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	PreferredPresence pgtype.Int2        `json:"preferred_presence"`
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	PasswordHash      string             `json:"password_hash"`
}

func (q *Queries) UserCreateAggregate(ctx context.Context, arg UserCreateAggregateParams) error {
	_, err := q.db.Exec(ctx, userCreateAggregate,
		arg.UserID,
		arg.ProfileCreatedAt,
		arg.ProfileUpdatedAt,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.UserCreatedAt,
		arg.UserUpdatedAt,
		arg.VerifiedAt,
		arg.PreferredPresence,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
	)
	return err
}

const userGet = `-- name: UserGet :one
SELECT
    id, email, username, password_hash, preferred_presence, verified_at, display_name, avatar_url, created_at, updated_at, profile_created_at, profile_updated_at
FROM
    user_aggregates
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) UserGet(ctx context.Context, id pgtype.UUID) (UserAggregate, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i UserAggregate
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PreferredPresence,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const userGetByEmail = `-- name: UserGetByEmail :one
SELECT
    id, email, username, password_hash, preferred_presence, verified_at, display_name, avatar_url, created_at, updated_at, profile_created_at, profile_updated_at
FROM
    user_aggregates
WHERE
    email = $1
LIMIT 1
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (UserAggregate, error) {
	row := q.db.QueryRow(ctx, userGetByEmail, email)
	var i UserAggregate
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PreferredPresence,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const userGetByUsername = `-- name: UserGetByUsername :one
SELECT
    id, email, username, password_hash, preferred_presence, verified_at, display_name, avatar_url, created_at, updated_at, profile_created_at, profile_updated_at
FROM
    user_aggregates
WHERE
    username = $1
LIMIT 1
`

func (q *Queries) UserGetByUsername(ctx context.Context, username string) (UserAggregate, error) {
	row := q.db.QueryRow(ctx, userGetByUsername, username)
	var i UserAggregate
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PreferredPresence,
		&i.VerifiedAt,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProfileCreatedAt,
		&i.ProfileUpdatedAt,
	)
	return i, err
}

const userProfileUpsert = `-- name: UserProfileUpsert :one
INSERT INTO user_profiles(user_id, created_at, updated_at, display_name, avatar_url)
    VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id)
    DO UPDATE SET
        display_name = EXCLUDED.display_name,
        avatar_url = EXCLUDED.avatar_url,
        updated_at = EXCLUDED.updated_at
    RETURNING
        user_id, created_at, updated_at, display_name, avatar_url
`

type UserProfileUpsertParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) UserProfileUpsert(ctx context.Context, arg UserProfileUpsertParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, userProfileUpsert,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const userUpdate = `-- name: UserUpdate :one
UPDATE
    users
SET
    email = $1,
    username = $2,
    password_hash = $3,
    preferred_presence = $4,
    verified_at = $5,
    updated_at = $6
WHERE
    id = $7
RETURNING
    id, created_at, updated_at, verified_at, preferred_presence, email, username, password_hash
`

type UserUpdateParams struct {
	Email             string             `json:"email"`
	Username          string             `json:"username"`
	PasswordHash      string             `json:"password_hash"`
	PreferredPresence pgtype.Int2        `json:"preferred_presence"`
	VerifiedAt        pgtype.Timestamptz `json:"verified_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID                pgtype.UUID        `json:"id"`
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, userUpdate,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.PreferredPresence,
		arg.VerifiedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.PreferredPresence,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
	)
	return i, err
}
