// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relationships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const relationshipDeleteVerified = `-- name: RelationshipDeleteVerified :exec
DELETE FROM relationships
WHERE user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
    AND (type != 3
        OR actor_id = $3::uuid)
`

type RelationshipDeleteVerifiedParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
	ActorID pgtype.UUID `json:"actor_id"`
}

func (q *Queries) RelationshipDeleteVerified(ctx context.Context, arg RelationshipDeleteVerifiedParams) error {
	_, err := q.db.Exec(ctx, relationshipDeleteVerified, arg.User1ID, arg.User2ID, arg.ActorID)
	return err
}

const relationshipGet = `-- name: RelationshipGet :one
SELECT
    user1_id,
    user2_id,
    actor_id,
    channel_id,
    created_at,
    updated_at,
    type
FROM
    relationships
WHERE
    user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
`

type RelationshipGetParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

func (q *Queries) RelationshipGet(ctx context.Context, arg RelationshipGetParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipGet, arg.User1ID, arg.User2ID)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const relationshipUpsert = `-- name: RelationshipUpsert :one
INSERT INTO relationships(user1_id, user2_id, actor_id, channel_id, created_at, updated_at, type)
    VALUES (LEAST($1::uuid, $2::uuid), GREATEST($1::uuid, $2::uuid), $3::uuid, $4::uuid, $5::timestamptz, $6::timestamptz, $7::smallint)
ON CONFLICT (user1_id, user2_id)
    DO UPDATE SET
        actor_id = EXCLUDED.actor_id,
        channel_id = CASE WHEN EXCLUDED.type = 2 THEN
            COALESCE(EXCLUDED.channel_id, relationships.channel_id)
        ELSE
            NULL
        END,
        updated_at = EXCLUDED.updated_at,
        type = EXCLUDED.type
    RETURNING
        user1_id,
        user2_id,
        actor_id,
        channel_id,
        created_at,
        updated_at,
        type
`

type RelationshipUpsertParams struct {
	User1ID   pgtype.UUID        `json:"user1_id"`
	User2ID   pgtype.UUID        `json:"user2_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Type      int16              `json:"type"`
}

func (q *Queries) RelationshipUpsert(ctx context.Context, arg RelationshipUpsertParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, relationshipUpsert,
		arg.User1ID,
		arg.User2ID,
		arg.ActorID,
		arg.ChannelID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Type,
	)
	var i Relationship
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}
