// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const relationDeleteByUser = `-- name: RelationDeleteByUser :exec
DELETE FROM relations
WHERE user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
    AND (type != 3
        OR actor_id = $3::uuid)
`

type RelationDeleteByUserParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
	ActorID pgtype.UUID `json:"actor_id"`
}

func (q *Queries) RelationDeleteByUser(ctx context.Context, arg RelationDeleteByUserParams) error {
	_, err := q.db.Exec(ctx, relationDeleteByUser, arg.User1ID, arg.User2ID, arg.ActorID)
	return err
}

const relationGet = `-- name: RelationGet :one
SELECT
    relations.user1_id, relations.user2_id, relations.actor_id, relations.channel_id, relations.created_at, relations.updated_at, relations.type
FROM
    relations
WHERE
    user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
`

type RelationGetParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

func (q *Queries) RelationGet(ctx context.Context, arg RelationGetParams) (Relation, error) {
	row := q.db.QueryRow(ctx, relationGet, arg.User1ID, arg.User2ID)
	var i Relation
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const relationGetByChannel = `-- name: RelationGetByChannel :one
SELECT
    relations.user1_id, relations.user2_id, relations.actor_id, relations.channel_id, relations.created_at, relations.updated_at, relations.type
FROM
    relations
WHERE
    channel_id = $1::uuid
`

func (q *Queries) RelationGetByChannel(ctx context.Context, channelID pgtype.UUID) (Relation, error) {
	row := q.db.QueryRow(ctx, relationGetByChannel, channelID)
	var i Relation
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const relationGetForUpdate = `-- name: RelationGetForUpdate :one
SELECT
    relations.user1_id, relations.user2_id, relations.actor_id, relations.channel_id, relations.created_at, relations.updated_at, relations.type
FROM
    relations
WHERE
    user1_id = LEAST($1::uuid, $2::uuid)
    AND user2_id = GREATEST($1::uuid, $2::uuid)
FOR UPDATE
`

type RelationGetForUpdateParams struct {
	User1ID pgtype.UUID `json:"user1_id"`
	User2ID pgtype.UUID `json:"user2_id"`
}

func (q *Queries) RelationGetForUpdate(ctx context.Context, arg RelationGetForUpdateParams) (Relation, error) {
	row := q.db.QueryRow(ctx, relationGetForUpdate, arg.User1ID, arg.User2ID)
	var i Relation
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const relationListTypeByUser = `-- name: RelationListTypeByUser :many
SELECT
    (
        CASE WHEN user1_id = $1::uuid THEN
            user2_id
        ELSE
            user1_id
        END)::uuid AS peer_id,
    actor_id,
    channel_id,
    created_at,
    updated_at,
    type
FROM
    relations
WHERE (user1_id = $1::uuid
    OR user2_id = $1::uuid)
AND type = $2::smallint
ORDER BY
    created_at DESC
LIMIT $3::int
`

type RelationListTypeByUserParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	TypeVal    int16       `json:"type_val"`
	BatchLimit int32       `json:"batch_limit"`
}

type RelationListTypeByUserRow struct {
	PeerID    pgtype.UUID        `json:"peer_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Type      int16              `json:"type"`
}

func (q *Queries) RelationListTypeByUser(ctx context.Context, arg RelationListTypeByUserParams) ([]RelationListTypeByUserRow, error) {
	rows, err := q.db.Query(ctx, relationListTypeByUser, arg.UserID, arg.TypeVal, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelationListTypeByUserRow
	for rows.Next() {
		var i RelationListTypeByUserRow
		if err := rows.Scan(
			&i.PeerID,
			&i.ActorID,
			&i.ChannelID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relationSave = `-- name: RelationSave :one
INSERT INTO relations(user1_id, user2_id, actor_id, channel_id, created_at, updated_at, type)
    VALUES (LEAST($1::uuid, $2::uuid), GREATEST($1::uuid, $2::uuid), $3::uuid, $4::uuid, $5::timestamptz, $6::timestamptz, $7::smallint)
ON CONFLICT (user1_id, user2_id)
    DO UPDATE SET
        actor_id = EXCLUDED.actor_id,
        channel_id = CASE WHEN EXCLUDED.type = 2 THEN
            COALESCE(EXCLUDED.channel_id, relations.channel_id)
        ELSE
            NULL
        END,
        updated_at = EXCLUDED.updated_at,
        type = EXCLUDED.type
    RETURNING
        relations.user1_id, relations.user2_id, relations.actor_id, relations.channel_id, relations.created_at, relations.updated_at, relations.type
`

type RelationSaveParams struct {
	User1ID   pgtype.UUID        `json:"user1_id"`
	User2ID   pgtype.UUID        `json:"user2_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Type      int16              `json:"type"`
}

func (q *Queries) RelationSave(ctx context.Context, arg RelationSaveParams) (Relation, error) {
	row := q.db.QueryRow(ctx, relationSave,
		arg.User1ID,
		arg.User2ID,
		arg.ActorID,
		arg.ChannelID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Type,
	)
	var i Relation
	err := row.Scan(
		&i.User1ID,
		&i.User2ID,
		&i.ActorID,
		&i.ChannelID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}
