// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions(id, user_id, created_at, updated_at, last_seen_at, expires_at, revoked_at, client_ip, refresh_token_hash, os, client, user_agent)
    VALUES ($1::uuid, $2::uuid, $3::timestamptz, $4::timestamptz, $5::timestamptz, $6::timestamptz, $7::timestamptz, $8::inet, $9::bytea, $10::text, $11::text, $12::text)
RETURNING
    id, user_id, created_at, updated_at, last_seen_at, expires_at, revoked_at, client_ip, refresh_token_hash, os, client, user_agent
`

type SessionCreateParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ClientIP         netip.Addr         `json:"client_ip"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	OS               string             `json:"os"`
	Client           string             `json:"client"`
	UserAgent        string             `json:"user_agent"`
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.ClientIP,
		arg.RefreshTokenHash,
		arg.OS,
		arg.Client,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionDeleteExpiredBatch = `-- name: SessionDeleteExpiredBatch :exec
WITH targets AS (
    SELECT
        id
    FROM
        sessions
    WHERE
        expires_at <= $1::timestamptz
    ORDER BY
        expires_at ASC,
        id ASC
    LIMIT $2::int
    FOR UPDATE
        SKIP LOCKED)
DELETE FROM sessions s USING targets t
WHERE s.id = t.id
`

type SessionDeleteExpiredBatchParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	BatchLimit int32              `json:"batch_limit"`
}

func (q *Queries) SessionDeleteExpiredBatch(ctx context.Context, arg SessionDeleteExpiredBatchParams) error {
	_, err := q.db.Exec(ctx, sessionDeleteExpiredBatch, arg.Now, arg.BatchLimit)
	return err
}

const sessionGet = `-- name: SessionGet :one
SELECT
    id,
    user_id,
    created_at,
    updated_at,
    last_seen_at,
    expires_at,
    revoked_at,
    client_ip,
    refresh_token_hash,
    os,
    client,
    user_agent
FROM
    sessions
WHERE
    id = $1::uuid
LIMIT 1
`

func (q *Queries) SessionGet(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGet, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionGetByRefreshTokenHash = `-- name: SessionGetByRefreshTokenHash :one
SELECT
    id,
    user_id,
    created_at,
    updated_at,
    last_seen_at,
    expires_at,
    revoked_at,
    client_ip,
    refresh_token_hash,
    os,
    client,
    user_agent
FROM
    sessions
WHERE
    refresh_token_hash = $1::bytea
LIMIT 1
`

func (q *Queries) SessionGetByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGetByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionRevoke = `-- name: SessionRevoke :exec
UPDATE
    sessions
SET
    revoked_at = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
    AND revoked_at IS NULL
`

type SessionRevokeParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) SessionRevoke(ctx context.Context, arg SessionRevokeParams) error {
	_, err := q.db.Exec(ctx, sessionRevoke, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	return err
}

const sessionRotateRefreshToken = `-- name: SessionRotateRefreshToken :one
UPDATE
    sessions
SET
    refresh_token_hash = $1::bytea,
    expires_at = $2::timestamptz,
    last_seen_at = $3::timestamptz,
    updated_at = $4::timestamptz,
    client_ip = $5::inet,
    user_agent = $6::text
WHERE
    id = $7::uuid
    AND refresh_token_hash = $8::bytea
    AND revoked_at IS NULL
    AND expires_at > $9::timestamptz
RETURNING
    id,
    user_id,
    created_at,
    updated_at,
    last_seen_at,
    expires_at,
    revoked_at,
    client_ip,
    refresh_token_hash,
    os,
    client,
    user_agent
`

type SessionRotateRefreshTokenParams struct {
	NewRefreshTokenHash []byte             `json:"new_refresh_token_hash"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClientIP            netip.Addr         `json:"client_ip"`
	UserAgent           string             `json:"user_agent"`
	ID                  pgtype.UUID        `json:"id"`
	OldRefreshTokenHash []byte             `json:"old_refresh_token_hash"`
	Now                 pgtype.Timestamptz `json:"now"`
}

func (q *Queries) SessionRotateRefreshToken(ctx context.Context, arg SessionRotateRefreshTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionRotateRefreshToken,
		arg.NewRefreshTokenHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.UpdatedAt,
		arg.ClientIP,
		arg.UserAgent,
		arg.ID,
		arg.OldRefreshTokenHash,
		arg.Now,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionUserListActive = `-- name: SessionUserListActive :many
SELECT
    id,
    user_id,
    created_at,
    updated_at,
    last_seen_at,
    expires_at,
    revoked_at,
    client_ip,
    os,
    client,
    user_agent
FROM
    sessions
WHERE
    user_id = $1::uuid
    AND revoked_at IS NULL
    AND expires_at > $2::timestamptz
ORDER BY
    last_seen_at DESC
LIMIT $3::int
`

type SessionUserListActiveParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	Now      pgtype.Timestamptz `json:"now"`
	LimitVal int32              `json:"limit_val"`
}

type SessionUserListActiveRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ClientIP   netip.Addr         `json:"client_ip"`
	OS         string             `json:"os"`
	Client     string             `json:"client"`
	UserAgent  string             `json:"user_agent"`
}

func (q *Queries) SessionUserListActive(ctx context.Context, arg SessionUserListActiveParams) ([]SessionUserListActiveRow, error) {
	rows, err := q.db.Query(ctx, sessionUserListActive, arg.UserID, arg.Now, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionUserListActiveRow
	for rows.Next() {
		var i SessionUserListActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ClientIP,
			&i.OS,
			&i.Client,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionUserRevokeAll = `-- name: SessionUserRevokeAll :exec
UPDATE
    sessions
SET
    revoked_at = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE
    user_id = $3::uuid
    AND revoked_at IS NULL
`

type SessionUserRevokeAllParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) SessionUserRevokeAll(ctx context.Context, arg SessionUserRevokeAllParams) error {
	_, err := q.db.Exec(ctx, sessionUserRevokeAll, arg.RevokedAt, arg.UpdatedAt, arg.UserID)
	return err
}
