// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions(id, user_id, created_at, updated_at, last_seen_at, expires_at, revoked_at, client_ip, refresh_token_hash, os, client, user_agent)
    VALUES ($1::uuid, $2::uuid, $3::timestamptz, $4::timestamptz, $5::timestamptz, $6::timestamptz, $7::timestamptz, $8::inet, $9::bytea, $10::text, $11::text, $12::text)
RETURNING
    id, user_id, created_at, updated_at, last_seen_at, expires_at, revoked_at, client_ip, refresh_token_hash, os, client, user_agent
`

type SessionCreateParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	ClientIP         netip.Addr         `json:"client_ip"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	OS               string             `json:"os"`
	Client           string             `json:"client"`
	UserAgent        string             `json:"user_agent"`
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.RevokedAt,
		arg.ClientIP,
		arg.RefreshTokenHash,
		arg.OS,
		arg.Client,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionDeleteBatchExpired = `-- name: SessionDeleteBatchExpired :exec
WITH targets AS (
    SELECT
        id
    FROM
        sessions
    WHERE
        expires_at <= $1::timestamptz
    ORDER BY
        expires_at ASC,
        id ASC
    LIMIT $2::int
    FOR UPDATE
        SKIP LOCKED)
DELETE FROM sessions
WHERE id IN (
        SELECT
            id
        FROM
            targets)
`

type SessionDeleteBatchExpiredParams struct {
	Now      pgtype.Timestamptz `json:"now"`
	LimitVal int32              `json:"limit_val"`
}

func (q *Queries) SessionDeleteBatchExpired(ctx context.Context, arg SessionDeleteBatchExpiredParams) error {
	_, err := q.db.Exec(ctx, sessionDeleteBatchExpired, arg.Now, arg.LimitVal)
	return err
}

const sessionGet = `-- name: SessionGet :one
SELECT
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
FROM
    sessions
WHERE
    id = $1::uuid
`

func (q *Queries) SessionGet(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGet, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionListValidByUserID = `-- name: SessionListValidByUserID :many
SELECT
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
FROM
    sessions
WHERE
    user_id = $1::uuid
    AND revoked_at IS NULL
    AND expires_at > $2::timestamptz
ORDER BY
    last_seen_at DESC
LIMIT $3::int
`

type SessionListValidByUserIDParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	Now      pgtype.Timestamptz `json:"now"`
	LimitVal int32              `json:"limit_val"`
}

func (q *Queries) SessionListValidByUserID(ctx context.Context, arg SessionListValidByUserIDParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionListValidByUserID, arg.UserID, arg.Now, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ClientIP,
			&i.RefreshTokenHash,
			&i.OS,
			&i.Client,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionRevoke = `-- name: SessionRevoke :exec
UPDATE
    sessions
SET
    revoked_at = $1::timestamptz,
    updated_at = $1::timestamptz
WHERE
    id = $2::uuid
    AND user_id = $3::uuid
    AND revoked_at IS NULL
`

type SessionRevokeParams struct {
	Now    pgtype.Timestamptz `json:"now"`
	ID     pgtype.UUID        `json:"id"`
	UserID pgtype.UUID        `json:"user_id"`
}

func (q *Queries) SessionRevoke(ctx context.Context, arg SessionRevokeParams) error {
	_, err := q.db.Exec(ctx, sessionRevoke, arg.Now, arg.ID, arg.UserID)
	return err
}

const sessionRevokeAll = `-- name: SessionRevokeAll :exec
UPDATE
    sessions
SET
    revoked_at = $1::timestamptz,
    updated_at = $1::timestamptz
WHERE
    user_id = $2::uuid
    AND revoked_at IS NULL
`

type SessionRevokeAllParams struct {
	Now    pgtype.Timestamptz `json:"now"`
	UserID pgtype.UUID        `json:"user_id"`
}

func (q *Queries) SessionRevokeAll(ctx context.Context, arg SessionRevokeAllParams) error {
	_, err := q.db.Exec(ctx, sessionRevokeAll, arg.Now, arg.UserID)
	return err
}

const sessionRotateRefreshTokenHash = `-- name: SessionRotateRefreshTokenHash :one
UPDATE
    sessions
SET
    refresh_token_hash = $1::bytea,
    expires_at = $2::timestamptz,
    last_seen_at = $3::timestamptz,
    updated_at = $3::timestamptz,
    client_ip = $4::inet,
    user_agent = $5::text
WHERE
    id = $6::uuid
    AND refresh_token_hash = $7::bytea
    AND revoked_at IS NULL
    AND expires_at > $3::timestamptz
RETURNING
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
`

type SessionRotateRefreshTokenHashParams struct {
	NewRefreshTokenHash []byte             `json:"new_refresh_token_hash"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	Now                 pgtype.Timestamptz `json:"now"`
	ClientIP            netip.Addr         `json:"client_ip"`
	UserAgent           string             `json:"user_agent"`
	ID                  pgtype.UUID        `json:"id"`
	OldRefreshTokenHash []byte             `json:"old_refresh_token_hash"`
}

func (q *Queries) SessionRotateRefreshTokenHash(ctx context.Context, arg SessionRotateRefreshTokenHashParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionRotateRefreshTokenHash,
		arg.NewRefreshTokenHash,
		arg.ExpiresAt,
		arg.Now,
		arg.ClientIP,
		arg.UserAgent,
		arg.ID,
		arg.OldRefreshTokenHash,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}
