// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions(id, user_id, refresh_token_hash, client_ip, user_agent, os, client, expires_at, last_seen_at, revoked_at, created_at, updated_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
`

type SessionCreateParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ClientIP         netip.Addr         `json:"client_ip"`
	UserAgent        string             `json:"user_agent"`
	OS               string             `json:"os"`
	Client           string             `json:"client"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ClientIP,
		arg.UserAgent,
		arg.OS,
		arg.Client,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionDeleteExpiredBatch = `-- name: SessionDeleteExpiredBatch :exec
WITH targets AS (
    SELECT
        id
    FROM
        sessions
    WHERE
        expires_at <= $1::timestamptz
    ORDER BY
        expires_at ASC,
        id ASC
    LIMIT $2::int
    FOR UPDATE
        SKIP LOCKED)
DELETE FROM sessions s USING targets t
WHERE s.id = t.id
`

type SessionDeleteExpiredBatchParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	BatchLimit int32              `json:"batch_limit"`
}

func (q *Queries) SessionDeleteExpiredBatch(ctx context.Context, arg SessionDeleteExpiredBatchParams) error {
	_, err := q.db.Exec(ctx, sessionDeleteExpiredBatch, arg.Now, arg.BatchLimit)
	return err
}

const sessionGet = `-- name: SessionGet :one
SELECT
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
FROM
    sessions
WHERE
    id = $1
`

func (q *Queries) SessionGet(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGet, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionGetByRefreshTokenHash = `-- name: SessionGetByRefreshTokenHash :one
SELECT
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
FROM
    sessions
WHERE
    refresh_token_hash = $1
`

func (q *Queries) SessionGetByRefreshTokenHash(ctx context.Context, refreshTokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGetByRefreshTokenHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionRotateRefreshToken = `-- name: SessionRotateRefreshToken :one
UPDATE
    sessions
SET
    refresh_token_hash = $1::bytea,
    expires_at = $2::timestamptz,
    last_seen_at = $3::timestamptz,
    updated_at = $4::timestamptz,
    client_ip = $5::inet,
    user_agent = $6::text
WHERE
    id = $7::uuid
    AND refresh_token_hash = $8::bytea
    AND revoked_at IS NULL
    AND expires_at > $9::timestamptz
RETURNING
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
`

type SessionRotateRefreshTokenParams struct {
	NewRefreshTokenHash []byte             `json:"new_refresh_token_hash"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt          pgtype.Timestamptz `json:"last_seen_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ClientIP            netip.Addr         `json:"client_ip"`
	UserAgent           string             `json:"user_agent"`
	ID                  pgtype.UUID        `json:"id"`
	OldRefreshTokenHash []byte             `json:"old_refresh_token_hash"`
	Now                 pgtype.Timestamptz `json:"now"`
}

func (q *Queries) SessionRotateRefreshToken(ctx context.Context, arg SessionRotateRefreshTokenParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionRotateRefreshToken,
		arg.NewRefreshTokenHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.UpdatedAt,
		arg.ClientIP,
		arg.UserAgent,
		arg.ID,
		arg.OldRefreshTokenHash,
		arg.Now,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionUpdate = `-- name: SessionUpdate :one
UPDATE
    sessions
SET
    user_id = $2,
    refresh_token_hash = $3,
    client_ip = $4,
    user_agent = $5,
    os = $6,
    client = $7,
    expires_at = $8,
    last_seen_at = $9,
    revoked_at = $10,
    updated_at = $11
WHERE
    id = $1
RETURNING
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
`

type SessionUpdateParams struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	ClientIP         netip.Addr         `json:"client_ip"`
	UserAgent        string             `json:"user_agent"`
	OS               string             `json:"os"`
	Client           string             `json:"client"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SessionUpdate(ctx context.Context, arg SessionUpdateParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionUpdate,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ClientIP,
		arg.UserAgent,
		arg.OS,
		arg.Client,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.RevokedAt,
		arg.UpdatedAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ClientIP,
		&i.RefreshTokenHash,
		&i.OS,
		&i.Client,
		&i.UserAgent,
	)
	return i, err
}

const sessionUpdateBatch = `-- name: SessionUpdateBatch :many
WITH input_data AS (
    SELECT
        jsonb_populate_recordset
    FROM
        jsonb_populate_recordset(NULL::sessions, $1::jsonb))
INSERT INTO sessions(id, user_id, refresh_token_hash, client_ip, user_agent, os, client, expires_at, last_seen_at, revoked_at, created_at, updated_at)
SELECT
    id,
    user_id,
    refresh_token_hash,
    client_ip,
    user_agent,
    os,
    client,
    expires_at,
    last_seen_at,
    revoked_at,
    created_at,
    updated_at
FROM
    input_data
ORDER BY
    id ASC
ON CONFLICT (id)
    DO UPDATE SET
        user_id = EXCLUDED.user_id,
        refresh_token_hash = EXCLUDED.refresh_token_hash,
        client_ip = EXCLUDED.client_ip,
        user_agent = EXCLUDED.user_agent,
        os = EXCLUDED.os,
        client = EXCLUDED.client,
        expires_at = EXCLUDED.expires_at,
        last_seen_at = EXCLUDED.last_seen_at,
        revoked_at = EXCLUDED.revoked_at,
        updated_at = EXCLUDED.updated_at
    RETURNING
        sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
`

func (q *Queries) SessionUpdateBatch(ctx context.Context, sessionsJson []byte) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionUpdateBatch, sessionsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ClientIP,
			&i.RefreshTokenHash,
			&i.OS,
			&i.Client,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionUserGetBatch = `-- name: SessionUserGetBatch :many
SELECT
    sessions.id, sessions.user_id, sessions.created_at, sessions.updated_at, sessions.last_seen_at, sessions.expires_at, sessions.revoked_at, sessions.client_ip, sessions.refresh_token_hash, sessions.os, sessions.client, sessions.user_agent
FROM
    sessions
WHERE
    user_id = $1::uuid
    AND revoked_at IS NULL
    AND expires_at > $2::timestamptz
ORDER BY
    last_seen_at DESC
LIMIT $3::int
`

type SessionUserGetBatchParams struct {
	UserID   pgtype.UUID        `json:"user_id"`
	Now      pgtype.Timestamptz `json:"now"`
	LimitVal int32              `json:"limit_val"`
}

func (q *Queries) SessionUserGetBatch(ctx context.Context, arg SessionUserGetBatchParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionUserGetBatch, arg.UserID, arg.Now, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ClientIP,
			&i.RefreshTokenHash,
			&i.OS,
			&i.Client,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionUserRevoke = `-- name: SessionUserRevoke :exec
UPDATE
    sessions
SET
    revoked_at = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE
    id = $3::uuid
    AND user_id = $4::uuid
    AND revoked_at IS NULL
`

type SessionUserRevokeParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) SessionUserRevoke(ctx context.Context, arg SessionUserRevokeParams) error {
	_, err := q.db.Exec(ctx, sessionUserRevoke,
		arg.RevokedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}

const sessionUserRevokeAll = `-- name: SessionUserRevokeAll :exec
UPDATE
    sessions
SET
    revoked_at = $1::timestamptz,
    updated_at = $2::timestamptz
WHERE
    user_id = $3::uuid
    AND revoked_at IS NULL
`

type SessionUserRevokeAllParams struct {
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
}

func (q *Queries) SessionUserRevokeAll(ctx context.Context, arg SessionUserRevokeAllParams) error {
	_, err := q.db.Exec(ctx, sessionUserRevokeAll, arg.RevokedAt, arg.UpdatedAt, arg.UserID)
	return err
}
