// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userAvailability = `-- name: UserAvailability :one
SELECT
    NOT EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            email = $1::citext)::boolean AS email_available,
    NOT EXISTS (
        SELECT
            1
        FROM
            users
        WHERE
            username = $2::citext)::boolean AS username_available
`

type UserAvailabilityParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

type UserAvailabilityRow struct {
	EmailAvailable    pgtype.Bool `json:"email_available"`
	UsernameAvailable pgtype.Bool `json:"username_available"`
}

func (q *Queries) UserAvailability(ctx context.Context, arg UserAvailabilityParams) (UserAvailabilityRow, error) {
	row := q.db.QueryRow(ctx, userAvailability, arg.Email, arg.Username)
	var i UserAvailabilityRow
	err := row.Scan(&i.EmailAvailable, &i.UsernameAvailable)
	return i, err
}

const userCreate = `-- name: UserCreate :exec
INSERT INTO users(id, email, username, display_name, password_hash, phone, bio, avatar_url, banner_color, preferred_presence, preferred_presence_until, verified_at, disabled_at, delete_scheduled_at, created_at, updated_at)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING
    users.id, users.created_at, users.updated_at, users.verified_at, users.disabled_at, users.delete_scheduled_at, users.preferred_presence_until, users.preferred_presence, users.email, users.username, users.display_name, users.password_hash, users.phone, users.bio, users.avatar_url, users.banner_color
`

type UserCreateParams struct {
	ID                     pgtype.UUID        `json:"id"`
	Email                  string             `json:"email"`
	Username               string             `json:"username"`
	DisplayName            string             `json:"display_name"`
	PasswordHash           string             `json:"password_hash"`
	Phone                  pgtype.Text        `json:"phone"`
	Bio                    pgtype.Text        `json:"bio"`
	AvatarUrl              pgtype.Text        `json:"avatar_url"`
	BannerColor            pgtype.Text        `json:"banner_color"`
	PreferredPresence      pgtype.Int2        `json:"preferred_presence"`
	PreferredPresenceUntil pgtype.Timestamptz `json:"preferred_presence_until"`
	VerifiedAt             pgtype.Timestamptz `json:"verified_at"`
	DisabledAt             pgtype.Timestamptz `json:"disabled_at"`
	DeleteScheduledAt      pgtype.Timestamptz `json:"delete_scheduled_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) error {
	_, err := q.db.Exec(ctx, userCreate,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Phone,
		arg.Bio,
		arg.AvatarUrl,
		arg.BannerColor,
		arg.PreferredPresence,
		arg.PreferredPresenceUntil,
		arg.VerifiedAt,
		arg.DisabledAt,
		arg.DeleteScheduledAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const userGet = `-- name: UserGet :one
SELECT
    users.id, users.created_at, users.updated_at, users.verified_at, users.disabled_at, users.delete_scheduled_at, users.preferred_presence_until, users.preferred_presence, users.email, users.username, users.display_name, users.password_hash, users.phone, users.bio, users.avatar_url, users.banner_color
FROM
    users
WHERE
    id = $1
`

func (q *Queries) UserGet(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.DeleteScheduledAt,
		&i.PreferredPresenceUntil,
		&i.PreferredPresence,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Bio,
		&i.AvatarUrl,
		&i.BannerColor,
	)
	return i, err
}

const userGetByEmail = `-- name: UserGetByEmail :one
SELECT
    users.id, users.created_at, users.updated_at, users.verified_at, users.disabled_at, users.delete_scheduled_at, users.preferred_presence_until, users.preferred_presence, users.email, users.username, users.display_name, users.password_hash, users.phone, users.bio, users.avatar_url, users.banner_color
FROM
    users
WHERE
    email = $1
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.DeleteScheduledAt,
		&i.PreferredPresenceUntil,
		&i.PreferredPresence,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Bio,
		&i.AvatarUrl,
		&i.BannerColor,
	)
	return i, err
}

const userListDeleteScheduled = `-- name: UserListDeleteScheduled :many
SELECT
    users.id, users.created_at, users.updated_at, users.verified_at, users.disabled_at, users.delete_scheduled_at, users.preferred_presence_until, users.preferred_presence, users.email, users.username, users.display_name, users.password_hash, users.phone, users.bio, users.avatar_url, users.banner_color
FROM
    users
WHERE
    delete_scheduled_at IS NOT NULL
    AND delete_scheduled_at <= $1::timestamptz
ORDER BY
    delete_scheduled_at ASC
LIMIT $2::int
`

type UserListDeleteScheduledParams struct {
	Now        pgtype.Timestamptz `json:"now"`
	BatchLimit int32              `json:"batch_limit"`
}

func (q *Queries) UserListDeleteScheduled(ctx context.Context, arg UserListDeleteScheduledParams) ([]User, error) {
	rows, err := q.db.Query(ctx, userListDeleteScheduled, arg.Now, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.DeleteScheduledAt,
			&i.PreferredPresenceUntil,
			&i.PreferredPresence,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Phone,
			&i.Bio,
			&i.AvatarUrl,
			&i.BannerColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userUpdate = `-- name: UserUpdate :one
UPDATE
    users
SET
    email = $2,
    username = $3,
    display_name = $4,
    password_hash = $5,
    phone = $6,
    bio = $7,
    avatar_url = $8,
    banner_color = $9,
    preferred_presence = $10,
    preferred_presence_until = $11,
    verified_at = $12,
    disabled_at = $13,
    delete_scheduled_at = $14,
    updated_at = $15
WHERE
    id = $1
RETURNING
    users.id, users.created_at, users.updated_at, users.verified_at, users.disabled_at, users.delete_scheduled_at, users.preferred_presence_until, users.preferred_presence, users.email, users.username, users.display_name, users.password_hash, users.phone, users.bio, users.avatar_url, users.banner_color
`

type UserUpdateParams struct {
	ID                     pgtype.UUID        `json:"id"`
	Email                  string             `json:"email"`
	Username               string             `json:"username"`
	DisplayName            string             `json:"display_name"`
	PasswordHash           string             `json:"password_hash"`
	Phone                  pgtype.Text        `json:"phone"`
	Bio                    pgtype.Text        `json:"bio"`
	AvatarUrl              pgtype.Text        `json:"avatar_url"`
	BannerColor            pgtype.Text        `json:"banner_color"`
	PreferredPresence      pgtype.Int2        `json:"preferred_presence"`
	PreferredPresenceUntil pgtype.Timestamptz `json:"preferred_presence_until"`
	VerifiedAt             pgtype.Timestamptz `json:"verified_at"`
	DisabledAt             pgtype.Timestamptz `json:"disabled_at"`
	DeleteScheduledAt      pgtype.Timestamptz `json:"delete_scheduled_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (User, error) {
	row := q.db.QueryRow(ctx, userUpdate,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Phone,
		arg.Bio,
		arg.AvatarUrl,
		arg.BannerColor,
		arg.PreferredPresence,
		arg.PreferredPresenceUntil,
		arg.VerifiedAt,
		arg.DisabledAt,
		arg.DeleteScheduledAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerifiedAt,
		&i.DisabledAt,
		&i.DeleteScheduledAt,
		&i.PreferredPresenceUntil,
		&i.PreferredPresence,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.Bio,
		&i.AvatarUrl,
		&i.BannerColor,
	)
	return i, err
}

const userUpdateBatch = `-- name: UserUpdateBatch :many
WITH input_data AS (
    SELECT
        jsonb_populate_recordset
    FROM
        jsonb_populate_recordset(NULL::users, $1::jsonb))
INSERT INTO users(id, email, username, display_name, password_hash, phone, bio, avatar_url, banner_color, preferred_presence, preferred_presence_until, verified_at, disabled_at, delete_scheduled_at, created_at, updated_at)
SELECT
    id,
    email,
    username,
    display_name,
    password_hash,
    phone,
    bio,
    avatar_url,
    banner_color,
    preferred_presence,
    preferred_presence_until,
    verified_at,
    disabled_at,
    delete_scheduled_at,
    created_at,
    updated_at
FROM
    input_data
ORDER BY
    id ASC
ON CONFLICT (id)
    DO UPDATE SET
        email = EXCLUDED.email,
        username = EXCLUDED.username,
        display_name = EXCLUDED.display_name,
        password_hash = EXCLUDED.password_hash,
        phone = EXCLUDED.phone,
        bio = EXCLUDED.bio,
        avatar_url = EXCLUDED.avatar_url,
        banner_color = EXCLUDED.banner_color,
        preferred_presence = EXCLUDED.preferred_presence,
        preferred_presence_until = EXCLUDED.preferred_presence_until,
        verified_at = EXCLUDED.verified_at,
        disabled_at = EXCLUDED.disabled_at,
        delete_scheduled_at = EXCLUDED.delete_scheduled_at,
        updated_at = EXCLUDED.updated_at
    RETURNING
        users.id, users.created_at, users.updated_at, users.verified_at, users.disabled_at, users.delete_scheduled_at, users.preferred_presence_until, users.preferred_presence, users.email, users.username, users.display_name, users.password_hash, users.phone, users.bio, users.avatar_url, users.banner_color
`

func (q *Queries) UserUpdateBatch(ctx context.Context, usersJson []byte) ([]User, error) {
	rows, err := q.db.Query(ctx, userUpdateBatch, usersJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VerifiedAt,
			&i.DisabledAt,
			&i.DeleteScheduledAt,
			&i.PreferredPresenceUntil,
			&i.PreferredPresence,
			&i.Email,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Phone,
			&i.Bio,
			&i.AvatarUrl,
			&i.BannerColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
